### ISSUE TITLE
Update fails for prerelease.

### ISSUE THREAD

**Issue by ArjixWasTaken** [LagradOst/CloudStream-3#10]
Welp...I am on a prerelease version (2nd from latest commit) and after trying to update to the other prerelease (latest commit) it um...failed to install.

I guess it has to do with the signature of the APK?
Either that or it's the version number.

**Comment by C10udburst** [comment]
As per [developers.android.com](https://developer.android.com/studio/publish/versioning):
> The Android system uses the `versionCode` value to protect against downgrades by preventing users from installing an APK with a lower `versionCode` than the version currently installed on their device.

So I'd assume that the debug signing is causing issues.
I could set up signing in the workflow, but you would probably want to change the signing key in github secrets afterwards

**Comment by LagradOst** [comment]
Ajix did you try bumping the ver number, beacause even with the correct signature, ver number remains supreme. You HAVE TO install a higher ver for it to work at all.

**Comment by C10udburst** [comment]
wait, so i did all that work in #11 for nothing? <img alt=":why:" width="16px" src="https://user-images.githubusercontent.com/18114966/129884217-caf07e71-937d-4380-a983-69488e3e0151.png">
