### ISSUE TITLE
Enhancement of New Search Bar On the Homepage

### ISSUE THREAD

**Issue by xololunatic** [LagradOst/CloudStream-3#1002]
UI/Ux enchantment Request:

Recently we got a new search bar in the Pre release on the homepage i liked it because it comes very handy but still I am disappointed that it does the same function as the old search section does.

So i got an idea that the search bar on the homepage should only search in the server we selected.
For example: If I had selected the server Sflix.to on the homepage then the search bar on the homepage should only search in that sflix.to server and not other servers.

While as the seprate search section will remain as it is.
That will come a lot handy, and i think it's easy to add also.

Please consider this I think it's very amazing feature 
Thank you.

**Comment by Adbc3949** [comment]
I thought the same 
That would be a lot better

**Comment by xololunatic** [comment]
Ya it will be. I wish the developers will take it seriously....

**Comment by houdini101** [comment]
I think its in the settings, but I'm not sure though.

**Comment by xololunatic** [comment]
No I know that's called ADVANCED SEARCH.. what i am talking about is way to different

**Comment by LagradOst** [comment]
Try latest pre

**Comment by xololunatic** [comment]
Yaa nicely done thankyou
