### ISSUE TITLE
Watching 

### ISSUE THREAD

**Issue by Gottarocket** [LagradOst/CloudStream-3#1003]
**Guidelines:**
- [ x] It **is not** a duplicate issue.
- [x ] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other ✓

**Describe your request here** *(fill this up)*
- [ ] How it works.
If you had "watching" shows before recent prerelease its deleted after update.  So next time same show if searched on search first section should have all "watched","watching","watch later" of that shows
- [ ] Issues it solves. 
Even if there is a bug which deletes "watching" from home page we can search it and find it quickly
- [ ] Why it is needed.

Some shows dont play right as you need with all providers so you would need to search for that correct provider and once you do you will forget who it was as you can click on play under "watching" on home page and watch it but if it disappears we need search again until we find that provider which did play that video directly

**Other related info**
 If this cant we done atleast separate option to see history of shows we watched so we can find what we watched before

**Comment by LagradOst** [comment]
what????

**Comment by imurreflection** [comment]
I think he mentioned clearly that watch history will be deleted with latest pre-release. Before, there was no such issue with watch history
