### ISSUE TITLE
Downloads tab doesn't detect downloaded content in some cases.

### ISSUE THREAD

**Issue by SlamZDank** [LagradOst/CloudStream-3#1011]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**
1. Go to a tv show or an anime that has some special characters like ` : ` in its name (basically characters that are unsupported while naming a folder)
2. Download an episode
3. Go to the downloads tab

**Expected behavior**
The downloaded content gets shown in the downloads tab.

**Actual behavior**
No sign of its existance until looking for it in the download directory.

![Screenshot_20220429-224140_CloudStream Beta](https://user-images.githubusercontent.com/83764499/166072863-736d02a4-68b3-4d50-a6b8-ad25f7e65f6a.png)
![Screenshot_20220429-224158_CloudStream Beta](https://user-images.githubusercontent.com/83764499/166072874-29e3e350-7a9e-49ba-828c-3bb83fc77d6e.png)
![Screenshot_20220429-224219_My Files](https://user-images.githubusercontent.com/83764499/166072876-04deefdb-09fc-4ece-a7c9-c5456e46ac9a.png)

**Device**
 - Android Version: Android 11
 - App Version: latest pre-release

**Additional info**
Movies aren't affected by this bug.

**Comment by LagradOst** [comment]
👀

**Comment by LagradOst** [comment]
Able to replicate

**Comment by LagradOst** [comment]
So this will be fixed in 24h
