### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Kevintsm** [LagradOst/CloudStream-3#1012]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [ ] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*
- [ ] How it works.
- [ ] Issues it solves.
- [ ] Why it is needed.

**Other related info**
Please check this site: https://modagamers.com/
https://animexin.xyz/

**Comment by LagradOst** [comment]
#24
