### ISSUE TITLE
Cloudstream Beta Problem

### ISSUE THREAD

**Issue by darthsinniious1989** [LagradOst/CloudStream-3#1015]
Ok, so I updated cloudstream beta & it seemed to have worked for a little while but then, I tried to watch all the Bunnyman movies but I couldn't. Whether it said no links or didn't load at all. This is for all the providers in the movie section. It didn't even work in the regular cloudstream either.

**Comment by LagradOst** [comment]
Both worked fine for me

**Comment by darthsinniious1989** [comment]
Well not for me.

**Comment by LagradOst** [comment]
Use vpn or the dns in app

**Comment by darthsinniious1989** [comment]
I am using a vpn, expressvpn. Which dns though? I'm using adguard.
