### ISSUE TITLE
Tag Thenos as Movie/TV Show provider

### ISSUE THREAD

**Issue by erazemk** [LagradOst/CloudStream-3#102]
Currently Thenos only shows up if Anime providers are selected, but it also offers TV Shows and Movies. Would it be possible to "tag" it as a Movie / TV Show provider as well, so that users who don't watch anime don't have to have all anime providers enabled?

**Comment by LagradOst** [comment]
What?

**Comment by erazemk** [comment]
Sorry, after retesting to describe the issue more clearly it appears that for whatever reason the issue isn't there anymore. Originally I thought Thenos was only available if the anime option was enabled, but it appears it works even if the anime option is disabled.
