### ISSUE TITLE
req

### ISSUE THREAD

**Issue by imxcr** [LagradOst/CloudStream-3#1021]
please add option for the background/window subtitles to adjust corner radius

**Comment by imxcr** [comment]
https://user-images.githubusercontent.com/98096677/166424682-8c68a62d-83d6-489a-b776-e5696a3c129e.mp4

**Comment by imxcr** [comment]
or maybe like this
![IMG_20220503_163452.jpg](https://user-images.githubusercontent.com/98096677/166425112-b0fa87c4-ad64-40bb-80a2-bd89df810347.jpg)

**Comment by imxcr** [comment]
or like this ^^
![IMG_20220503_163452.jpg](https://user-images.githubusercontent.com/98096677/166425291-d75be52a-96c3-4c0e-bef7-0df91b36de85.jpg)

**Comment by LagradOst** [comment]
Not possible
