### ISSUE TITLE
Animeworld and movierulzhd

### ISSUE THREAD

**Issue by Thorodinson1** [LagradOst/CloudStream-3#1022]
Hey Bro can you add this 👇👇👇

https://anime-world.in/

It have dubbed anime in many languages.👆👆👆👆

Also this 👇👇👇

https://movierulzhd.bar/

👆👆 This have movie and TV in many languages, as we can choose dubbed Audio for each series or movies.
❤️❤️❤️

**Comment by LagradOst** [comment]
#24
