### ISSUE TITLE
Custom primary color

### ISSUE THREAD

**Issue by ZooNooU** [LagradOst/CloudStream-3#1028]
### Describe your suggested feature

as the title says, an option for custom primary color option alongside the stock ones (just 3 simple RGB sliders are more than enough)
if that's possible of course and doesn't require an annoying amount of efforts/time..

it's been opened before but it was November of last year so I thought bout re-opening it..

### Other details

I had to check the 1st box so it gets submitted, sorry dev 💀

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No, android does not like that
