### ISSUE TITLE
There. I fixed it

### ISSUE THREAD

**Issue by MrConqueror** [LagradOst/CloudStream-3#1029]
### Describe your suggested feature

![IMG_20220505_093739](https://user-images.githubusercontent.com/102837820/166852348-062016c6-598c-46f8-a047-c6289229bfd1.jpg) 

For me Cs3 is one of the streaming app that has better Player. It's very responsive when u Click or tap on the center the icons shows faster unlike Saikou there's some animation there. And those icons are not large or very white as well. I also like the idea of putting icons under seekbar. But the info and source Quality ruined it.

And for Tittle It's already put on poster, in All Movies/Tvseries. And because of the text some movies Tittle is hard to read as it's blocking the real title on Movie/TV series poster. Good thing there's an option to put it under, but would it be nice if there's no Title text at all? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
:okand: might fix idk
