### ISSUE TITLE
Chromecast only works for some episodes 

### ISSUE THREAD

**Issue by saurabhinabys** [LagradOst/CloudStream-3#103]
For any show, only few episodes cast others play on app only.

**Comment by LagradOst** [comment]
Provider?

**Comment by saurabhinabys** [comment]
All providers have same issue. First few episodes cast easily, then others just try to load and fail without any warning.

**Comment by saurabhinabys** [comment]
Dude, can i help someway to identify exact reason?

**Comment by saurabhinabys** [comment]
in general and pre-release both problem persists. And it just won't cast after first few episodes of any show, even with VLC connection just keeps trying to load content and fail after a while.

**Comment by LagradOst** [comment]
> 
> 
> in general and pre-release both problem persists. And it just won't cast after first few episodes of any show, even with VLC connection just keeps trying to load content and fail after a while.

If VLC cant cast it, then I cant cast it. My guess is that you are trying to cast on a provider with no chromecast support that is not marked yet.

**Comment by saurabhinabys** [comment]
Oh, okay. Thanks anyway. Your app is awesome, thanks for your work.
