### ISSUE TITLE
Time

### ISSUE THREAD

**Issue by HousGreet** [LagradOst/CloudStream-3#1035]
### Describe your suggested feature

Could you add an option to display remaining time in the player like in Netflix? Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No, exo does not like that
