### ISSUE TITLE
Zoro 2004 http problem

### ISSUE THREAD

**Issue by Korontos123** [LagradOst/CloudStream-3#1037]
### Steps to reproduce

1.choose any anime from zoro provider
2.select the source to " zoro source "
3. gives me a message that says " ERROR_CODE_IO_BAD_HTTP_STATUS(2004) " and closes the player 

### Expected behavior

the anime play according to my selection normally 

### Actual behavior

it gives me the error and the player closes

### Cloudstream version

2.9.25 (pre-release)

### Android version

Android 8

### Other details

it doesn't matter if i chose 
![Screenshot_20220507-171419_CloudStream Beta](https://user-images.githubusercontent.com/104093479/167263035-e12dffc2-2447-4f7a-ae77-fb7830847b10.jpg)
sub or dub

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
@LagradOst Looks like zoro updated their shit again, about time we switch to websockets anyways :pensive: 
I tested rollback, doesn't seem to be the cause :thinking:
