### ISSUE TITLE
Preview download size

### ISSUE THREAD

**Issue by Starlord619** [LagradOst/CloudStream-3#104]
Is there a way to preview video size before downloading it
It could be really useful if we know file size before downloading any video

**Comment by LagradOst** [comment]
I will have to do an additional get request for every link for every episode. So I cant add it like I would do the description of the episode, and if you wanted to find out the size then the user (you) would have to click some kind of preview size button.

**Comment by ArjixWasTaken** [comment]
Um, this is a completely useless feature.
Since you can just start the download, cancel it and voila, you now know the filesize.

**Comment by LagradOst** [comment]
> 
> 
> Um, this is a completely useless feature.
> Since you can just start the download, cancel it and voila, you now know the filesize.

bruh, I think he wanted a more ergonomic solution that does not require 10 clicks to see the file size.

**Comment by ArjixWasTaken** [comment]
> > Um, this is a completely useless feature.
> > Since you can just start the download, cancel it and voila, you now know the filesize.
> 
> bruh, I think he wanted a more ergonomic solution that does not require 10 clicks to see the file size.

And that's a pain to add properly.

**Comment by LagradOst** [comment]
That is what I said
