### ISSUE TITLE
Adjust text border thickness 

### ISSUE THREAD

**Issue by oroboros** [LagradOst/CloudStream-3#1040]
### Describe your suggested feature

On my Android TV, I need subtitles at 36, but border is so thin that from far away, subtitles are difficult to read when the screen is white.

Would there be the chance of adjusting text border thickness please? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
no can do, it is a private field and no official way of overriding it https://github.com/google/ExoPlayer/blob/02f7aafe67b4893134a31ea55a3ba0f0535df145/library/ui/src/main/java/com/google/android/exoplayer2/ui/SubtitlePainter.java#L55
