### ISSUE TITLE
Kisskh.me provider

### ISSUE THREAD

**Issue by mg8297819** [LagradOst/CloudStream-3#1046]
### Describe your suggested feature

Please add kisskh.me provider, it has the latest kdrama and they upload super fast for new episodes. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
