### ISSUE TITLE
Error Playing Certain Movies

### ISSUE THREAD

**Issue by Tuba202** [LagradOst/CloudStream-3#105]
I was trying to watch Shang Chi this weekend, and came across this weird error:

Source error
None of the available extractors
(FlvExtractor, FlacExtractor, WavExtractor,
FragmentedMp4Extractor, Mp4Extractor,
AmrExtractor, PsExtractor, OggExtractor,
TsExtractor, Matroska Extractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.

Does anyone know why this is happening?
It is happening on the AllMoviesForYou source.

**Comment by LagradOst** [comment]
Wack link, the source probs generated a link but it points to no content, or that is my guess.
