### ISSUE TITLE
More Source Request

### ISSUE THREAD

**Issue by dykti** [LagradOst/CloudStream-3#1050]
### Describe your suggested feature

After using the app for some time I realized the app has some great sources which provide movies, tv shows, anime, etc. But, it lacked many Bollywood movies and tv shows and also Hindi dubbed versions of Popular non-Hindi shows. The ones that are present are often 'no links found' or very bad quality. I would request you to add some more sources for Indian shows and movies. 

Suggestion:
Source --> https://www.mytrustworth.com/literature/seasons/hindi-seasons/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
