### ISSUE TITLE
FaselHD problems 

### ISSUE THREAD

**Issue by HousGreet** [LagradOst/CloudStream-3#1054]
### Source information

FaselHD

### Source link

www.faselhd.top

### Steps to reproduce

1. My preferred watch quality is 480p so when i open the stream it directly starts at 480p.
2. After a few seconds with dark screen an error occurs which prevent the video from starting.
3. If i choose other quality like 360p it works normally, this is happening for every movie/show, only a few qualities work and others don't.
![Screenshot_20220513-224426_CloudStream Beta](https://user-images.githubusercontent.com/92183042/168380115-c18e4b21-fa99-490c-b834-d496a0a815de.jpg)

### CloudStream version

2.9.25 beta

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by ImZaw** [comment]
try watching on the site itself u would face problems with watching so its a them problem we can't do anything for now

**Comment by HousGreet** [comment]
For example the tv show The Office only works at 360p other qualities give an error as the screenshot above.

**Comment by ImZaw** [comment]
can't fix it, FaselHD's problem.
You can figure that by watching from their site.

**Comment by HousGreet** [comment]
Ok thank you.
