### ISSUE TITLE
Subtitles Elevation

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/CloudStream-3#1056]
It seems that even after selecting 'Zero' or "10' in subtitles Elevation settings in either pre-release beta or in CS3, subtitles still overlaps on the original video which was not the case earlier. It used to be below video. Can u pls fix it.

**Comment by LagradOst** [comment]
Send ss

**Comment by imurreflection** [comment]
Please see the SS. 
Movie: Morbius. 
Provider: sop2day
![Screenshot_2022-05-15-08-42-05-59_965bbf4d18d205f782c6b8409c5773a4](https://user-images.githubusercontent.com/30263396/168455735-27f56e5b-c764-4c06-a4b8-156530754baf.jpg)
![Screenshot_2022-05-15-08-41-44-98_965bbf4d18d205f782c6b8409c5773a4](https://user-images.githubusercontent.com/30263396/168455736-bd6a8d5a-5072-4875-886a-ac5b9f882a54.jpg)
Movie: Uncharted
Provider: sop2day
![Screenshot_2022-05-15-08-41-23-65_965bbf4d18d205f782c6b8409c5773a4](https://user-images.githubusercontent.com/30263396/168455752-94cd29da-0e6f-4d4c-9754-0ec14eeadb93.jpg)
![Screenshot_2022-05-15-08-40-57-14_965bbf4d18d205f782c6b8409c5773a4](https://user-images.githubusercontent.com/30263396/168455753-69520268-5089-490a-9a4d-c958275de85a.jpg)

**Comment by LagradOst** [comment]
So it should be lower down correct?

**Comment by imurreflection** [comment]
Yes, as it was previously

**Comment by LagradOst** [comment]
So this only affects prerelease?

**Comment by imurreflection** [comment]
Not really..but after the latest pre-release and CS3 update, it started.

**Comment by imurreflection** [comment]
This seems to be an issue with a particular provider only. In some others, it's working fine. Closing the issue now. Thanks
