### ISSUE TITLE
turkanime.co provider 

### ISSUE THREAD

**Issue by kyoyacchi** [LagradOst/CloudStream-3#1058]
### Describe your suggested feature

Please add turkanime.co as provider, it's best site for watching anime in Turkish.

### Other details

(It has fansubs)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24

**Comment by kyoyacchi** [comment]
> #24

When will you add it? At least respond..

**Comment by LagradOst** [comment]
Providers are posted in #24, and no I wont add it because there is alreasy 100+ providers that are already requested and adding a provider takes several hours

**Comment by kyoyacchi** [comment]
> Providers are posted in #24, and no I wont add it because there is alreasy 100+ providers that are already requested and adding a provider takes several hours

Bruh. Are you serious?

**Comment by LagradOst** [comment]
1000%

**Comment by LagradOst** [comment]
All providers added sence like 10mo ago is from pr. I have not done a provider in a very long time
