### ISSUE TITLE
Source links not showing resolution in ver 2.10.25

### ISSUE THREAD

**Issue by JimZiii** [LagradOst/CloudStream-3#1060]
### Steps to reproduce

Open source on any video playing

### Expected behavior

To get multiple links from the same source with different resolutions

### Actual behavior

Multiple links, all with the exact same name and no resolution to distinguish them

### Cloudstream version

2.10.25

### Android version

12

### Other details

This image is from 2.9.25, showing all the resolutions next to the links
![Screenshot_20220516-002555_CloudStream](https://user-images.githubusercontent.com/7854537/168497004-945a7983-f6aa-4ab6-b938-9a69c26a4c3f.jpg)

This is from 2.10.25, with all the resolutions gone
![Screenshot_20220516-002629_CloudStream Beta](https://user-images.githubusercontent.com/7854537/168497015-205c5453-eb11-4794-b6df-b1dbd0b22953.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Adbc3949** [comment]
Yup Facing Same Issue Here
Gotta try downloading each link to figure out the 1080p one lol

**Comment by JimZiii** [comment]
Seems to be working again after the latest patch
