### ISSUE TITLE
How do i turn off google drive backup?

### ISSUE THREAD

**Issue by JimZiii** [LagradOst/CloudStream-3#1061]
Not sure which version this was added in but it's one of the relatively recent ones since it didn't used to happen.

I tried to get a fresh install but no matter what i did, i kept getting my old settings and movies first time starting it. I don't have a lot of experience with google drive backup, especially not with it automatically restoring everything without asking me, so it took me a good while to figure out what was going on.

I'm just wondering if it's possible to turn it off or if you could add the option to turn it off in a future update because i can't remove just one app from the backup, i have to delete the whole backup or turn it off completely to stop it from restoring

**Comment by LagradOst** [comment]
Clear the data of the app in system settings

**Comment by JimZiii** [comment]
Even after clearing data, after a fresh install its back to my old settings and movies, which is why it took me a while to figure out what was happening because I've never seen that happen before lol.
I know i can clear data after every fresh install and opening it for the first time, just thought you might want to add a more permanent solution in the future.

If its even possible

**Comment by LagradOst** [comment]
It is not possible because it is an outside feature that I have no control over
