### ISSUE TITLE
Vidstream and Mcloud Links not Showing Up 

### ISSUE THREAD

**Issue by Adbc3949** [LagradOst/CloudStream-3#1072]
### Steps to reproduce

Open 9anime, Sflix.pro, Bflix etc that have Vidstream and Mcloud Links

### Expected behavior

The Links Show and Play

### Actual behavior

The Vidstream and Mcloud Links do not Show up at all

### Cloudstream version

2.10.25

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
@Adbc3949 Try my fork, this should be fixed

**Comment by Adbc3949** [comment]
> @Adbc3949 Try my fork, this should be fixed

Nope Not Working

**Comment by KillerDogeEmpire** [comment]
> > @Adbc3949 Try my fork, this should be fixed
> 
> Nope Not Working

it works for me though...

**Comment by Tolga077** [comment]
I'm having the same problem. Fmovies no longer works.

**Comment by Tolga077** [comment]
> > > @Adbc3949 Try my fork, this should be fixed
> > 
> > 
> > Nope Not Working
> 
> it works for me though...
Some of your mirror sources are working. Is it possible to combine those sources with fmovies.to subtitles? Only fmovies has subtitles in so many languages.
