### ISSUE TITLE
Provider Arabic 

### ISSUE THREAD

**Issue by Abdelkaderkhelfi** [LagradOst/CloudStream-3#1073]
### Source information

Egybest

### Source link

https://ww.egy.best/

### Steps to reproduce

1. Website content is not working
2.  The problem appeared in the version 2.9.24
3.  In the previous version, the link to the site was as follows  https://egybest.cafe/
4. In this version, the following link has become          https://ww.egy.best/
5. When you open a movie, a dark color screen appears written in it " couldn't find média links "
      

### CloudStream version

2.9.24

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Already exits in app, use pre-release and enable Arabic sites.

**Comment by Abdelkaderkhelfi** [comment]
Try this link EGY BEST
https://egybest.biz/
