### ISSUE TITLE
Can someone please add some indian movies sites as well.

### ISSUE THREAD

**Issue by harpreet100** [LagradOst/CloudStream-3#1078]
### Describe your suggested feature

Limited Indian content. Most of those have no link.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24

**Comment by harpreet100** [comment]
I don't get it. Why is this closed?

**Comment by LagradOst** [comment]
Post all your sites in #24 dont bloat issues
