### ISSUE TITLE
No Audio and No links on hdmovie5.tv

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/CloudStream-3#1085]
Hi Dev,
On many links, the audio does not play on first link in CS beta. Examples would be Beast, Bhool Bhulaya, Snow Piercer season 1&2 (no link found) and many more but they play absolutely fine in mobile or web browser.

Perhaps Shivam brahmkshatriya from @saikou-app can look into this as he is the one who got this source added

**Comment by imurreflection** [comment]
In addition to the above issue, now, none of the movie plays. No issue with the site though. Can you please fix it as this is the only Hindi site

**Comment by imurreflection** [comment]
Dear Dev, please try to fix this..this is the only site with Indian language content. Also, is there any tutorial we can learn and try a pull request?

**Comment by KillerDogeEmpire** [comment]
@brahmkshatriya

**Comment by imurreflection** [comment]
Hi @brahmkshatriya
Can you please look at this issue mate..
Btw- this is a fabulous ID :smiley:

**Comment by imurreflection** [comment]
This is working now. Closing the issue
