### ISSUE TITLE
Trailers.to not working 

### ISSUE THREAD

**Issue by MohamadBayz** [LagradOst/CloudStream-3#1088]
### Source information

Trailers.to

### Source link

https://trailers.to/video/cloudstream/tmdb/2673/S4E6

### Steps to reproduce

1- search for "The O.C." 
2- Open Season 4 Episode 6 
3 - says link not found

### CloudStream version

2.9.24

### Android version

Android 12.1

### Other details

Mostly says link not found when i try like 10 times restarting the app then i get lucky and one of the links works after that one again says no link found 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Trailers. to is fucked for many series and there is nothing I can do about it. If the api gives an invalid link then use another provider as trailers. to wont work.

**Comment by MohamadBayz** [comment]
Ok thanks dude
