### ISSUE TITLE
Crash when canceling a download

### ISSUE THREAD

**Issue by tonya1545b** [LagradOst/CloudStream-3#109]
The app crash when canceling a download

**Comment by LagradOst** [comment]
On pre-release or release?

**Comment by LagradOst** [comment]
(The download system was somewhat reworked in pre-release so if you are still experiencing this is pre-release then I will mark this as a bug)

**Comment by timnea** [comment]
I was wanting to test the bug tonight with the pre-release version but the latest pre-release crash when trying to start app.

**Comment by LagradOst** [comment]
Fuck, I checked. This is due to chromecast behaving wack. I did exactly as the android docs, but it still crashes for some ppl. :pain:

**Comment by LagradOst** [comment]
Try now

**Comment by tonya1545b** [comment]
It works in the latest pre-release.

**Comment by tonya1545b** [comment]
And it crash again with version 2.0
