### ISSUE TITLE
Provider request

### ISSUE THREAD

**Issue by venkat2305** [LagradOst/CloudStream-3#1093]
Is it possible to add kamyroll ?

**Comment by KillerDogeEmpire** [comment]
@venkat2305 they don't want to because kamyroll is pretty much crunchyroll, and they don't want a DMCA take down from crunchyroll.

If you want Kamyroll/Crunchyroll you can use my fork of cs3 or you can use @Stormunblessed he has crunchyroll in his cs3 too

**Comment by KillerDogeEmpire** [comment]
Here is the link to my fork 
https://github.com/KillerDogeEmpire/CloudStream-3

Here is Stormunblessed's
https://github.com/Stormunblessed/CloudStream-3

**Comment by venkat2305** [comment]
> Here is the link to my fork 
> https://github.com/KillerDogeEmpire/CloudStream-3
> 
> Here is Stormunblessed's fork
> https://github.com/Stormunblessed/CloudStream-3

Thanks for your help and  Do you plan to add anl sync for crunchyroll?
