### ISSUE TITLE
Vidstream and Mcloud not Working Again 

### ISSUE THREAD

**Issue by Adbc3949** [LagradOst/CloudStream-3#1095]
### Steps to reproduce

Try playing anything in 9anime, Sflix.pro, Bflix etc

### Expected behavior

Vidstream and Mcloud Links Show and Play 

### Actual behavior

No Vidstream and Mcloud Links 

### Cloudstream version

2.10.25

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Zeroo097** [comment]
Did you get the solution?
