### ISSUE TITLE
Pre-Release Archive

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/CloudStream-3#1099]
Dear Dev, is it possible to have access to all pre-releases archive si that we can revert to previous release if we have any issue. I am asking it because before 2.1.24 pre-release, HD Movie 5 was working fine but now it says 'No Link Found' on every movie

**Comment by KillerDogeEmpire** [comment]
> Dear Dev, is it possible to have access to all pre-releases archive si that we can revert to previous release if we have any issue. I am asking it because before 2.1.24 pre-release, HD Movie 5 was working fine but now it says 'No Link Found' on every movie

that won't solve the problem that's dut to the site

**Comment by imurreflection** [comment]
May i know what is the issue with site. I have observed few things:
1) Domain has been changed to .top instead of .tv
2) they are not using bull stream or dood stream any more 
3. No cloudfare or anti bot issue
 Hope this helps

**Comment by KillerDogeEmpire** [comment]
> May i know what is the issue with site. I have observed few things:
> 
> 1. Domain has been changed to .top instead of .tv
> 2. they are not using bull stream or dood stream any more
> 3. No cloudfare or anti bot issue
>    Hope this helps

It could have updated their anti scrape. wait for a fix, even though it doesn't look like they have cloudflare they could have cloudflare

**Comment by odnar-dev** [comment]
also it help to keep track of changelog

**Comment by Blatzar** [comment]
All changelog seen in pre-release updates can be found [here](https://github.com/LagradOst/CloudStream-3/commits/master)

**Comment by imurreflection** [comment]
Thank you all for your replies. Closing the issue now
