### ISSUE TITLE
9anime Bugs and Download Method Problems

### ISSUE THREAD

**Issue by legendartist58** [LagradOst/CloudStream-3#1100]
9anime provider isn't working properly, some animes aren't showing completely in the app, for example:

Fruits Basket Season 2 isn't showing in the app, even the download method isn't working.

Please fix M4UPLOAD Download Method, thanks.

Vidstream, Streamtape and others 9anime servers also aren't working in the app.

**Comment by KillerDogeEmpire** [comment]
9anime keeps updating their keys, wait for a fix.
