### ISSUE TITLE
ANDROID TV - Retry Connection... Error

### ISSUE THREAD

**Issue by TuupacFR** [LagradOst/CloudStream-3#1107]
### Steps to reproduce

When i click on any specific anime, i get the retry connection error. Every time. It used to work well before. 
![IMG_20220529_134643](https://user-images.githubusercontent.com/99209812/170862073-38fa0169-f68e-4e67-ae27-8c53099c9118.jpg)

### Expected behavior

Play the video/ or show the anime list of episodes 

### Actual behavior

Connection error

### Cloudstream version

2.9.24

### Android version

10

### Other details

Works perfectly on my Android phone, but not on my tv anymore 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by esodigoyo** [comment]
It is the same in my android phone. Previous version works normally.

**Comment by hritik2144** [comment]
Having same problem with andriod (9anime)

**Comment by hritik2144** [comment]
![Uploading Screenshot_20220601-095836_CloudStream.jpg…]()

**Comment by hritik2144** [comment]
![Screenshot_20220601-095836_CloudStream](https://user-images.githubusercontent.com/106645346/171327910-8c6cc41e-215a-4d50-8d96-365a988082cd.jpg)
Having same problem with Android (9anime)

**Comment by JimZiii** [comment]
It's been fixed in the beta version a few days ago, if you want to use those sources while waiting for the new patch just download the beta version.
You can have both versions installed at the same time so it's fairly easy to move between them. And i think you can backup your settings and database from the stable version and restore it in the beta, so you don't have to go over everything again.
