### ISSUE TITLE
Anime Provider Request

### ISSUE THREAD

**Issue by AhmedShiryu34** [LagradOst/CloudStream-3#1125]
There is an arabic language Provider, site called anime4up , There's only english Providers for anime in the app , it would be great if you add this website as provider of anime shows or any other arabic Provider for anime specifically
Keep up the good work ❤️

### Other details
Anime4up link : https://anime4up.art/
_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
#24
