### ISSUE TITLE
Request: a separate "wishlist" for animes

### ISSUE THREAD

**Issue by JimZiii** [LagradOst/CloudStream-3#1126]
### Describe your suggested feature

Would it be possible to add a second wishlist for anime with all the same categories as the current one?
I have a lot of movies and series bookmarked and currently I've had to use the "completed" category for animes since it's more convenient to have them separate.

A second idea would be to implement the list from either anilist or mal and have it sync everything with the account you signed in with.
The result either way is separate lists for regular movies/series and animes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No plans atm to expand the categories, the second a duplicate request of #912
