### ISSUE TITLE
Olgply source in the wrong categories

### ISSUE THREAD

**Issue by JimZiii** [LagradOst/CloudStream-3#1127]
On the search tab olgply should only be in movies and series but currently it's also in anime and cartoons.

Also, on the home tab when choosing a source to show, olgply is the only source in cartoons, watchcartoononline is gone completely while olgply is still in anime and the only source in cartoons.

It's really minor but it's a bit annoying when searching by category and you get things from an unrelated source.

**Comment by KillerDogeEmpire** [comment]
I feel Like Olgply should have stayed in all categories because it has anime, and cartoons ontop of movies and tv shows
