### ISSUE TITLE
'Preferred quality to auto' option

### ISSUE THREAD

**Issue by Kanishk2910** [LagradOst/CloudStream-3#1129]
Add an option to automatically switch quality based on the internet connection (preety useful for mobile data users).
The quality is already set at 4k for me by default and didn't notice until I used the app to watch without wifi.
As mobile data is limited and player buffers a lot, it ruins the watching experience.

**Comment by LagradOst** [comment]
No, we are not netflix and can switch video quality on the fly, and I am not gonna do speed tests every time you try to watch smth

**Comment by Kanishk2910** [comment]
Okay then
BTW thanks for making such good
