### ISSUE TITLE
ghost animation

### ISSUE THREAD

**Issue by andsofine** [LagradOst/CloudStream-3#1130]
is it possible to make such animations work without any changes on the top?

https://user-images.githubusercontent.com/99369164/172088623-92eac352-677d-4533-910c-f1ccf113a8ec.mp4

**Comment by LagradOst** [comment]
> Android moment 

I did not explicitly write anywhere that this "ghost animation" should happened, it is just android being wack. This also does not on my A10 phone so A12 is probs fucking it up for you.

**Comment by LagradOst** [comment]
Because it cant be fixed
