### ISSUE TITLE
provider selection window closes the keyboard

### ISSUE THREAD

**Issue by andsofine** [LagradOst/CloudStream-3#1132]
this probably shouldn't happen. I also think this popup should be placed higher so that it can be seen simultaneously with the keyboard

and it seems the bottom panel should not be above the keyboard

https://user-images.githubusercontent.com/99369164/172092310-dd703aec-6acd-4b90-986c-529693bae047.mp4

**Comment by LagradOst** [comment]
This is the intended behavior as there exist people with no screen real estate and the provider section is quite long.

**Comment by LagradOst** [comment]
Simply no, if you use english providers it will take up the entire screen and some more. I dont want to place them into 2 columnas that looks and feels ugly
