### ISSUE TITLE
Feature of quality before downloading a video

### ISSUE THREAD

**Issue by mrnoone101** [LagradOst/CloudStream-3#1142]
### Describe your suggested feature

Feature of quality before downloading a video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No

**Comment by LagradOst** [comment]
you can hold an episode to download a specific quality
