### ISSUE TITLE
Can you add "Speeding up" setting like UC Browser?

### ISSUE THREAD

**Issue by zeref-dragneel** [LagradOst/CloudStream-3#1146]
### Describe your suggested feature

Does CloudStream application support "speeding up" like UC Browser?
I want to buffer videos 100% like UC Browser while they play and not just a few seconds of it. Because I have a slow internet connection, and it would be really convenient if I could fully load a video instead of just a few seconds of it. Thank you very much
![image](https://user-images.githubusercontent.com/95934994/172390264-6024f895-0879-459f-85d1-f9628f383428.png)

### Other details

[UC Browser for Android](https://m.apkpure.com/uc-browser/com.UCMobile.intl)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
You can adjust both buffer size and buffer length in settings :+1: 
Just make sure you have enough RAM otherwise it may crash.
![image](https://user-images.githubusercontent.com/46196380/172423397-4de53a85-81bf-4d0f-b97a-ddd2a8f8259d.png)
