### ISSUE TITLE
Is it Possible to add compressor or reduce the size of Videos while downloading

### ISSUE THREAD

**Issue by mrnoone101** [LagradOst/CloudStream-3#1152]
### Describe your suggested feature

well, as I see on other sites or apps there is some kind of compressor that reduce the size of videos. For example 300mb to 400mb for 720p. But when I download from CloudStream it shows the size of mostly videos between 500mb to 600mb. I dont know if you already implemented it or not but if you work a little bit more on downloader or compressor then it might b good. Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
Hold the episode you want to download then select download mirror
![Uploading Screenshot_20220607-224911_CloudStream Beta.jpg…]()

**Comment by KillerDogeEmpire** [comment]
![Screenshot_20220607-224911_CloudStream Beta](https://user-images.githubusercontent.com/87155550/172541425-ce3c866b-d999-4321-81da-d5eabf5356eb.jpg)

**Comment by mrnoone101** [comment]
I tried it but 720 & 1080 Videos has same size mostly

**Comment by mrnoone101** [comment]
Whenever I download videos from even different providers the size of videos (720) are above 500mb to 600mb, I just want to give you a little suggestion if you can reduce more size of videos. It would be good in 300mb to 400mb for 720p

**Comment by KillerDogeEmpire** [comment]
That depends on the provider, I don't think they can do that

**Comment by LagradOst** [comment]
Nope
