### ISSUE TITLE
No links found but original website play video

### ISSUE THREAD

**Issue by pranimation** [LagradOst/CloudStream-3#1163]
### Source information

Trailers.to

### Source link

https://trailers.to/en/tvshow/6290/2-broke-girls-2011

### Steps to reproduce

Search : 2 broke girls
Click on: trailers.to provider
Click on any episode.
Output:No links found
Same episode will play on website.

### CloudStream version

2.10.28

### Android version

6

### Other details

This I checked with only trailers.to but I suspect other provider like 2embed,sflix are having same problem. Need to varify first.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
The api does not have it

**Comment by pranimation** [comment]
This is strange, as I watched the same show this week, bummer.
