### ISSUE TITLE
Is it possible to add Queue feature in downloading videos

### ISSUE THREAD

**Issue by mrnoone101** [LagradOst/CloudStream-3#1176]
### Describe your suggested feature

If you can add this feature then it would be great, well when I download three episodes at same time first video gets download first and rest should go in queue whenever first download video completed then it should download itselft second and so on..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Queue already exist, but max 3 downloads at the same time

**Comment by mrnoone101** [comment]
But there is a bug whenever download 3 different episodes but it download the same episodes, I already opened the bug, but you didnt reply yet
