### ISSUE TITLE
Can't restore data on tv

### ISSUE THREAD

**Issue by venkat2305** [LagradOst/CloudStream-3#1178]
Unable to restore data on tv
It says there's no app that can do that on my tv

**Comment by CR1MS0N24** [comment]
Any solution that you have for the problem?

**Comment by venkat2305** [comment]
nope. Do you have the same issue?

**Comment by CR1MS0N24** [comment]
Yep been looking if there is an app for it for a while now

**Comment by venkat2305** [comment]
I wish, devs look into this.

**Comment by venkat2305** [comment]
Check this videohttps://user-images.githubusercontent.com/55329452/174402505-011b4e8e-5f68-4591-96b4-45b1dc8ab594.mp4

**Comment by CR1MS0N24** [comment]
ok so at least for you it does have tools to run that option but it doesnt know how yet

**Comment by Blatzar** [comment]
This app works on Android TV emulator for me: https://apkpure.com/file-manager/com.alphainventor.filemanager
Please try

**Comment by venkat2305** [comment]
> This app works on Android TV emulator for me: https://apkpure.com/file-manager/com.alphainventor.filemanager
> Please try
> 

Thank you so much. It totally worked.

**Comment by CR1MS0N24** [comment]
thanks
