### ISSUE TITLE
In-App Movie Trailers support

### ISSUE THREAD

**Issue by MUCHACHO19** [LagradOst/CloudStream-3#1181]
### Describe your suggested feature

Can you guys provide the option to watch trailers or previews from within the app(like Netflix)?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Check out pre-release

**Comment by mrmakrider** [comment]
dear the trailers not working in android tv version only mobile version

**Comment by LagradOst** [comment]
yes, they are not implemented on tv yet
