### ISSUE TITLE
Request to add a site

### ISSUE THREAD

**Issue by tombad098** [LagradOst/CloudStream-3#1184]
### Describe your suggested feature

First of all, thank you very much for this beautiful app I would like to add this site to the application. This site displays all Turkish series, translated and dubbed into Arabic.
https://eshiq.net/

### Other details

https://eshiq.net/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by zeref-dragneel** [comment]
#24

**Comment by LagradOst** [comment]
#24
