### ISSUE TITLE
No links found

### ISSUE THREAD

**Issue by unOmni** [LagradOst/CloudStream-3#1187]
### Source information

Dopebox

### Source link

www.dopebox.to

### Steps to reproduce

1. Choose a video to watch
2. No links found pops up

### CloudStream version

2.10.28

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Works in the latest pre-release
