### ISSUE TITLE
No Links

### ISSUE THREAD

**Issue by darthsinniious1989** [LagradOst/CloudStream-3#1194]
### Steps to reproduce

What the hell is the deal here? No even the non-beta version of cloudstream wanted to load up links today. It says no links with almost all providers. One of those providers is solarmovies. Why is cloudstream having so much issues? I left the beta version for the original for that exact reason. Fix it please. I'm honestly pissed cloudstream is having so much issues lately.

### Expected behavior

All providers will play whatever video I watch without any issues. 

### Actual behavior

No Links

### Cloudstream version

2.10.28

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
The current beta is 2.10.29, and I can confirm that solarmovies works on the latest pre. The reason why like 6 providers shut down at the same time is that all of them are the clone of 2 sites. Those 2 sites updated encryption

**Comment by LagradOst** [comment]
There is legit nothing we can do if the site decides to update. We need to update cs3 and then ppl need to install that update
