### ISSUE TITLE
Documentary site add-on request

### ISSUE THREAD

**Issue by tombad098** [LagradOst/CloudStream-3#1197]
### Describe your suggested feature

The application does not contain documentaries providers. I suggest reviewing some sites and adding them to the application if possible, it will be good

### Other details

https://watchdocumentaries.com/

https://www.documentarystorm.com/

https://topdocumentaryfilms.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
