### ISSUE TITLE
No link

### ISSUE THREAD

**Issue by gadz91** [LagradOst/CloudStream-3#1198]
### Source information

dopebox, sflix

### Source link

dopebox.to sflix.to

### Steps to reproduce

1. search We are breaking up in dopebox
2. click episode 2
3. issue No links found although in the site its working. 

### CloudStream version

2.10.28 beta

### Android version

android 10

### Other details

![Screenshot_2022-06-19-11-51-28-97](https://user-images.githubusercontent.com/86019036/174465109-cf3af792-d948-4c4d-91af-923b4570e002.jpg)
![Screenshot_2022-06-19-11-51-28-97](https://user-images.githubusercontent.com/86019036/174465158-0d66b786-896d-4c67-92c7-3aee9d2feac0.jpg)

No links found even though but in the site it has and its working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
update to 29
