### ISSUE TITLE
Please add provider/website

### ISSUE THREAD

**Issue by Adi432144** [LagradOst/CloudStream-3#1199]
### Describe your suggested feature

I want you guys to add this website to your app please
www.dramacool.city
This is best website to watch/download drama 

### Other details

Please THINK if want and check the website and you will also found it awesome ☺️
This is website: www.dramacool.city

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
