### ISSUE TITLE
Is Adding Hulu Will Be Possible.

### ISSUE THREAD

**Issue by Yashmak620** [LagradOst/CloudStream-3#1201]
### Describe your suggested feature

I am Suggesting Adding Hulu Because closed Captions.Especially For Anime,
I Am Getting a felling you would not add the hulu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No
