### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by Winner875** [LagradOst/CloudStream-3#1203]
### Steps to reproduce

1. Click on the download button
2. Download

### Expected behavior

It should download normally

### Actual behavior

It downloads with excess mb 

### Cloudstream version

2.10.28

### Android version

Android 9

### Other details

I hope it is fixable

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
I dont understand the issue

**Comment by Winner875** [comment]
> I dont understand the issue

It's for only gogo anime because that's what I checked. Like an episode that is 40mb will be 60-70mb when I download it with the internal downloader.
Is there a problem with the internal downloader or it's on my own end ?

**Comment by LagradOst** [comment]
The downloader is getting reworked rn, but I think it is just an m3u8 (the size estimate on a m3u8 can be wrong with 100mb). If it does not duplicate it or download it many times this is not a bug.
