### ISSUE TITLE
Gogoanime Randomly Changes Resolution

### ISSUE THREAD

**Issue by yant0** [LagradOst/CloudStream-3#1216]
### Source information

Gogoanime

### Source link

Gogoanime

### Steps to reproduce

1. Open app
2. Select gogoanime provider
3. Select anime
4. Set source as gogoanime

### CloudStream version

2.10.29-PRE

### Android version

11

### Other details

Gogoanime source randomly change video resolution every few seconds. In the source tab, it does not provide each gogoanime video resolution.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
It is an m3u8
