### ISSUE TITLE
Tagalog providers are not showing 

### ISSUE THREAD

**Issue by Rubberxgum** [LagradOst/CloudStream-3#1218]
### Steps to reproduce

1. Set Tagalog as one of the provider languages.
2. Select the menu button on the search section
 

### Expected behavior

Providers of selected languages should be showing including Tagalog.

### Actual behavior

Tagalog providers are not showing.

### Cloudstream version

2.10.28

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Tagalog only has asian dramas, do you have that selected?

**Comment by Rubberxgum** [comment]
Oh! I actually selected anime as my preferred media. I didn't realize that it would remove the Asian dramas. It shows now after setting my preferred media to all.
