### ISSUE TITLE
How to turn OFF subtitles altogether?

### ISSUE THREAD

**Issue by stakeout55** [LagradOst/CloudStream-3#1227]
Hey!!! THANK YOU so much for this lovely application. It is incredible. I cant seem to find an option to turn OFF all subtilties altogether? Any ideas? Thank you! 

Edit: I found the ability to turn them off when the App Layout is "phone" but not when the app layout is "tv"

Edit edit: force closed app, now seems to be working. Any way to disable subtitles by default??? Thank you!

**Comment by LagradOst** [comment]
yes, set default to none in sub settings
