### ISSUE TITLE
Metada

### ISSUE THREAD

**Issue by Elsuu** [LagradOst/CloudStream-3#1234]
### Steps to reproduce

 Trailers.to Metada is not provided by site video loading will fail if it dose not exist on site.

### Expected behavior

Not opening

### Actual behavior

Its not working

### Cloudstream version

2.10.30

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
> Trailers.to Metada is not provided by site video loading will fail if it dose not exist on site.

This means that the video will not load if it's on trailers.to. Re-open this if the show is available to watch on trailers.to, but not in app and say what you are trying to watch.
