### ISSUE TITLE
add site

### ISSUE THREAD

**Issue by tombad098** [LagradOst/CloudStream-3#1238]
### Describe your suggested feature

I think this provider would be good to add to the application, but I don't know if it works or not, please take a look

https://yseries.tv/home/

### Other details

https://yseries.tv/home/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
#24
