### ISSUE TITLE
Download Quality

### ISSUE THREAD

**Issue by Aditya190803** [LagradOst/CloudStream-3#1239]
There is no option to change the download quality as i download using my mobile data 350mb for one episode is way too much

**Comment by KillerDogeEmpire** [comment]
Click/tap and hold the episode you want to download and then click/tap download mirrors
![Screenshot_20220705-002131_CloudStream Beta](https://user-images.githubusercontent.com/87155550/177272523-c0fda251-50c5-4d87-aac6-91a2b34a7890.jpg)
![Screenshot_20220705-002138_CloudStream Beta](https://user-images.githubusercontent.com/87155550/177272553-579efb34-f0d0-4590-bb12-fbf9f37741c7.jpg)
 and select what server you want to download
