### ISSUE TITLE
German Providers

### ISSUE THREAD

**Issue by TubaApollo** [LagradOst/CloudStream-3#124]
Hey, i have a few German Movie/Anime Sites, would be nice if a Site which is implementable, could be added. 

**Movie Providers**
- https://bs.to/ (Movies and Animes)
- https://s.to/ (Movies)
- https://www2.kinox.to/ (Movies)

**Anime Providers**
- https://anicloud.io/ (Anime)
- https://www2.aniflix.tv/ (Anime)
- https://beta.animecloud.tv/ (Anime)
- https://pure-anime.net/ (Anime, they also seem to have own streaming server)

**Comment by LagradOst** [comment]
pr > issue 🙏 🙏 🙏 🙏

**Comment by dystopiaTD** [comment]
Another one that seems to be without captchas:
https://www1.streamcloud.club/
Series and movies
