### ISSUE TITLE
Subtitle from internet.

### ISSUE THREAD

**Issue by infinite-007** [LagradOst/CloudStream-3#1249]
### Steps to reproduce

Steps to reproduce:
1. Load subtitle from internet
2. Choose a subtitle from the list
3. When the movie/show is resumed with the subtitle loaded, it doesn't resume instantaneously. As if the source is loaded afresh.

### Expected behavior

The movie/show should resume instantaneously.

### Actual behavior

When the movie/show is resumed with the subtitle loaded, it doesn't resume instantaneously. As if the source is loaded afresh.

### Cloudstream version

2.10.28

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
I have already looked into this and I was unable to solve it. I am not aware of a way to fix it or if it even is fixable. It could just be a technical limitation in exoplayer.
