### ISSUE TITLE
Monoschinos

### ISSUE THREAD

**Issue by mormmi** [LagradOst/CloudStream-3#1253]
### Source information

Monoschinos

### Source link

wwwmonoschinos2.com

### Steps to reproduce

Null Pointer Exception  at Monoschinos Provider.kt 53
Site might  have updated o added Cloudflare/DDOS protection

### CloudStream version

2.10.30-PRE

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
