### ISSUE TITLE
The source https://hdmovie2.to is not working in CS3 latest pre-release. Please look into this. Only source in Hindi language.

### ISSUE THREAD

**Issue by infinite-007** [LagradOst/CloudStream-3#1263]
The source https://hdmovie2.to is not working in CS3 latest pre-release. Please look into this. Only source in Hindi language.

_Originally posted by @infinite-007 in https://github.com/LagradOst/CloudStream-3/issues/24#issuecomment-1178693499_

**Comment by Blatzar** [comment]
[Fixed](https://github.com/LagradOst/CloudStream-3/commit/4b6d941d4df7feb3ec31575a2d623d320c34ee0a)
