### ISSUE TITLE
Provider Request

### ISSUE THREAD

**Issue by infinite-007** [LagradOst/CloudStream-3#1264]
### Describe your suggested feature
Please add this source:

https://einthusan.tv/

No Cloudflare protection. But may be inaccessible in some region and a VPN may be required. Has huge collection and fast server speed. Mostly south-Asian content (Hindi, Bengali, Marathi, Telegu, Tamil, Malayalam, Kanada, etc.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
