### ISSUE TITLE
Olgply source not working

### ISSUE THREAD

**Issue by infinite-007** [LagradOst/CloudStream-3#1272]
### Source information

Olgply

### Source link

https://olgply.com/

### Steps to reproduce

1. Switch to olgply source from source list
2. Open any movie/show
3. Play it
4. No link found
However can play it using the website in a browser. Probably the site has updated as it was down for some days.

### CloudStream version

cloustream beta 2.10.30

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by mattrizzo66** [comment]
I had also been following this, and had noticed the Olgply site was down for about 10 days due to "server issues".  The repairs have been made and site back up for the last day or two.  

So probably just need to resynch some connections in Cloudstream.

**Comment by infinite-007** [comment]
Olgply fixed
