### ISSUE TITLE
issues with oploverz and nontonanimeid

### ISSUE THREAD

**Issue by MyraDragneel** [LagradOst/CloudStream-3#1282]
### Source information

Oploverz and NontonAnimeID

### Source link

https://65.108.132.145 and https://75.119.159.228

### Steps to reproduce

there are some anime with oploverz and nontonanimeid providers that cannot be opened in the application but can be opened on the website.
![Screenshot_20220712-052605_CloudStream_Beta](https://user-images.githubusercontent.com/83377700/178369897-71321e3f-089e-4855-a470-8b17cd1bb872.png)
![Screenshot_20220712-052614_CloudStream_Beta](https://user-images.githubusercontent.com/83377700/178369905-32fb73c3-f02a-4ec9-af6d-2f8f1b4f4541.png)

### CloudStream version

2.10.30-PRE

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by hexated** [comment]
Tell me what animes and how many..?

**Comment by MyraDragneel** [comment]
> Tell me what animes and how many..?

some anime movies like sao progressive and others

**Comment by hexated** [comment]
i'll fix it. beofre that, try to open that anime from search not from home. it will work

**Comment by MyraDragneel** [comment]
> i'll fix it. beofre that, try to open that anime from search not from home. it will work

okay👍
