### ISSUE TITLE
9anime not working

### ISSUE THREAD

**Issue by ya221ne** [LagradOst/CloudStream-3#1284]
### Source information

9anime

### Source link

9anime.id

### Steps to reproduce

select 9anime when searching an anime

### CloudStream version

2.10.28

### Android version

android 12

### Other details

due to website ui change. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [x] I will fill out all of the requested information in this form.

**Comment by Adbc3949** [comment]
Still not working in 3.0.1

**Comment by ya221ne** [comment]
> Still not working in 3.0.1

because website layout changed and links too

**Comment by sharqo** [comment]
Now it shows invalid argument
