### ISSUE TITLE
Cross Platform

### ISSUE THREAD

**Issue by NoelJacob** [LagradOst/CloudStream-3#1288]
### Describe your suggested feature

Would be cool

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NoelJacob** [comment]
why maybe?

**Comment by LagradOst** [comment]
Too much work
