### ISSUE TITLE
My List Feature (Similar to Netflix)

### ISSUE THREAD

**Issue by ProGamerisYT** [LagradOst/CloudStream-3#1289]
### Describe your suggested feature

Hello. I was wondering if CloudStream could add a similar feature to Netflix in which one can add certain shows or movies to their own list/watchlist? That would improve user experience as it would allow users to watch their pick up dramas at a later date without having to struggle to refind them. 

### Other details

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/109209728/178809253-054d8b2d-4efb-46ce-97b0-4694481b1162.png">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Already exists, see: 
![image](https://user-images.githubusercontent.com/46196380/178817240-48b942de-24a2-491a-b1cb-a458308635a2.png)
