### ISSUE TITLE
Streaming video quality shows

### ISSUE THREAD

**Issue by max5354** [LagradOst/CloudStream-3#1295]
### Describe your suggested feature

Add support for video quality that shows streaming video quality like 720p,1080p,2k etc. In video player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Press the source button to switch quality and current quality is always shown
