### ISSUE TITLE
Add VLC video player support

### ISSUE THREAD

**Issue by max5354** [LagradOst/CloudStream-3#1296]
### Describe your suggested feature

Add vlc video player support. So we can watch movies/series in vlc media player instead of default video player 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Already exist, hold and play with vlc
