### ISSUE TITLE
Voice search option for android tv

### ISSUE THREAD

**Issue by krrishkap** [LagradOst/CloudStream-3#1301]
### Describe your suggested feature

i was thinking can voice search be implemented for android tv coz typing on a tv is too sluggish 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Is that not provided by your controller or keyboard?

**Comment by krrishkap** [comment]
> Is that not provided by your controller or keyboard?

no its there for only youtube, other ott platforms and google assistant by default for me at least

**Comment by krrishkap** [comment]
![SHA_20220717_212059494_8 4 400](https://user-images.githubusercontent.com/86251706/179406265-eba84845-37bc-4a25-bd56-a95f1d32e370.jpg)
![SHA_20220717_212201360_8 4 400](https://user-images.githubusercontent.com/86251706/179406404-1f0d7933-5915-494d-89a1-a1b93bc970ff.jpg)
see like this in yt app and on remote a specific button for assistant

**Comment by krrishkap** [comment]
nvm

**Comment by LagradOst** [comment]
????????

**Comment by krrishkap** [comment]
> ????????

it was my bad , i didnt see that gboard had a voice typing option for tv you just have enable it in settings 😅
