### ISSUE TITLE
2embed : Link Not Found 

### ISSUE THREAD

**Issue by OshekharO** [LagradOst/CloudStream-3#1303]
### Source information

2embed

### Source link

https://2embed.org

### Steps to reproduce

1. Open the app
2. Choose 2embed Provider
3. Open any movie
4. See the error.

### CloudStream version

2.10.31

### Android version

Android 11

### Other details

I think there is need to fix link extractor ( servers ) for 2embed. I was not able to check that as i don't have my pc with me. please check once else revert back to 2embed.to if you don't want to.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Dont ping

**Comment by OshekharO** [comment]
> Dont ping

Okk

**Comment by Blatzar** [comment]
I think this was solved in https://github.com/LagradOst/CloudStream-3/pull/1302

**Comment by OshekharO** [comment]
> I think this was solved in #1302

Nope i think the issue exist here: [TwoEmbedProvider.kt#L60](https://github.com/OshekharO/CloudStream-3/blob/e14a7f8d9e3fe3799e1dad6cd6c737887c7b89e7/app/src/main/java/com/lagradost/cloudstream3/movieproviders/TwoEmbedProvider.kt#L60)
