### ISSUE TITLE
BOLLYWOOD MOVIES

### ISSUE THREAD

**Issue by Kaluku10** [LagradOst/CloudStream-3#1304]
### Describe your suggested feature

Is it possible to add bollywood movies in the app it will be very great because i know alot of people love them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
