### ISSUE TITLE
can you add hurawatch.cc and kickassanime?

### ISSUE THREAD

**Issue by raged2214** [LagradOst/CloudStream-3#1309]
### Describe your suggested feature

can you add hurawatch.cc and kickassanime? thats the site i mostly visiting. and animedao or animesuge.cc?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
