### ISSUE TITLE
Add a hungarian/english movie source provider

### ISSUE THREAD

**Issue by d4f5409d** [LagradOst/CloudStream-3#1310]
### Describe your suggested feature

Add https://online-filmek.me as a movie provider wherefrom we can stream our favorite movies in the Hungarian language

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24
