### ISSUE TITLE
request to add hindi source

### ISSUE THREAD

**Issue by dan8443** [LagradOst/CloudStream-3#1318]
### Describe your suggested feature

there is only one Hindi source hdmove2.org  that is not showing series episodes **(also if you can fix the problem is it only shows the last episode of the series for** **, for example, ms marvel, the bots S3 almost every new series added** ).
I want to request to add one more Hindi source I have some good recommendations these also provide other local Asian languages  please add one of them
1)https://yomovies.plus/
2)https://prmovies.one/
3) https://yesmovies4u.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shubham01015** [comment]
Yes ... That will be very helpful

**Comment by KillerDogeEmpire** [comment]
#24
