### ISSUE TITLE
some filipino sites that could work i guess

### ISSUE THREAD

**Issue by gregorio0h** [LagradOst/CloudStream-3#1323]
### Describe your suggested feature

https://pmh.li/
https://pinoymoviepedia.ru/
https://watchpinoymovies.su/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
#24
