### ISSUE TITLE
Fast Forward >> / Rewind << in Media Player

### ISSUE THREAD

**Issue by intellimediatv** [LagradOst/CloudStream-3#1326]
The Media player does not allow the user to properly fast forward or rewind the content regardless which of the server hosts one is using to play the content. When attempted the stream just spins and refuses to play is this due to the media player that is being used can this be fixed in next update especially for non mobile devices which use this app on a TV

**Comment by LagradOst** [comment]
what

**Comment by intellimediatv** [comment]
When you try to fast forward the movie or tv show or try to rewind it just sits bufferring. Unable to fast forward or rewind content it does not resume playing on non mobile devices using the app for i.e on a android tv device

**Comment by LagradOst** [comment]
That is exoplayer + not netflix servers

**Comment by intellimediatv** [comment]
Developer so why on other apps using exoplayer fastforward and rewind works for media being played

**Comment by LagradOst** [comment]
Already exists
