### ISSUE TITLE
French provider

### ISSUE THREAD

**Issue by MrFlappy0** [LagradOst/CloudStream-3#1327]
### Describe your suggested feature

Hi, I'm looking for the best streaming site for France because there is only one provider and in addition it is bug 1 time out of 2 (so if you can put them on quickly that would be great) ( the actualy french provider is off every time )
I put you a site related to each category

Manga : https://vostfree.cx/

all kinds : 
https://sokrostream.tube/ 
https://filmzenstream.tube/ 
https://www.libertyland.al/ 
https://wiflix.bet/ 
https://french-stream.ac/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24

**Comment by MrFlappy0** [comment]
? what is #24

**Comment by MrFlappy0** [comment]
mmh
