### ISSUE TITLE
Airplay

### ISSUE THREAD

**Issue by noah010** [LagradOst/CloudStream-3#1330]
### Describe your suggested feature

Hello, is it possible to add a feature that allows you to cast media from Cloudstream to your TV using Airplay?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
no

**Comment by noah010** [comment]
> no

Why?

**Comment by LagradOst** [comment]
apple stuff is fucked
