### ISSUE TITLE
Banners on sflix.to episodes 

### ISSUE THREAD

**Issue by venkat2305** [LagradOst/CloudStream-3#1334]
![IMG_20220725_142120.jpg](https://user-images.githubusercontent.com/55329452/180737583-ed5e919e-db93-4d65-9f0c-4372587870a6.jpg)

It doesn't look good. I know it's the same in the site. Can you add something ( like the poster )to them to make it look it better.

Please close this issue, if you feel this is a waste of your time

**Comment by LagradOst** [comment]
If it is the same on the site, thrn ofc we cant add posters
