### ISSUE TITLE
Support playing external stream links

### ISSUE THREAD

**Issue by AlyafeiAli** [LagradOst/CloudStream-3#1335]
### Describe your suggested feature

Currently, it supports playing external video files that are stored locally, but it doesn't support playing external links.

For example, in MiXplorer, I'm able to open local videos in Cloudstream, but when I try to open direct stream links (from MiXplorer using my gdrive), Cloudstream is not listed in the available apps. 

Same thing in Stremio and other apps, Cloudstream doesn't show up as an option when I try to play a direct link, it only shows up as an option when I play local files.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AlyafeiAli** [comment]
Are you sure it was fixed, @LagradOst ?
I just installed the latest pre-release and it's still not showing up when playing a streaming link, it only shows up when playing a locally saved file

Online files:
![Screenshot_20220726-070131_MiXplorer](https://user-images.githubusercontent.com/52626961/180914084-593dbb6e-e0aa-41bf-a0b5-100e54d869fa.jpg)

Offline files work:
![Screenshot_20220726-070248_MiXplorer](https://user-images.githubusercontent.com/52626961/180914192-af54c147-8fe5-407e-84b0-8949a5bad2fd.jpg)

**Comment by LagradOst** [comment]
I can look into it, but what I added was share > play with cloudstream
