### ISSUE TITLE
Kindly add Vmovee link 

### ISSUE THREAD

**Issue by Sersi001** [LagradOst/CloudStream-3#1343]
### Describe your suggested feature

Many links doesn't work or have movies. Vmovee is one of those links which had 90% content in it. Please add that link in the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
#24 ?
