### ISSUE TITLE
Json parse issue while clicking on sflixpro 

### ISSUE THREAD

**Issue by Ayub-Git** [LagradOst/CloudStream-3#1345]
### Steps to reproduce

Filter with sflix pro
Select any video and this exception occurs 

### Expected behavior

Open and play video

### Actual behavior

Exception occurs

### Cloudstream version

2.10.29

### Android version

12

### Other details

`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
known issue
