### ISSUE TITLE
MAL client not synchrone

### ISSUE THREAD

**Issue by willyreza** [LagradOst/CloudStream-3#1351]
### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### Cloudstream version

3.0.0

### Android version

Android 12

### Other details

mall client is not syncing properly. please fix it soon.

![Screenshot_20220727-051017_MyAnimeList](https://user-images.githubusercontent.com/3974476/181121130-30308f7f-2cb0-43d8-938c-f1b5d586164b.jpg)
![Screenshot_20220727-051117_CloudStream](https://user-images.githubusercontent.com/3974476/181121155-3d1ca5b2-3f60-4405-9ff6-b982387700c4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Unable to replicate
