### ISSUE TITLE
FaselHD is no longer there?

### ISSUE THREAD

**Issue by ZooNooU** [LagradOst/CloudStream-3#1353]
### Steps to reproduce

1. Go arabic providers
2. FaselHD isn't there anymore

### Expected behavior

FaselHD shud be with other Arabic providers

### Actual behavior

No FaselHD 

### Cloudstream version

3.0.1

### Android version

12L

### Other details

FaselHD is one of the best Arabic providers in the app,, whay happened to it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Disabled

**Comment by ZooNooU** [comment]
> Disabled

May I know why?
