### ISSUE TITLE
video player

### ISSUE THREAD

**Issue by glorymaster** [LagradOst/CloudStream-3#1363]
### Describe your suggested feature

I love how the trailer play, it plays smoothly.
I suggest that in the next next update.. the videos can be played like how we play the trailer, and can browse the cs3 app while the video is playing...
thanks btw... great fellows. 
![Screenshot_20220730-012909](https://user-images.githubusercontent.com/71760685/181814002-33c47b6f-0cfd-47d1-ba33-02ec880f159f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
no
