### ISSUE TITLE
Please add this source

### ISSUE THREAD

**Issue by infinite-007** [LagradOst/CloudStream-3#1378]
### Describe your suggested feature

Please add this source:
https://primewire.id/home

### Other details

Simple interface and easy to implement. Has great content from various countries.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
#24
