### ISSUE TITLE
9anime not working since yesterday

### ISSUE THREAD

**Issue by lemonking909** [LagradOst/CloudStream-3#1379]
### Source information

9anime

### Source link

https://9anime.id

### Steps to reproduce

![Screenshot_20220801-161235_CloudStream Beta](https://user-images.githubusercontent.com/106336779/182104037-70bf65d6-2b2c-41ff-8ce3-95c7670f1ae6.jpg)

### CloudStream version

3.0.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/LagradOst/CloudStream-3/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Known issue
