### ISSUE TITLE
Sources not working

### ISSUE THREAD

**Issue by thelord81** [LagradOst/CloudStream-3#1390]
### Describe your suggested feature

My greetings
Most of the sources are not working or are incorrect or the web page has been changed please fix it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
update to pre

**Comment by thelord81** [comment]
How?
