### ISSUE TITLE
WCO Stream

### ISSUE THREAD

**Issue by Igrissid** [LagradOst/CloudStream-3#140]
I'm sorry about this but WCO Stream is experiencing a certain error for the pre version. Remote Error 
ERROR_CODE_IO_BAD_HTTP_STATUS (2004)
Source error 
This error appears when you are trying to watch some shows. For example, Evangelion.

**Comment by Igrissid** [comment]
I still can't watch Evangelion. How is it working for you?

**Comment by Maddyhf** [comment]
I don't know but it is not showing up now

**Comment by Igrissid** [comment]
Did you update to the pre version?

**Comment by Igrissid** [comment]
Okay, Thanks for informing me about this!

**Comment by Igrissid** [comment]
Remote Error
ERROR_CODE_IO_BAD_HTTP_STATUS (2004)
Source error
