### ISSUE TITLE
android tv version 

### ISSUE THREAD

**Issue by alegye** [LagradOst/CloudStream-3#142]
When is it going to see version for android tv cloudstream 3 and when more providers pages are added

**Comment by alegye** [comment]
https://tvshows88.com/
https://wvw.ssoap2day.to
https://ww1.solarmovie.cr/
https://www3.watchserieshd.ru/
https://danimados.com/
https://caricaturashd.net
https://flixtor.video/
https://movies2watch.tv
https://4kmovies.co/

**Comment by LagradOst** [comment]
cs3 now works on Android TV and it has a banner and custom layout in latest stable
