### ISSUE TITLE
ShieldTv interface won't fade while playing video.

### ISSUE THREAD

**Issue by wikd** [LagradOst/CloudStream-3#144]
Installed this on shield and when video is playing the osd of the buttons and progress bar will not go away. Also when searching it will not bring up keyboard.

**Comment by LagradOst** [comment]
How is this in the current preview build?

**Comment by optzeci** [comment]
The interface dissappears when you start a movie, but if you bring it again in order to use some button, it does not dissappear after. 

So the initial bug was somehow fixed, but not totally. Anyway it's a little bit better.

Unfortunately I didn't the latest pre-release build.

**Comment by wikd** [comment]
Yeah as stated the gui goes away nicely but it is extremely funky to get it to come back up.

**Comment by optzeci** [comment]
The Android TV navigation improved in the latest 2.2.3 PRE, but there is still not 100% functional.

If you need testers for Android TV, I can help you. I have 3 Android TV devices.

**Comment by wikd** [comment]
This issue is still around btw. The latest update let's you press ok and it pops ui up but then it never goes away again.

**Comment by LagradOst** [comment]
Not a bug, intended UX. On tv you press the back button to fade or lock it.

**Comment by wikd** [comment]
Back button just exits player for me. Everything works fine with the shield tv app though, guess I'll just use it. The app really is great especially considering it was never intended for tv's.

**Comment by LagradOst** [comment]
This behavior was changed in latest pre, update to hide with back button.

**Comment by wikd** [comment]
Ok updated to latest and it does indeed fix the issue. Works perfectly now. Sorry about that.
