### ISSUE TITLE
french dub providers

### ISSUE THREAD

**Issue by amorabda** [LagradOst/CloudStream-3#15]
Hi,
Congrats for this great app.
If you can add french dub movies providers, it will be great
for movies:
https://wiflix.site/
https://hdss.watch/
https://wvw.streamay.to/

for animes:
https://french-anime.com/

Thanks

**Comment by ArjixWasTaken** [comment]
As mentioned in #8 no non-english providers are planned to be added yet.
But I will leave this open just in case @LagradOst changes his mind.
