### ISSUE TITLE
French tv shows provider

### ISSUE THREAD

**Issue by amorabda** [LagradOst/CloudStream-3#150]
First thank for adding vf-film.org its very good french provider but only for movies, there is a similar website for series vf-serie.org can you add it please?
Http://vf-serie.org
Its very similar to vf-film but for tvshows.

**Comment by leprofdelombre** [comment]
https://vf-film.org/ become https://vf-film.me/
You can change please 🙇

**Comment by Sarlay** [comment]
I opened a pull request with:
- https://vf-serie.org
- https://vf-film.me

This will (probably) be in pre-release soon
Hope you enjoy !
