### ISSUE TITLE
Minor issues on Android TV (not urgent)

### ISSUE THREAD

**Issue by dhrubo66** [LagradOst/CloudStream-3#154]
Great work by the developer! The app works nicely on Android TV, however fixing some minor bugs when the developer has free time would be awesome.

1. The media control buttons at the center and seek bar doesn't go away. Pressing back on remote exits the player. Currently using mouse mode to click on blank space to resolve that.
2. While searching, the keyboard doesn't come up. It's only after you put a character in the search somehow (by another remote with character input or app), an invisible button beside menu becomes active, clicking which the keyboard finally pops out.

**Comment by LagradOst** [comment]
Should be fixed in pre
