### ISSUE TITLE
Change icon color an add themes. 

### ISSUE THREAD

**Issue by Samy20023** [LagradOst/CloudStream-3#17]
Hi,

I want to thank you for create such a wonderful app. Can you change app icon color and make it black and also add themes for the app in upcoming update? Thank you for your efforts.

**Comment by LagradOst** [comment]
Q: Can you change app icon color and make it black
A: No, it is the coloring scheme I use for my others apps, and I wont change it. There is a way to make the icon a custom color, but that is far in the future.
Q: add themes for the app in upcoming update
A: Planned, dont have an ETA, but some more important issues will be resolved before this
