### ISSUE TITLE
WCO Stream Play link error

### ISSUE THREAD

**Issue by SubaruSudo** [LagradOst/CloudStream-3#186]
Earlier today, I was attempting to watch some anime on WCO Stream, which I think is a very good source but, when I tried playing an episode it couldn't play due to some source error. I also took some screenshots. Can you please fix this.
Edit: Initially, I thought this was due to my wifi but after using a VPN I have concluded that is not the case and it might just be an internal problem. I've tried restarting the app several times and updating to the prerelease. 
![Screenshot_2021-10-26-17-49-22](https://user-images.githubusercontent.com/88172960/138967955-53babb24-6b50-45af-b2fd-6487ff9d8e10.jpg)
![Screenshot_2021-10-26-17-48-53](https://user-images.githubusercontent.com/88172960/138967957-b43b7c73-ea59-40d4-8812-d7620b548f85.jpg)
![Screenshot_2021-10-26-17-47-59](https://user-images.githubusercontent.com/88172960/138967959-3b434456-8b63-430d-b586-8c994f5af06d.jpg)

**Comment by LagradOst** [comment]
Should be fixed in pre
