### ISSUE TITLE
Add indian providers

### ISSUE THREAD

**Issue by Pranithjainbp84** [LagradOst/CloudStream-3#199]
Add some of indian providers please 
1 https://ww6.9movierulz.bar/
or
3 https://hdmovie5.art/
Any one but I prefer movierulz. There is no way I find indian movies / series other than vmovee.

**Comment by Pranithjainbp84** [comment]
Updated domain

**Comment by Pranithjainbp84** [comment]
🔥 New Movies Updated Daily 🔥


   Domain: ⚡️ https://ww2.7movierulz.ph/ ⚡️

🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟🌟

👉English:
https://ww2.7movierulz.ph/genre/english/

👉Hindi:
https://ww2.7movierulz.ph/genre/hindi/

👉Telugu:
https://ww2.7movierulz.ph/genre/telugu/

👉Tamil: 
https://ww2.7movierulz.ph/genre/tamil/

👉Malayalam:
https://ww2.7movierulz.ph/genre/malayalam/

👉Kannada:
https://ww2.7movierulz.ph/genre/kannada/

⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️

👉Hindi Dubbed:
https://ww2.7movierulz.ph/genre/hindi-dubbed/

👉Telugu Dubbed:
https://ww2.7movierulz.ph/genre/telugu-dubbed/

👉Tamil Dubbed:
https://ww2.7movierulz.ph/genre/tamil-dubbed/

🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶

👉Hindi Web Series:
https://ww2.7movierulz.ph/genre/hindi-web-series-download/

👉Telugu Web Series:
https://ww2.7movierulz.ph/genre/telugu-web-series/

👉Tamil Web Series:
https://ww2.7movierulz.ph/genre/tamil-web-series/

👉English Web Series:
https://ww2.7movierulz.ph/genre/download-tv-shows-english-web-series/

💫💫💫💫💫💫💫💫💫💫💫💫💫💫💫

👉TV Shows:
https://ww2.7movierulz.ph/tvshows/

👉Featured:
https://ww2.7movierulz.ph/genre/featured/

👉Collection:
https://ww2.7movierulz.ph/best-movies/

**Comment by ArjixWasTaken** [comment]
So many emoji 🤮

**Comment by Pranithjainbp84** [comment]
It's not mine it's from official telegram group

**Comment by Pranithjainbp84** [comment]
Updated both domain

**Comment by Pranithjainbp84** [comment]
Added new site

**Comment by Pranithjainbp84** [comment]
Sites Domin updated please add

**Comment by Pranithjainbp84** [comment]
Site Domin updated

**Comment by Pranithjainbp84** [comment]
Domain:  https://9movierulz.bar/ 

English:
https://9movierulz.bar/genre/english/

Hindi:
https://9movierulz.bar/genre/hindi/

Telugu:
https://9movierulz.bar/genre/telugu/

Tamil: 
https://9movierulz.bar/genre/tamil/

Malayalam:
https://9movierulz.bar/genre/malayalam/

Kannada:
https://9movierulz.bar/genre/kannada/

Hindi Dubbed:
https://9movierulz.bar/genre/hindi-dubbed/

Telugu Dubbed:
https://9movierulz.bar/genre/telugu-dubbed/

Tamil Dubbed:
https://9movierulz.bar/genre/tamil-dubbed/

Hindi Web Series:
https://9movierulz.bar/genre/hindi-web-series-download/

Telugu Web Series:
https://9movierulz.bar/genre/telugu-web-series/

Tamil Web Series:
https://9movierulz.bar/genre/tamil-web-series/

English Web Series:
https://9movierulz.bar/genre/download-tv-shows-english-web-series/

TV Shows:
https://9movierulz.bar/tvshows/

Featured:
https://9movierulz.bar/genre/featured/

Collection:
https://9movierulz.bar/best-movies/

_Sent from my AC2001 using [FastHub-RE](https://github.com/LightDestory/FastHub-RE/)_

**Comment by Light7654** [comment]
Bro do you Know any alternative website of these 

But with Korean dub movies(Hollywood)

**Comment by Pranithjainbp84** [comment]
I don't know bro

**Comment by Light7654** [comment]
Ok
