### ISSUE TITLE
[Enhancement] Separate movies/tv from Anime

### ISSUE THREAD

**Issue by Jacekun** [LagradOst/CloudStream-3#200]
Request: Add an option to select what type of media the user wants. And only show providers for that media type.

How it works:

1. Selector setting with options: '**All, Movie/TV only, Anime only**'. Then, filter out providers based on the selection.

2. Similar to what Tachiyomi does, an extension model that needs to be installed. And only installed extensions can be used. It can be only 2 so it can be easily maintainable -> **Movie/TV shows** and **Anime**.

I will try to implement this myself once I got time. For now, I will leave this as a request.

**Comment by LagradOst** [comment]
Search already has that function, you want that for homepage as well?

**Comment by Jacekun** [comment]
Yeah, that's exactly it

**Comment by cutterchop** [comment]
hey i already suggested a first time start up setup ;o
