### ISSUE TITLE
Error code io bad http status 2004

### ISSUE THREAD

**Issue by Theitfixer85** [LagradOst/CloudStream-3#202]
I get Error code io bad http status 2004 when trying to play anything using the internal player. Works fine when playing in vlc.

Using an nvidia shield and the pre release version of the app

**Comment by LagradOst** [comment]
Exoplayer being wack, TODO: https://stackoverflow.com/questions/69040127/error-code-io-bad-http-status-exoplayer-android

**Comment by LagradOst** [comment]
Might be fixed in pre now.

**Comment by Theitfixer85** [comment]
> Might be fixed in pre now.

Yes it's fixed now
