### ISSUE TITLE
Android tv navigation bugs

### ISSUE THREAD

**Issue by Theitfixer85** [LagradOst/CloudStream-3#209]
Just some minor bugs - on android tv (using the nvidia shield) on the main menu you can't use the remote to scroll down to anything under the play/info boxes to get to the recently updated anime section. Have to use a mouse toggle app to drag it there.

Also If you enter the recently updated anime section so it maximises that section pushing down on the remote makes it go two to the right and up goes two to the left

If you search for something it brings up the keyboard but you can't see what you are typing. You can only see what you have typed after pressing finish or pressing the back button to hide the keyboard

**Comment by Pentaphon** [comment]
Having the same issue on FireTV which is basically the same thing. I can't select any videos but I can browse the main menus. We need full remote support.

**Comment by Theitfixer85** [comment]
The new android tv bug fix release hasn't fixed any of the bugs

It has placed a new menu option on the left side for home search downloads and settings

But when you move onto the carousel to select a show you then can't back to these menu options in the left.

You still can't also move below the play/info buttons to get to recently updated anime.

If you use a mouse toggle to get to the recently updated anime section and expand it then as before pressing down moves two to the right and up two to the left.


The only thing in my bug list that is fixed is the search where you can now see what you are typing.
