### ISSUE TITLE
English Provider

### ISSUE THREAD

**Issue by 1onLSD** [LagradOst/CloudStream-3#214]
by far this is the best provider I have found 

https://dopebox.to/  
https://9anime.vc/

The first on for movies and tvshows and the second one is for anime and they both support multiple subtitles and quality settings

**Comment by cutterchop** [comment]
it looks like dopebox is one of the clones, the website Sflix already added to the app is almost the exact same

**Comment by 1onLSD** [comment]
Ok I think they're about the same yes, but 9anime is still worth to add

**Comment by VijaykumarBK** [comment]
> by far this is the best provider I have found 
> 
> https://dopebox.to/  
> https://9anime.id/
> 
> The first on for movies and tvshows and the second one is for anime and they both support multiple subtitles and quality settings

**Comment by VijaykumarBK** [comment]
The vc link for 9 anime is fake..

**Comment by 1onLSD** [comment]
how did you manage to get this up? it looks real to me as I can stream any anime or did you mean that it's a duplicate of another website .?

**Comment by VijaykumarBK** [comment]
The official website for 9anime is 9anime.me
That's the place u get its official streaming website link

**Comment by VijaykumarBK** [comment]
Ya meant it is duplicate 
The ppl who do the hardworking dont get any credit ....coz of these fake copies websites

**Comment by 1onLSD** [comment]
well I think you're right I'll change the website in the issue thanks

**Comment by 1onLSD** [comment]
It's already been requested (9anime.to) So I think I'll close this issue thanks for your help dude
