### ISSUE TITLE
No Dub Links for All Anime

### ISSUE THREAD

**Issue by SubaruSudo** [LagradOst/CloudStream-3#215]
It would be nice to have dub links for this source.

**Comment by LagradOst** [comment]
What source? Cs3 has dubbed anime

**Comment by SubaruSudo** [comment]
@LagradOst All Anime  was added by @ArjixWasTaken

**Comment by SubaruSudo** [comment]
@LagradOst. You can check the search filter for the source.

**Comment by ArjixWasTaken** [comment]
Fuck that, I originally did support dub anime for this source, but no.
There is no way to switch between sub and dub so I disabled dub.

You can see that the code is still there, but commented out.

Because as I said, if both dub and sub are present, cs-3 only allows you to watch dub.

**Comment by SubaruSudo** [comment]
@ArjixWasTaken. Sorry about that.

**Comment by ArjixWasTaken** [comment]
> @ArjixWasTaken. Sorry about that.

You did nothing to be sorry, I just stated the reason why no dub is enabled and my frustration.

**Comment by LagradOst** [comment]
TODO: Dub/Sub switch

**Comment by ArjixWasTaken** [comment]
> @LagradOst. You can check the search filter for the source.

The search has nothing to do with that btw.

**Comment by LagradOst** [comment]
Should be semi fixed in https://github.com/LagradOst/CloudStream-3/commit/2f9c76d9b5fc09b9bf12512ace7028bb7815006a

**Comment by SubaruSudo** [comment]
> Should be semi fixed in [2f9c76d](https://github.com/LagradOst/CloudStream-3/commit/2f9c76d9b5fc09b9bf12512ace7028bb7815006a)

@LagradOst  Thanks for adding the dub option.
