### ISSUE TITLE
User data too large?

### ISSUE THREAD

**Issue by yephny** [LagradOst/CloudStream-3#220]
I'm not sure if this is an indication of a possible bug but it seemed strange to me to see the user data at 100MB while I have only 3 shows on my homepage marked "Watching" or "Completed". Is this expected?

On another note, I just checked data usages and the app has downloaded about 40GB of data and uploaded 500MB so far, the latter of which seems extreme.

**Comment by LagradOst** [comment]
looks about right. I think it is image cache that takes space. For data, I can assure you that cs3 does not make any unsolicited requests. You can look at the src code or via http canary. Webview might do extra requests tho (Zoro and sflix uses it)

**Comment by yephny** [comment]
Thank you for clearing that up. Does it make sense for cached images to be listed under user data instead of app cache?

**Comment by LagradOst** [comment]
Idk tbh

**Comment by yephny** [comment]
This is getting out of hand, my user data is now over 500 MB. `/data/user/0/com.lagradost.cloudstream3/files/exoplayer` constitutes most of it. There are directories with names from 0 to 9 inside and they're filled with .exo files about 5 MB each.

**Comment by LagradOst** [comment]
yes cache

**Comment by LagradOst** [comment]
https://github.com/LagradOst/CloudStream-3/blob/a4bea62392cad1770ea5477281fe53ac64cfce3a/app/src/main/java/com/lagradost/cloudstream3/ui/player/PlayerFragment.kt#L280

**Comment by yephny** [comment]
Any reason why cache is in user data and not app cache? We could just clear cache if it got too big, like in browsers.

It seems counterintuitive to let this build up.

**Comment by LagradOst** [comment]
can be changed
