### ISSUE TITLE
[meta request] remove tagalog translation

### ISSUE THREAD

**Issue by CVIUS** [LagradOst/CloudStream-3#222]
whoever translated the strings to tagalog is using google translate. :cringe:
I am a Filipino and I can tell that.

**Comment by LagradOst** [comment]
😔 ye that and norsk is google translated by @krrishkap

**Comment by LagradOst** [comment]
You can pr the correct translation tho 👉😎👉

**Comment by krrishkap** [comment]
> whoever translated the strings to tagalog is using google translate. :cringe: I am a Filipino and I can tell that.

what part of it is cringe? most of the translations were done by a Filipino native @whinee  i added missing strings  coz he didnt had his laptop arround , some of them are supposed to be cringe tho coz i couldn't find some specific word with that specific context .

**Comment by CVIUS** [comment]
> what part of it is cringe? 
you wouldn't know unless you understand Tagalog

**Comment by whinee** [comment]
Holy fucking shit, I just saw this issue. In any case, I could not agree less; it is indeed cringe.

In my defense though, I've only done it to only gain access to the contributor channel over at CloudStream3's Joint Discord App Support Guild, aptly named "banana-farm".

**Comment by whinee** [comment]
LagradOST, better known as Lag, has expressed displeasure regarding this revelation. And as such, I would like to take this opportunity to correct my wrong-doings and make everything right.

However, as is the theme of the Universe that we're in, as to make an absolute mockery of our feeble minds, there is almost no language that need not any context to translate it to another one. As an example, take "Home". It is indeed an intuitive use of the word. Home is where you stay in, the place you always come back to. However, that would no work in Tagalog, as of the following reasons:
- Houses in here are not considered home, generally, as you cannot feel that you are welcome in it; and
- Filipino homes are naught without privacy, or rather, unfortunately, lack thereof.

Regarding Krrish' comment:
> i added missing strings coz he didnt had his laptop arround
1. she
2. really? how? when?

> some of them are supposed to be cringe tho

You need not concern yourself. Tagalog is naught but a cringe language. Thee hath naught erred.
