### ISSUE TITLE
Lock isn't working properly

### ISSUE THREAD

**Issue by yephny** [LagradOst/CloudStream-3#225]
I expect that no button will be clickable when I enable lock, but I can still tap where "Source" appears to open the source picker.

1. Play a video.
2. Click the "Lock" button.
3. Tap the screen once to show the video progress bar.
4. Nothing will be visible under the bar but still tap where the "source" button normally is.
5. The video will pause and the source picker will appear.

- Eigengrau mode is enabled, the resize button is disabled.
- Android 10, Cloudstream 3 v.2.1.2

**Comment by LagradOst** [comment]
Bruh

**Comment by LagradOst** [comment]
Fixed in pre
