### ISSUE TITLE
Disable home page auto refresh into Manuel 

### ISSUE THREAD

**Issue by cutterchop** [LagradOst/CloudStream-3#227]
Problem : when you switch between tabs and go back home it refreshes some sections of the home page, Sometimes this is annoying as I glance one show before switching and I miss it, secondly is that it's tasking and taking more response time to switch ( refreshing on every switch therefore taking more time ) , by eliminating this feature and adding a refresh icon between the setting icon on the top right it can be beneficial and faster
![IMG_20211103_131410](https://user-images.githubusercontent.com/31880937/140538854-7bf3ba15-5181-4441-9d71-a70bdf0dc814.jpg)
around here maybe

**Comment by LagradOst** [comment]
Fixed in pre
