### ISSUE TITLE
No issue Just showing some support

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#230]
I do not have an issue I just wanted to show some support and say thank you for creating this app it works nice even though my phone is basically garbage. The resize feature, skipping the op and the video player are exquisite and one I get a new device or maybe a tablet I can only imagine the fun with this app that is going to happen so again keep up the splendid work I just thought to let you know how grateful I am have a nice day.

**Comment by LagradOst** [comment]
🤗

**Comment by AbdullahM0hamed** [comment]
![hug](https://cdn.discordapp.com/emojis/849668785165828106.png)

**Comment by Blatzar** [comment]
![hug](https://cdn.discordapp.com/emojis/849668785165828106.png)
