### ISSUE TITLE
Sflix down

### ISSUE THREAD

**Issue by Buddie911** [LagradOst/CloudStream-3#237]
I'm having problems with sflix, it seems like the site itself is down tho. Can we please maybe replace it with https://sflix.pro/home. It works a lot better and has multiple subtitles and multiple sources.

**Comment by LagradOst** [comment]
Sflix is up again, I dont do providers anymore, but it is kinda a duplicate so it wont be added (I think)

**Comment by vedant-shah** [comment]
sflix.to isn't yet working for me, is it working for you ?

**Comment by LagradOst** [comment]
Try dns
