### ISSUE TITLE
Add option to select streaming server from the list of options given in the website

### ISSUE THREAD

**Issue by iamaravindim** [LagradOst/CloudStream-3#244]
Streaming doesn't work on most websites since the default streaming server in the websites used in Cloudstream-3 does not work. I checked the websites manually. I had to change the options of the streaming server to alternative server on the websites to make it work.

**Comment by LagradOst** [comment]
what?

**Comment by iamaravindim** [comment]
I meant this option
![server](https://user-images.githubusercontent.com/71166946/141684821-ce96f2b9-8b15-415d-a249-f065ee143bbb.png)

**Comment by ArjixWasTaken** [comment]
Yeah uhh....that's provider specific, we already support those options.
The only reason you don't see those servers is because a specific provider does not scrape them.
