### ISSUE TITLE
Dub problem

### ISSUE THREAD

**Issue by Recoil1024** [LagradOst/CloudStream-3#246]
When trying to watch anime through zoro everytime only sub servers come up

**Comment by cutterchop** [comment]
> When trying to watch anime through zoro everytime only sub servers come up

Check if this is on, also inside the video go to source maybe it's a source setting 

![96d35cb5b02130b39e948121101d558d](https://user-images.githubusercontent.com/31880937/141800822-534a77db-0332-4ad4-a6ae-ced9317fd10f.jpg)

Bruh wrong photo

![IMG_20211115_154051](https://user-images.githubusercontent.com/31880937/141800876-7462b751-8e1f-4240-8da2-1ffb92986013.jpg)

Oh it's a source setting

![IMG_20211115_154524](https://user-images.githubusercontent.com/31880937/141801466-1bf38da4-a404-4417-a84e-f5499d4b9105.jpg)

**Comment by ArjixWasTaken** [comment]
zoro does not have links specific for sub or dub
it has both versions in the same anime in the same episode

so we can't really split them apart, thats why, just like on the website we have the sub/dub as sources

**Comment by Recoil1024** [comment]
Thank you for your response and that joke is old as hell
