### ISSUE TITLE
Love this app hope it grows further

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#248]
It's weird how much this app reminds me of Netflix but that's a very great thing the layout at least for me is perfect all that's left is Mal or anilist and IMDb sync thank you for making this app hope it continues to grow.

**Comment by LagradOst** [comment]
MAL and Anilist sync is already worked on. IMDb stuff can ve harder because they dont have Oauth2.

**Comment by JasonSmith20** [comment]
Understood do what you can

**Comment by JasonSmith20** [comment]
What I said about it being similar to netflix I did a direct comparison on my phone I was right but in terms of lag Cloudstream won perfectly layout similar which I love however Netflix won in loadin but thats the only area it won I can say confidently this app is amazing I can only Imagine when it is truly perfected nice work keep it going.

**Comment by Schmongo** [comment]
> MAL and Anilist sync is already worked on. IMDb stuff can ve harder because they dont have Oauth2.

Would tracking with trakt.tv for episodes/movies be possible or does it have the same problem?

**Comment by LagradOst** [comment]
iirc trakt has oauth2 but that is very low priority
