### ISSUE TITLE
Trailers.to 's not visible 

### ISSUE THREAD

**Issue by krrishkap** [LagradOst/CloudStream-3#249]
What happened to trailers ? Its gone after those sync api changes

**Comment by LagradOst** [comment]
Site changed, and no tbdm yet

**Comment by krrishkap** [comment]
> Site changed, and no tbdm yet

Aaaaah shit

**Comment by cutterchop** [comment]
> > Site changed, and no tbdm yet
> 
> Aaaaah shit

Actually he just dropped it off so it's not coming back most probably

**Comment by Schmongo** [comment]
Tbdm?

It's still working fine for me on version 2.1.2 though.

Hope it comes back somehow.. Would be nice to have some alternatives!

**Comment by krrishkap** [comment]
@LagradOst its still working on that "mem leak fix" commit but its not showing up just after the "sync api and bug fix" commit  , tried that version just now everything's perfectly fine . am i missing up on something ?
