### ISSUE TITLE
add custom colour option

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#250]
It would be great if we could we could make our own colors a minor suggestion but doable I hope.

**Comment by LagradOst** [comment]
No, current is good and we will need a framework for 100% custom colors. A lot of useless work.

**Comment by JasonSmith20** [comment]
Then could you add a previous episode button to the player

**Comment by LagradOst** [comment]
I am sorry but I see no reason to add that.

**Comment by Schmongo** [comment]
Could you add the option for a simple 'white' as a primary color?
