### ISSUE TITLE
Add Netflix theme

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#254]
It would be good if you could add a NETFLIX colors theme option which would be great just please consider it I ask this because I like Netflix UI its clean like this one but the library contents are limited and this app is the next best thing please just add a NETFLIX theme for the future like when loading a video the red is too pale it should be more red and the white play button should be a brighter white this is all I am asking I cannot afford netflix at the moment this is my only option.

**Comment by ArjixWasTaken** [comment]
Just for your information, nobody likes issues that beg for a feature/enhancement.
Your issue should simply state what you want to be done, don't get your emotions into this.

**Comment by LagradOst** [comment]
Fire+Almoled is netflix more or less

**Comment by JasonSmith20** [comment]
Oh it sounded emotional honestly that was not my intention I just believe this app has the potential to advance in greatness oh and also it sounded like I was begging my bad I will get it right next time and just ask without sounding like a beggar but seriously netflix library does suck.

> Just for your information, nobody likes issues that beg for a feature/enhancement. Your issue should simply state what you want to be done, don't get your emotions into this.
