### ISSUE TITLE
9anime development progress 

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#255]
I wanted to know how the addition of 9anime.to is going because I know the library is huge so its not easy to add I know wcostream has 9anime videos but sometimes they dont play I need to know if it will be added or discarded thats all

**Comment by LagradOst** [comment]
Ask on the discord and dont create issues for questions on stuff that are prone to changes. dev in open source has no deadlines or progress in the same way as regular stuff. some guy just has some free time one day and makes it in 4h and there is no telling when that is, but I can say that I am not adding any providers atm.

**Comment by JasonSmith20** [comment]
Understood
