### ISSUE TITLE
Can you please put automatic quality 

### ISSUE THREAD

**Issue by SkyCreedPH** [LagradOst/CloudStream-3#257]
can you guys update

**Comment by LagradOst** [comment]
this is not Youtube??????

**Comment by ArjixWasTaken** [comment]
No, this is clearly youtube, are you on drugs or smth? @LagradOst

**Comment by SkyCreedPH** [comment]
what did i do to you why you calling me drugs i just request

**Comment by ArjixWasTaken** [comment]
> what did i do to you why you calling me drugs i just request

You must be on drugs to confuse a message that is clearly directed at @LagradOst as a message that is directed to you....

**Comment by SkyCreedPH** [comment]
man im joking chill bro

**Comment by SkyCreedPH** [comment]
Bro are you gen z

**Comment by SkyCreedPH** [comment]
bro im joking it's ok 🤣 even if you don't put it on

**Comment by SkyCreedPH** [comment]
bro suck my dick😂
