### ISSUE TITLE
Cast not working

### ISSUE THREAD

**Issue by Moon14590** [LagradOst/CloudStream-3#262]
Screen cast isn't working for me. 
Below I've attached a screen recording with screen cast on. Though my TV gets connected, the movie never plays. Looks like a UI issue, or something else?

• Cloustream 3 v2.2.3
• OneUI 3.1, Android 11
• Not rooted
• arm64, Snapdragon

https://user-images.githubusercontent.com/58824912/142832116-d8410e47-8926-4204-abb6-12bf3826e8a4.mp4

**Comment by LagradOst** [comment]
No, this is an issue with some links. Hold and play another link or switch source. I cant fix this as I get Result.Success even from an invalid link for some reason.

**Comment by LagradOst** [comment]
To make this clear, everything is good on my end and the tv even gives me a correct response, but the tv just stops.

**Comment by Moon14590** [comment]
> No, this is an issue with some links. Hold and play another link or switch source. I cant fix this as I get Result.Success even from an invalid link for some reason. 

    Okk...weird. That link was working for me without cast. So when it wouldnt work with cast, I thought it had something to with the app. Thanks for replying.

**Comment by Moon14590** [comment]
Installed the apk on my Android tv😜
