### ISSUE TITLE
Can I help add translations?

### ISSUE THREAD

**Issue by Darthagnon** [LagradOst/CloudStream-3#263]
I'm multilingual, and would like to help add some translations. I speak a few Latin languages besides English, and have international contacts. Worst-case scenario, resorting to machine translation, I can spot when the right words are given or not.

**Comment by ArjixWasTaken** [comment]
Just look at how the others added translations, and add your own.

**Comment by LagradOst** [comment]
If you want to add a translation add the folder with the language called smth like values-[lang code] and add strings.xml and transelate. Then add it to the readme and settingsfragment.kt and pr 👍

**Comment by Darthagnon** [comment]
Thank you for the instructions, @LagradOst. I followed them and have added 2 languages and done a pull request. I focused on these two so that my Brazilian family and Romanian friends can use it more easily.

**Comment by ArjixWasTaken** [comment]
> Thank you for the instructions, @LagradOst. I followed them and have added 2 languages and done a pull request. I focused on these two so that my Brazilian family and Romanian friends can use it more easily.

Very nice of you, truly, translating an app is a boring process, you must really like this app. ❤️ ❤️ ❤️

**Comment by Darthagnon** [comment]
I've been testing, and noticed a bunch of missing (untranslated) strings - I want to add them. Which XML should I use as a base? I used the Spanish one, but that is evidently outdated. I don't remember seeing the strings in the English xml, either...
Untranslated strings:
- Preferred Media
- Provider Languages
- DNS Over HTTPS
- Download Path
- App Layout
- Primary Colour
- App Theme
- Disclaimer (and disclaimer text)

**Comment by Darthagnon** [comment]
Question: Is Eigengravy Mode a pseudo-translation from German Eigengraumode? or is it an in-joke or technical term? `Video Playback Speed` would be more understandable. Requesting permission to rename.

**Comment by ArjixWasTaken** [comment]
> Question: Is Eigengravy Mode a pseudo-translation from German Eigengraumode? or is it an in-joke or technical term? `Video Playback Speed` would be more understandable. Requesting permission to rename.

Eigy is a guy from the discord
It was added as a joke since he requested for it

It's preferable to not translate it, but you can do that.

**Comment by Darthagnon** [comment]
I've sent the app prerelease to my Romanian friends; let's see what they think of the translation lol
