### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#265]
Can You add another fire primary color with this hex code #E50914 Just more accurate color red hope you can do its minor but but seems simple enough.

**Comment by ArjixWasTaken** [comment]
If it's "simple enough" (and it is) then just do the pull request.

**Comment by JasonSmith20** [comment]
I meant simple for you I DO NOT KNOW KNOW WHAT TO DO I was just making a request still a kid bro

**Comment by LagradOst** [comment]
![this](https://user-images.githubusercontent.com/11805592/143071391-17b3407f-bea5-445c-a311-9c21dd01e53e.PNG)
Current vs Change. I see no difference

**Comment by ArjixWasTaken** [comment]
> Current vs Change. I see no difference

I can see a slight difference, the suggested change is brighter than the current color.
But it's not at a noticeable level.

**Comment by LagradOst** [comment]
So should it be changed y/n? @ArjixWasTaken

**Comment by ArjixWasTaken** [comment]
n

**Comment by ArjixWasTaken** [comment]
> I meant simple for you I DO NOT KNOW KNOW WHAT TO DO I was just making a request

You did not even put effort into making a proper title for this issue, and you expect us to put the effort to do what you want?

**Comment by LagradOst** [comment]
> > I meant simple for you I DO NOT KNOW KNOW WHAT TO DO I was just making a request
> 
> You did not even put effort into making a proper title for this issue, and you expect us to put the effort to do what you want?

plz no tox

**Comment by ArjixWasTaken** [comment]
> plz no tox

![](https://images-ext-1.discordapp.net/external/FYM5V2QIDes3N0RIBiWsGMLdS-nDPULZbogrxnlxGx0/https/cdn.discordapp.com/emojis/810227943263305768.png)
