### ISSUE TITLE
I did not mean change the color I just asked for an addition 

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#266]
In my previous issue I asked for an alternate fire theme more accurate since I don't know how to do it myself as I am still a kid and I  do not know how to create coding in apps so I asked because that shade of red brightens the app more than the current one which for some reason every time I exit the app and re-enter the loading Icon changes to a pale looking shade of red so thought it maybe was a bug so I am requesting an alternative shade of red please and thanks just a color that is all I am asking oh and I am not begging for this just asking just to be clear.

**Comment by LagradOst** [comment]
That is not the primary color, that is coloraccent and is supposed to be different.

**Comment by JasonSmith20** [comment]
I know that I just asked for another alternative version of the fire theme because the current for me has issues

**Comment by LagradOst** [comment]
@Blatzar @ArjixWasTaken same loadingcircle color red as nav bar red? y/n?

**Comment by Blatzar** [comment]
No opinions good either way

**Comment by LagradOst** [comment]
Also no essay next time, try to keep text to a minimum

**Comment by ArjixWasTaken** [comment]
> since I don't know how to do it myself as I am still a kid and I do not know how to create coding in apps

Age doesn't stop anyone from knowing how to code.
There are even 13 year old game devs.

**Comment by LagradOst** [comment]
Fixed.
