### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by joybavisi** [LagradOst/CloudStream-3#267]
The **search page in CS3** looks a bit ugly and confusing. I mean, just look at the search page of **CS2**, it looks quite **clean and minimal** as compared to that of CS3. You can **group all the search results** under **one head (movie/tv show/anime)** and not as per sources. You can give us the option to **select our favourite source** when we enter the **player** for watching.

![CS2 Search Page](https://user-images.githubusercontent.com/36401796/143400853-0fef7b17-47ed-4fbd-92fc-52d29df8ab5b.jpeg)

![Screenshot_20211125_132543](https://user-images.githubusercontent.com/36401796/143401648-3e007bab-45c0-46e6-9697-3c0b5942fcee.jpg)

**Comment by LagradOst** [comment]
No, cs2 and cs3 works on different principles. There are architecture differences that make some UX stuff hard or impossible. Cs2 search was the best I could manage with that framework and api, while cs3 is how I wanted cs2 to be. What you are suggesting is not possible (atm) nor what I want for cs3.

**Comment by joybavisi** [comment]
But, atleast you can make the search page somewhat clean. Because sometimes, I try to open and find that the links are dead in some sources. If we could change the source directly from the player, the user experience would be great.

**Comment by LagradOst** [comment]
All sources are not simply linked, and I already added a search all button in the resultspage.
