### ISSUE TITLE
Problem parsing the package

### ISSUE THREAD

**Issue by Kraze21** [LagradOst/CloudStream-3#268]
Whenever I try to update directly from app (pre-release version) the it shows "There is a problem parsing the package", I always have to use my browser and go here (GitHub) to manually download the update (which works fine)

**Comment by LagradOst** [comment]
Android version? (((Also this issue can be solved by downloading it via the app, but installing in in the file explorer of your phone)))

**Comment by JasonSmith20** [comment]
It depends on your device itself not the app in particular sometimes for instance it is like this on your phone but I currently have never had this and my phone is kind of old so it maybe your device.
