### ISSUE TITLE
Pls can u change gogoanime's website.


### ISSUE THREAD

**Issue by ITADORI-15** [LagradOst/CloudStream-3#271]
**Pls do change it from gogoanime.vc to gogoanime.cm**

**Comment by LagradOst** [comment]
Why?

**Comment by VijaykumarBK** [comment]
Gogoanime.vc doesnt work anymore and their official working website is gogoanime.cm
Whatever is fine for u.....
Also in the app if u switch website to gogoanime the info doesnt load up

**Comment by ITADORI-15** [comment]
Bro plz reply

**Comment by lasersPew** [comment]
This happened rn since the app throws up link not found when playing some anime.

**Comment by ITADORI-15** [comment]
Atleast 1 to agree with me

**Comment by ITADORI-15** [comment]
Even kawaiifu has some prob

**Comment by lasersPew** [comment]
Well, I'll retract my statement since #331 solves my problem and gogoanime.cm changes their website frequently and the link is hard coded to the source code which may hinder to the development of the app itself.

**Comment by lasersPew** [comment]
> Well, I'll retract my statement since #331 solves my problem and gogoanime.cm changes their website frequently and the link is hard coded to the source code which may hinder to the development of the app itself.

It's #330 btw. I did add wrong issue.
