### ISSUE TITLE
Can't connect on "Vf-film.me"

### ISSUE THREAD

**Issue by thogrinn** [LagradOst/CloudStream-3#272]
The app return "couldn't connect to server" since 2 days. App is up to date (last), and the site works. It's french provider. Same bug with beta version. Try different dns, VPN on or off, nothin.

**Comment by LagradOst** [comment]
Provider responds with UnknownHostException you also experience this @Sarlay

**Comment by amorabda** [comment]
i think its better to switch to another provider in french langage with support of movies and tvshows at same time, to have a home screen for french speaking poeple.
https://01streaming.tv/  movies + tvshows
https://wiflix.tel/ movies+ tvshows
https://french-anime.com/  animes
