### ISSUE TITLE
Using remote to control not working(ANDROID TV)

### ISSUE THREAD

**Issue by AyeGH** [LagradOst/CloudStream-3#273]
i can't control it but i can go to the nav bar and scroll up and down but overall i cant choose nor pick any movies what i want.

**Comment by LagradOst** [comment]
What?

**Comment by ArjixWasTaken** [comment]
~~Ah yes, broken english and a swedish dev with dyslexia trying to understand the broken english.~~
@AyeGH Can you please speak in proper english please?
