### ISSUE TITLE
Countdown sequence when auto next 

### ISSUE THREAD

**Issue by Jasonsmith236** [LagradOst/CloudStream-3#277]
Would it be possible to add a countdown sequence to the player when auto next episode it's trivial I guess but it just brightens the apps potential think it through then reply.

**Comment by LagradOst** [comment]
No, as 99% of episodes has an ending of sorts I feel like it would be a waste to add smth that would never be seen. I also find it sort of annoying when apps have a giant popup for next episode second counter.

**Comment by JasonSmith20** [comment]
Now that I think about it I guess it is annoying nonetheless thank you for replying.
