### ISSUE TITLE
Downloading doesn't work!

### ISSUE THREAD

**Issue by ImranMZ** [LagradOst/CloudStream-3#278]
Idk if it's only for me but when i download a movie or even an episode from any provider....the size of that movie just randomly decreases and increases without an end to it....i tried to download a movie for a whole day but it just never finish downloading and downlaod just disappears.
-Please add an option to download videos with External download manager such as -ADM-

**Comment by LagradOst** [comment]
Wont add external download support. What you where downloading was an m3u8 file

**Comment by ImranMZ** [comment]
> Wont add external download support. What you where downloading was an m3u8 file

Oh..okay i understand 👍
