### ISSUE TITLE
Nvidia shield pro 2019 navigation issues

### ISSUE THREAD

**Issue by Theitfixer85** [LagradOst/CloudStream-3#280]
Reference from
https://github.com/LagradOst/CloudStream-3/issues/209

Despite the last latest pre-release stating android tv bugs fixed they still remain

It has placed a new menu option on the left side for home search downloads and settings

But when you move onto the carousel to select a show you then can't back to these menu options in the left.

You still can't also move below the play/info buttons to get to recently updated anime.

If you use a mouse toggle to get to the recently updated anime section and expand it then as before pressing down moves two to the right and up two to the left.

The only thing in my bug list that is fixed is the search where you can now see what you are typing.

**Comment by LagradOst** [comment]
Are you using android tv or smth else?

**Comment by Theitfixer85** [comment]
Nvidia shield - android tv based on android 9 (sdk 28)

**Comment by LagradOst** [comment]
Works perfectly on android TV emulator and 99% on fireTV. (check https://youtu.be/ChcVwHgNmYI)

The app is not designed for Nvidia shield pro and any issue with it wont be fixed by me.

**Comment by Theitfixer85** [comment]
Firetv is a modified version of android tv and not a pure version

You will probably have exactly the same issues on Google chromecast with android tv and a mi tv box as all these use a pure version of android tv

**Comment by LagradOst** [comment]
Chromecast is not any fork of android tv????? Also the app works on android tv.

**Comment by Theitfixer85** [comment]
> Chromecast is not any fork of android tv????? Also the app works on android tv.

Chromecast with Google TV is a device with android tv!


https://www.currys.co.uk/gbuk/tv-and-home-entertainment/digital-and-smart-tv/set-top-boxes/chromecast-with-google-tv-snow-10216159-pdt.html?istCompanyId=bec25c7e-cbcd-460d-81d5-a25372d2e3d7&istFeedId=4d7eb93e-055f-499d-8ee5-1cdcc50d67d1&istItemId=imlmlttpp&istBid=tztx&srcid=198&cmpid=ppc~gg~0042+(Shopping+Ads)+Vision+Content+-+Generic+Vision+Content+2021~0042+(PLA)+VISION+CONTENT+ad+group~Exact&mctag=gg_goog_7904&kwid=GOOGLE&device=m&ds_kids=92700067130115796&tgtid=0042+(Shopping+Ads)+Vision+Content+-+Generic+Vision+Content+2021&gclid=EAIaIQobChMIp_j1wpW79AIVFIBQBh25rA4qEAQYAiABEgL6y_D_BwE&gclsrc=aw.ds

**Comment by LagradOst** [comment]
Yes, but chromecast works on diffrent principles. You dont navigate on the tv with a chromecast. I have a chromecast myself and tldr it works by sending over a link to play, like vlc.

**Comment by LagradOst** [comment]
Yes, but chromecast works on diffrent principles. You dont navigate on the tv with a chromecast. I have a chromecast myself and tldr it works by sending over a link to play, like vlc.

**Comment by Theitfixer85** [comment]
> Yes, but chromecast works on diffrent principles. You dont navigate on the tv with a chromecast. I have a chromecast myself and tldr it works by sending over a link to play, like vlc.

Sounds like you just have a chromecast and not a chromecast with Google TV (they are different)

**Comment by LagradOst** [comment]
PR stuff yourself if you want this fixed.
