### ISSUE TITLE
Please add Trailers.to provider

### ISSUE THREAD

**Issue by Thorodinson1** [LagradOst/CloudStream-3#281]
Please readd Trailers.to provider in the beta version, it was removed from previous build.
https://trailers.to

**Comment by Jasonsmith236** [comment]
Trailers.to is using accounts now so maybe it can't be done.

**Comment by AsherJa** [comment]
This too, some servers buffer too much this one doesn't so please add it back.

**Comment by ArjixWasTaken** [comment]
Why do you think it was removed?
Just think, would we remove it w/o a reason?

No it won't be added back.
