### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by Gottarocket** [LagradOst/CloudStream-3#284]
Option to change source without playing video

**Comment by LagradOst** [comment]
What?

**Comment by ArjixWasTaken** [comment]
I too am confused.

**Comment by Gottarocket** [comment]
https://0bin.net/paste/ve8OshbQ#60EoEPq1garemBindu3Wr19plRWSIYQ+w2jSiAnRa2C
Get this option outside video  player

**Comment by LagradOst** [comment]
Why?

**Comment by Gottarocket** [comment]
Sometimes it will show link not found so if we can change sources and check it might show  up

**Comment by ArjixWasTaken** [comment]
You just made it even more confusing btw

**Comment by LagradOst** [comment]
> Sometimes it will show link not found so if we can change sources and check it might show up

Link not found means that NO link is found. What you are describing is switching links, and you cant do that if no links are found.

**Comment by ArjixWasTaken** [comment]
> pebcac

![](https://images-ext-1.discordapp.net/external/OWul5UeTJc5k46HmwfID1migB63xq2eqfsKXktuoA54/https/cdn.discordapp.com/emojis/847138667646287922.png)
