### ISSUE TITLE
Cloud Stream New App Icon suggestion. 

### ISSUE THREAD

**Issue by objestik** [LagradOst/CloudStream-3#288]
My personal opinion is that the current app icon is not modern or fitting for the user interface. 
I would like to suggest that it be changed to the one below. 
![image](https://user-images.githubusercontent.com/28157614/144042147-43e17e67-d3e2-4edc-9d19-1e2632960032.png)
![image](https://user-images.githubusercontent.com/28157614/144042171-236462dd-21c2-4ab5-921c-9bc559170e20.png)

**Comment by LagradOst** [comment]
Did you make these, and if yes then send me the svg or ai file so I can do a poll. 👍

**Comment by JasonSmith20** [comment]
These are great stuff has a premium vibe to it

**Comment by Blatzar** [comment]
Damn those look great

**Comment by objestik** [comment]
> Did you make these, and if yes then send me the svg or ai file so I can do a poll. 👍
I stumbled across the design and immediately thought of this app. 
I think it fits the name so well.

I asked the designer if he would contribute, and you guys give him credit for the design on the GitHub page.

Even if it means buying the design from him. I think it would be worth every penny!.

**Comment by Sarlay** [comment]
It honestly looks awesome !

If it's paid you could ask people for donations, I am sure some people would find this project

**Comment by yant0** [comment]
this is hot

**Comment by objestik** [comment]
So, I reached out to the designer behind this project and asked if he would like to contribute, but he wants to get paid for it 
His price for the license and the free band guide was 250 US dollars. @LagradOst 

You can contact him by email if you wish to buy the design yourself as the maintainer of the project. I have not linked him to this GitHub page or anything. 

One thing to clarify. I don't know the guy.

Here's the link for the design. 
https://dribbble.com/shots/16120488-Cloud-Stream-Logo

**Comment by LagradOst** [comment]
250 is too much for a logo, so no.
