### ISSUE TITLE
.

### ISSUE THREAD

**Issue by niraularohan** [LagradOst/CloudStream-3#290]

**Comment by niraularohan** [comment]
It's like 5x faster than sflix.to

**Comment by Bungeexgum** [comment]
> I highly suggest you to add https://bflix.to on the app as this website's videos are hosted on google-cloud servers and to be honest, streaming from bflix.to is very very fast than its alternatives.
> 
> I really hope that you would implement this thing.

 Visited the site it has ads and runs slow. Dopebox.to is much better and we have that in the app try visit the site so you'll see.

**Comment by niraularohan** [comment]
Yes, Dopebox.to is good but I find it not as great as bflix. As sflix is already in cloudstream3, dopebox doesn't make any difference as it's the clone of sflix.

Sflix/Dopebox uses Upcloud servers while Bflix uses Mycloud and I find it much much faster in my case.
Yes, bflix has ads but I haven't seen them as I use ublock origin as adblock.

Bflix may also be faster and great for me because of my location and internet bandwidth. I am from Nepal and the Internet speed of broadband I currently is 30 Mbps.

Trust me, for south asian users, bflix is much much faster than sflix/dopebox or other websites.

It makes more sense to add a completely new site bflix rather than adding dopebox which is the clone of sflix.

I still have hope from dev guys. It's a request of many to add bflx.
