### ISSUE TITLE
Did not show downloaded episode

### ISSUE THREAD

**Issue by yant0** [LagradOst/CloudStream-3#291]
on sd card
![Imagepipe_253](https://user-images.githubusercontent.com/80298071/144158227-973759f0-b5a0-4ab8-a87f-647c38badc7a.jpg)

-----
on app
![Imagepipe_255](https://user-images.githubusercontent.com/80298071/144158255-d37fa393-232a-4ad5-ae07-c0cc86e886dc.jpg)

**Comment by LagradOst** [comment]
Is episode 19 and 20 valid files? How big are they?

**Comment by yant0** [comment]
nope lol. sorry just checked them. but the notafication shows episode is downloaded fine (background download). feel free to close the issue if it isnt a bug
