### ISSUE TITLE
Caching Links For Binge Watching?

### ISSUE THREAD

**Issue by ghfsa** [LagradOst/CloudStream-3#293]
Hello devs, heres another impractical suggestion that I came up with ;) 
I havent seen it implemented in any other app, hence I don't know if its feasible/possible...

Anyway, if we're watching a series, many of us _binge watch or atleast watch a couple of episodes_ most of the time. This app gives us a seamless experience...well, almost. 

You open the app, go to the series, navigate to the episode and start playing. Each step takes not more than a second mostly. Except one part. Although far better than the other multi-links apps out there, fetching of link does take longer than the rest of the steps. This is fine when you initially start your session, but kinda breaks the seamless experience when you _finish the episode and want to immediately go the next one_. You end up on a cliffhanger but then wait for the link to load to continue.

What if I could _cache 'selected episode (season?)link' locally_? 
I go to the series' season, check mark the episodes that I need to cache and hit the 'cache selected links' button? I could even wait a few minutes for this process....so that I can have _an interruption-free experience of enjoying my favourite show later on_.

Could this concept be expanded to include the movies in my watchlist?

Just a thought. I don't actually know how the fetching works, so if this is impractical, do excuse the post. Thanks again for the great app.

![Cache3](https://user-images.githubusercontent.com/83634560/144196437-d2bb8a6e-e25e-4689-a92a-76b497fe2c86.png)

Also a button to clear links cache in app settings?

**Comment by LagradOst** [comment]
This is a very bad idea because many links are ip locked and only valid for a short time. I think I preload links atm when you have watched over 80% or smth. So no, it is simply not possible for many providers.

**Comment by ghfsa** [comment]
> ...only valid for a short time

Didn't know that.


>I preload links atm when you have watched over...

Then this is good as well.
Just to add, if this feature is present, then having an option for its value would be useful. I mean, someone might always watch 3 episodes at a time. For him, prefetching only _'2 subsequent'_ links would suffice. For someone who watches 2, one would suffice. Just thinking about bandwidth. 
Ignore if inconsequential.
Feel free to close the issue. 
Thanks
