### ISSUE TITLE
Add genres to HomePageResponse

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#294]
would it be possible to genres of a film/tv/anime under the scrollable main poster cards at home screen just wondering if it could be done

**Comment by LagradOst** [comment]
Not atm because that data is not apart of the SearchResponse interface so that will have to be added to all providers. Also very few sites provide that information so it would be kinda useless impo.

@ArjixWasTaken y/n on adding that

**Comment by ArjixWasTaken** [comment]
For now n

**Comment by ArjixWasTaken** [comment]
We would need more UI stuff first

**Comment by JasonSmith20** [comment]
I thought so
