### ISSUE TITLE
Add Tv (horizontal) view and navigation

### ISSUE THREAD

**Issue by stojkovskistefan** [LagradOst/CloudStream-3#299]
Add Tv (horizontal) view and navigation

**Comment by LagradOst** [comment]
What?

**Comment by stojkovskistefan** [comment]
The app is created for android phones, but it is not standardized for a TV use. Other apps like this one, have the TV UI view.

**Comment by LagradOst** [comment]
Check out pre.

**Comment by stojkovskistefan** [comment]
Will do. Thanks
