### ISSUE TITLE
Add support for Samsung Smart TV

### ISSUE THREAD

**Issue by Kaluku10** [LagradOst/CloudStream-3#305]
Please i beg you..
Make this app to be supported in samsung smart tv software

**Comment by ArjixWasTaken** [comment]
Should be already possible...
Unless your Samsung is not an ATV (Android TV), something very common for models made before 2017

**Comment by ArjixWasTaken** [comment]
so its an older model?
from what I see non android samsung devices support apps written in c#

CloudStream-3 is written in kotlin and its not possible to change to c#

**Comment by Kaluku10** [comment]
Thank you very much brother❤️

**Comment by ArjixWasTaken** [comment]
Anyways, I'll leave this issue open just in case there is a hidden way to make android apps work on it.

**Comment by LagradOst** [comment]
ye, no support for it
