### ISSUE TITLE
Doesn't allow me to download anything

### ISSUE THREAD

**Issue by CasuallyOrange** [LagradOst/CloudStream-3#307]
I have tried to download stuff multiple times but it always just says loading for a bit and then the loading screen dissappears. I've seen my file manager and it does download something but the file is usually about 25-100 kb and when I open it using the file manager just says error. In the downloads category it shows nothing (the storage permission is on aswell) other than that it's a great app!

**Comment by ArjixWasTaken** [comment]
Android version?
Are you using a custom download path?
etc

give more info

**Comment by CasuallyOrange** [comment]
Yes I'm on android. The download path is storage/emulated/0/cloudstream

**Comment by ArjixWasTaken** [comment]
I did not ask you if you were on android...that is really obvious, this app only runs on android...
I asked for the android version...

**Comment by CasuallyOrange** [comment]
Ah ok, I'm on android 9 pie

**Comment by ArjixWasTaken** [comment]
@Blatzar any ideas?

**Comment by Blatzar** [comment]
Perhaps it's wrongfully downloading an m3u8?
Open the file with a text editor and show output.

**Comment by CasuallyOrange** [comment]
With the new update downloading works fine! Thanks for fixing it :D

**Comment by ArjixWasTaken** [comment]
Nice
