### ISSUE TITLE
Trailer.to error 4001

### ISSUE THREAD

**Issue by cutterchop** [LagradOst/CloudStream-3#309]
note: it is working fine on my phone this occurred on a android emulator im using called ldplayer 4 with these model settings 
 
 
![unknown](https://user-images.githubusercontent.com/31880937/145095144-d517a26b-c812-43c6-8e45-864f455df97b.png)

 
i was trying to watch the tv show The good doctor Season 4 episode 1

and this error appeared 

![unknown](https://user-images.githubusercontent.com/31880937/145093747-7ca1d3b8-488e-474b-97f0-a99fcc9e287f.png)

so i headed to my phone but its working, both devices on latest beta release.

i also can watch on sflix and dopebox just fine this only shows up with trailers.to

![unknown](https://user-images.githubusercontent.com/31880937/145095573-f9ab5290-4b42-4aab-b4aa-a431fcc05c20.png)

extra note: it appears that this problem only happens with the tv series the good doctor 

i tried watching the following as a test : sherlock and 8 mile both opened fine, also i re tried the tv show the good doctor but it gave the same error.

**Comment by LagradOst** [comment]
Exoplayer error, cant be fixed.
