### ISSUE TITLE
Kawaiifu is not working Retry Connection

### ISSUE THREAD

**Issue by bienconsuelo21** [LagradOst/CloudStream-3#310]
![Screenshot_20211208-091134](https://user-images.githubusercontent.com/88108348/145130572-68e12b0f-ec42-4019-8d7c-d57036059578.png)

And I try uninstall the app nothing happens and I try to click the retry connection several times nothing happens please fix the problem thank you.

**Comment by Imsleepyyy** [comment]
Same here :(

**Comment by LagradOst** [comment]
removed due to cloudflare
