### ISSUE TITLE
versionCode not increased

### ISSUE THREAD

**Issue by IzzySoft** [LagradOst/CloudStream-3#316]
Yesterdays release and the previous one from November both share the same `versionCode` (34), so Android won't accept the new release as update. Please take care increasing `versionCode` whenever you make a new release. Maybe you also want to replace the APK on the latest release with one carrying a higher number (eg. 35)?

**Comment by ArjixWasTaken** [comment]
OOF, I never use the stable version so I never had that issue.
@LagradOst fix

**Comment by LagradOst** [comment]
> OOF, I never use the stable version so I never had that issue.
> @LagradOst fix

This is actually not a problem for android. Android only fucks you over if you try to install a lower ver. Still I forgot to increase it.

**Comment by ArjixWasTaken** [comment]
> > OOF, I never use the stable version so I never had that issue.
> > @LagradOst fix
> 
> This is actually not a problem for android. Android only fucks you over if you try to install a lower ver. Still I forgot to increase it. 

This could possibly be done in the Gradle task for the release mode

**Comment by Blatzar** [comment]
> Android won't accept the new release as update

:thinking: 
What kind of device are you running? I've done plenty of experimenting with versionCode without repercussions unless the version number is lower. It should still be upgradable with the same versionCode and it allows you to downgrade if all releases are the same. Does the apk straight up not install and are you sure it's because of versionCode? What does [SAI](https://play.google.com/store/apps/details?id=com.aefyr.sai&hl=en&gl=US) say?

**Comment by IzzySoft** [comment]
> This is actually not a problem for android. Android only fucks you over if you try to install a lower ver. Still I forgot to increase it.

While that is true if you *force* the install, you won't get any notification that a new version is available. So folks have to check manually whether updates are available (which they might forget to do) – instead trusting their F-Droid client will notify them that a new version was [made available here](http://apt.qumran.org/fdroid/index/apk/com.lagradost.cloudstream3) :wink: Because that client will say: "installed? 34. available? 34. OK, nothing to do, kbytnx."

**Comment by LagradOst** [comment]
Ait @IzzySoft I will push an update after some pr, I was not aware that this was a problem because I was not aware that this project was in a FDroid repo (or index, idk the terminology)

**Comment by IzzySoft** [comment]
Thanks @LagradOst – and while it's not the F-Droid.org repo, mine seems to have gotten some popularity already. It's probably the biggest public 3rd party repo, having reached the count of 777 apps today.

Whenever your update is ready, it will again be picked automatically (same for your other app btw). My updater checks once per day – so if it's not today, it's tomorrow :smile:
