### ISSUE TITLE
TOPP ISSUES...

### ISSUE THREAD

**Issue by Kaluku10** [LagradOst/CloudStream-3#321]
1.INDIAN MOVIES DO NOT HAVE ENGLISH SUBTITLES
2.increase movie quality to 4k buh with no lagging
3.CATEGORIZE THE MOVIES...
4.SHOW TRAILER OF THE MOVIE BEFORE WATCHING THE FULL MOVIE
5.SUPPORT VLC PLAYER
NOTE:
THIS APP IS SO AMAZING..I WOULD LIKE TO CONGRATULATE THE OWNERS OF THE APPS..ITS SO AMAZING KEEP UPDATING IT AND MAKING IT MORE BEAUTIFUL.
I WOULD LOVE ONE OF THE ADMINS TO TEACH ME HOW TO CREATE AN APP LIKE THIS...ILL APPRECIATE ALOT.....D

**Comment by LagradOst** [comment]
Cant tell if this is a joke or not

**Comment by Kaluku10** [comment]
Not a joke🤣serious issues...

**Comment by Kaluku10** [comment]
Are u willing to teach me??

**Comment by LagradOst** [comment]
The a tldr
1. Cant
2. Cant
3. Cant
4. Cant
5. Already exists
6. No, Use google that is what I did

**Comment by Kaluku10** [comment]
Which site did you use? To create a movie app
