### ISSUE TITLE
Suggestion: larger list of shows/movies/anime dispalyed

### ISSUE THREAD

**Issue by cutterchop** [LagradOst/CloudStream-3#323]
so basically this wont be a problem i have as i usually have a show/movie/anime on mind to watch, but many of my friends/family keep on scrolling through the lists like trending/latest or the one that is displayed on top until they find something interesting, now its understandable that there wont be a big amount of movies/shows/animes on trending or latest but perhaps can you make the top preview have this feature where it lists what is on the website as recommendations so it does not end as fast they probably have a 100 list that would be enough, but the top preview is most of the time repeating what is on the slots under 
as i checked sflix now the main page has the slots which are displayed in the app so i dont know if its possibile to  do so.
but worth asking. 

![image](https://user-images.githubusercontent.com/31880937/145567305-4f9800de-d1e1-4832-a241-261d33810838.png)

**Comment by LagradOst** [comment]
Top list is just shuffle of the bottom lists
