### ISSUE TITLE
Suggestion: Set Preferred Media to Movies & TV by default

### ISSUE THREAD

**Issue by Darthagnon** [LagradOst/CloudStream-3#326]
I like Anime. But I'd still classify it as somewhat of a niche, and there is a LOT of it. It's not the most welcoming experience to open the app and first thing it seems to come up with is a ton of catgirl anime on the homescreen. Would it be possible to set "Preferred Media" to Movies & TV by default?

Related suggestions:
- `Preferred Media` is an obscure title; add explanatory text below setting, something like `What types of video do you prefer to watch? Too much anime?`
- Subtitles button in the main player UI, so you can enable/disable subs on the fly?

**Comment by Darthagnon** [comment]
Just installed debug build, and Pinoymedia was the first site to come up, with lots of "Adult" films. There definitely needs to be some way of setting a clean default homescreen (some sort of weighted bias to providers?) without pr0n or anime. 

Related suggestion:
- Add label `Provider: Providername.xyz` to top bar, instead of just `Providername`, see screenshot . Would make the GUI more foolproof. Would also be nice if to change providers, instead of just a small dropdown on the far right, the whole `Provider: Providername.xyz` top bar was the button to bring up the provider-switch menu.
![HD-Player_RsSIC2T7K1](https://user-images.githubusercontent.com/20792748/145607768-9497dd04-88e7-4ef2-a634-1c786a10e8f2.png)
![HD-Player_RsSIC2T7K1](https://user-images.githubusercontent.com/20792748/145608180-f3ecf6da-5e77-4f35-938e-66ac3db0e0ff.png)

**Comment by LagradOst** [comment]
> Just installed debug build, and Pinoymedia was the first site to come up, with lots of "Adult" films. There definitely needs to be some way of setting a clean default homescreen (some sort of weighted bias to providers?) without pr0n or anime. 

That was removed in the latest pre.

**Comment by Darthagnon** [comment]
Had some more ideas, for more clearly showing selection, and where buttons are. Mockup (grays are too light, but as a general idea):
![cloudstream3 prototype](https://user-images.githubusercontent.com/20792748/145609809-1764a8ba-f1a8-48d6-9fef-4e76ea009971.png)

Understandable; I should have realised the target audience would prefer it with anime. I had assumed a more general audience, who might be put-off by being greeted by hentai thumbnails on first launch. imo semi-random would be an improvement.

**Comment by LagradOst** [comment]
> - Add label `Provider: Providername.xyz` to top bar, instead of just `Providername`, see screenshot . Would make the GUI more foolproof. Would also be nice if to change providers, instead of just a small dropdown on the far right, the whole `Provider: Providername.xyz` top bar was the button to bring up the provider-switch menu.

No, it looks ugly that way. BUT you have to keep in mind that the top bar is not set in stone, the text there was only to keep it from being empty as I did not have time to add a searchbar up there. In future vers of cs3 there will be more icons up there for different functions

**Comment by Darthagnon** [comment]
I sent it to my mainstream audience friends, who were put off initially by all the anime appearing on first launch (she said "I looked at it, but it was just Chinese films")...

I drew up instructions so she could find the film list and switch:
![Instructions for CloudStream for Ioana](https://user-images.githubusercontent.com/20792748/146066574-cfa71baf-0b00-4880-af6f-e300a20ce6c1.png)
.

**Comment by Darthagnon** [comment]
> [Pinoymedia, with adult films] was removed in the latest pre.

Screenshot from pre-release cbeecb7, featuring films from Pinoy Moviepedia, which appeared on first launch (apologies, I got the name wrong earlier) (imo, some sort of bias, so that niches like anime, or risque Tagalog films don't appear on first launch or less frequently while Random, would be an improvement.
![HD-Player_EFonKWVeks](https://user-images.githubusercontent.com/20792748/146068883-104b381e-42b8-4e2a-b1c3-fefca3bf6dbc.jpg)
 
Films: Pornstar 2: Pangawalang..., My Husband My Lover, Mahjong Nights, A Girl and a Guy
I'm not complaining about the source being there; just a bit concerned, e.g. my aunt might put it on my little nephew's tablet, and on first launch could display 18+ anime like Evangelion (or anything with a lot of fanservice) or random Tagalog pornos is concerning
