### ISSUE TITLE
[Enhancement] For Player on AndroidTV

### ISSUE THREAD

**Issue by ghfsa** [LagradOst/CloudStream-3#328]
Requesting enhancements for Player on AndroidTV
Basically, like the players on streaming services...
- player autohide
- show player by keypress ''UP' 
- Seekbar point, when selected should be prominent.  
![Screa2](https://user-images.githubusercontent.com/83634560/145670632-326ecd6c-5337-43b9-b147-25cea7028cf2.png)

-Also...clock in player?

Thank you

**Comment by tywentghxst** [comment]
Agreed, and should be able to rewind and fast forward from the remote, but also make the player more with lil seeable background to know what button you are on

**Comment by LagradOst** [comment]
> ld be able to rewind and fast forward from the remote, but also make the player more with lil seeable background to know what button you are on
`  KeyEvent.KEYCODE_FORWARD, KeyEvent.KEYCODE_D, KeyEvent.KEYCODE_MEDIA_SKIP_FORWARD, KeyEvent.KEYCODE_MEDIA_FAST_FORWARD -> {
                PlayerEventType.SeekForward
            }
            KeyEvent.KEYCODE_BACK, KeyEvent.KEYCODE_A, KeyEvent.KEYCODE_MEDIA_SKIP_BACKWARD, KeyEvent.KEYCODE_MEDIA_REWIND -> {
                PlayerEventType.SeekBack
            }`

I already have this, I have no idea what keycode your control sends to android so I cant fix it

**Comment by tywentghxst** [comment]
I'm using a TLC Google tv on Android tv software, if that helps to understand

**Comment by tywentghxst** [comment]
Just tested on a fire stick to see if it worked there and it didn't actually

**Comment by ghfsa** [comment]
@tywentghxst I'm using on FiretvStick (Gen2) and last I checked, fast forward/fast backward remote buttons & player button background ARE WORKING on my device.

Maybe try changing app theme? IDK. (I'm using Amoled theme. Will update if I see issue, but consider it working if I don't reply otherwise.)

**Comment by tywentghxst** [comment]
@ghfsa thanks for the idea! I'll try that when I return home and let you know

**Comment by LagradOst** [comment]
Player redesign done
