### ISSUE TITLE
Gogo anime doesn't work

### ISSUE THREAD

**Issue by joyful-cambion** [LagradOst/CloudStream-3#33]
Hello, I tried to wath dragon ball super on gogo anime and I got this error code on the screen, I tried to watch other animes from the website but I still get the same error screen.
![Screenshot_20210827-164840_CloudStream](https://user-images.githubusercontent.com/74503778/131154729-8d5f861d-4e88-4417-9a13-997307264999.jpg)

**Comment by ArjixWasTaken** [comment]
Can't replicate.
Are you sure you are on the latest stable/beta version?

**Comment by joyful-cambion** [comment]
Weird enough, it was 2 days since I posted about this issue but now it seems working maybe the website servers were down in that time, it works perfectly now ... thanks
