### ISSUE TITLE
[Bug] Gogoanime on app says "No links found" while loading the video.

### ISSUE THREAD

**Issue by lasersPew** [LagradOst/CloudStream-3#330]
Gogoanime on app says "No links found" while loading the video then doesn't load the video at all. I tried to go to the site using Firefox and it redirected gogoanime.vc to gogoanime.wiki

**Comment by LagradOst** [comment]
ISP block try dns over https or vpn

**Comment by lasersPew** [comment]
> ISP block try dns over https or vpn

Still doesn't work. I did used both DoH, changing my DNS server config and VPN but it still don't do a thing.

**Comment by lasersPew** [comment]
Maybe you can add a form to change the URL of the site since they change their domain frequently.
