### ISSUE TITLE
Resuming media does not replay from where you left off

### ISSUE THREAD

**Issue by Flam3z** [LagradOst/CloudStream-3#331]
Whenever im in pip mode or just overall leave in the middle of watching something and go back, it seems to go back about 20 or so minutes before than where i actually left off from.

Device: Samsung S10 | Android 11
App Version: 2.3.3

**Comment by LagradOst** [comment]
Unable to replicate, try latest pre

**Comment by Flam3z** [comment]
Replicated it in the pre.

Key Notes: I turned subtitles off and i exited the in-app media player from my phone's back button instead of the app's.

**Comment by LagradOst** [comment]
found possible issue, the phone back button trigger -30sec

**Comment by LagradOst** [comment]
try latest pre in 4min

**Comment by Flam3z** [comment]
Issue has been fixed, cant wait until next update. Thanks
