### ISSUE TITLE
TV SUPPORT

### ISSUE THREAD

**Issue by tywentghxst** [LagradOst/CloudStream-3#332]
I'm using on my TCL Google Tv Android Tv, and a few issues that would make it better are listed below because right now it's a lil broken 

•most of the time when surfing around on Android Tv version you have no idea what or where you are clicking because the dark background is not seeable in most situations

•when playing a show or movie you can't rewind or fast forward with the buttons and need to click the plus 10 or be on the slider and most of the time you can't even see what button your on to click forward or back and end up clicking out of the video by mistake. Please add rewide and fast forward to buttons, just the -10 and +10 would be perfect

•VIDEO PLAYER needs background to see where you are clicking

• also please add a ui timer, like how long the player UI will stay up without buttons being touch until it will disappear, because as of now, if you use it, it just doesn't go away untill you realize it's not going and you gotta click back

Small problem
• the top recommended page, when going left or right, it's showcasing the wrong show/movie for the play and info page causing some confusion on trying to open a recommended 

Over all an amazing app but needs more love for the Android Tv version please 🥺

# THANK YOU SO MUCH FOR YOUR HARD WORK!!!! ♥️♥️

**Comment by tywentghxst** [comment]
THANK YOU SO MUCH FOR YOUR HARD WORK!!!! ♥️♥️

**Comment by LagradOst** [comment]
I would argue that all these issues are solved in latest stable
