### ISSUE TITLE
Add a Arabic source

### ISSUE THREAD

**Issue by Mua10** [LagradOst/CloudStream-3#334]
I hope that you add an Arabic source for anime or movies

**Comment by LagradOst** [comment]
add url to a source so I can lable it as a provider

**Comment by Mua10** [comment]
Like this https://shahed4u.dev/home27/

**Comment by cutterchop** [comment]
> Like this https://shahed4u.dev/home27/

We added a better Arabic site check it out on the latest beta pre release

**Comment by Mua10** [comment]
> > Like this https://shahed4u.dev/home27/
> 
> We added a better Arabic site check it out on the latest beta pre release

Ok thanks
