### ISSUE TITLE
Zoro links not working in-app

### ISSUE THREAD

**Issue by kgbandido** [LagradOst/CloudStream-3#337]
The zoro source no matter the anime will continuously load while in the app. The website works just fine.

**Comment by LagradOst** [comment]
Even in pre-release?

**Comment by Igrissid** [comment]
@LagradOst Also, there are also no dub links.

**Comment by JasonSmith20** [comment]
For me it loads faster in the pre release but no dub I use it for dub because the quality is better than from the other sources.

**Comment by JasonSmith20** [comment]
It is working now

**Comment by kgbandido** [comment]
> Even in pre-release?

Yes I am running pre release, sorry for not specifying.

**Comment by kgbandido** [comment]
Ok now it seems to be working after updating just now
