### ISSUE TITLE
Vf-serie.org search problem

### ISSUE THREAD

**Issue by amorabda** [LagradOst/CloudStream-3#339]
Hi,

There is search problem in vf-serie.org but the problem is on there website it returs host error.
I found a better french provider for movies, tv shows and anime.
https://french-stream.re/
i think its better to have one website for both movies and tv shows so we can have it on home page for french speaking poeple.
actually they have to search movies or tv shows (not working provider).
https://french-stream.re/ is using uptostream and doodstream links and whatching quality is very good, other french websites uses uqloads,

**Comment by Sarlay** [comment]
Yes vf-serie is broken atm
I will probably try to add a french provider later (thanks for the suggestion)

**Comment by amorabda** [comment]
Thanks, i tried lot of sites but i think its the best video quality.
I can suggest others if you want

**Comment by amorabda** [comment]
@Sarlay , tell me if i can help

**Comment by Sarlay** [comment]
@amorabda
