### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ishimagi** [LagradOst/CloudStream-3#340]
![Screenshot_2021-12-16-22-33-12-789_com lagradost cloudstream3](https://user-images.githubusercontent.com/91235066/146427441-2273396c-3aef-4034-bfd5-957bea77ec1c.jpg)
![Screenshot_2021-12-16-22-31-33-685_com lagradost cloudstream3](https://user-images.githubusercontent.com/91235066/146427450-41b6fed9-b3e7-4b0e-8d4e-0b56522720d9.jpg)
In all anime links

**Comment by LagradOst** [comment]
Works for me
