### ISSUE TITLE
Fire TV 4K only shows the older blue icon in launcher instead of new fancy red icon

### ISSUE THREAD

**Issue by Pentaphon** [LagradOst/CloudStream-3#342]
What the title says.

**Comment by LagradOst** [comment]
Blue is for stable, red is for pre and green is for debug. Send ss of icon so I can see if it is the correct one along with your current ver.

**Comment by Pentaphon** [comment]
As you can see, it's definitely Cloudstream Beta as the launcher shows. 

![beta](https://user-images.githubusercontent.com/49374058/146656816-d47ecbc1-0e88-4661-98df-9f19b015227d.jpg)

**Comment by LagradOst** [comment]
This is how pre is supposed to look on a tv
![ic_banner](https://user-images.githubusercontent.com/11805592/146658735-43f92d00-3ccc-4724-947a-f2d4c0c611fc.png)
I searched the entire project and there is no reference to that image in the latest pre nor did the vector image have any references, so my guess is an old pre-release or that your tv has *cached* that image.

**Comment by LagradOst** [comment]
![image](https://user-images.githubusercontent.com/11805592/146658877-db66db76-3827-4b8b-bb0d-c0f8671bdf9d.png)
this is all the png files in the entire project

**Comment by Pentaphon** [comment]
You were right. I uninstalled the app, downloaded the latest beta and now I get this. Just an icon. No banner. This could be a FireTV issue since Kodi has a similar icon as well but maybe they haven't done a banner for FireTV either or FireTV just doesn't let sideloaded apps have banners at all?

![newbeta](https://user-images.githubusercontent.com/49374058/146659322-dafa57d4-50d3-48e2-83f3-1298969b2b18.jpg)
