### ISSUE TITLE
[Request] App for windows

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#343]
Please make this app for windows also

**Comment by JasonSmith20** [comment]
I do not think that would be possible atm because that would be a different project entirely.

**Comment by zeronegithub** [comment]
> I do not think that would be possible atm because that would be a different project entirely.

I think so too

recommended: https://mega.nz/folder/845R2AwB#pxb0rXgk0IwGlAZNdR-Ttg

**Comment by LagradOst** [comment]
> I do not think that would be possible atm because that would be a different project entirely.

^^^^
