### ISSUE TITLE
vf-serie.org not working

### ISSUE THREAD

**Issue by Snoopski21** [LagradOst/CloudStream-3#349]
It's about vf-serie.org,search in not working

**Comment by LagradOst** [comment]
@Sarlay

**Comment by Sarlay** [comment]
Yes, the issue comes from vf-serie, I am working right now on implementing another provider

It will probably be added tomorrow or the next day

**Comment by Snoopski21** [comment]
I suggested the site (wiflix.tel)
They said that the site can't be reached for no reason

**Comment by amorabda** [comment]
@Sarlay if can help tell me

**Comment by amorabda** [comment]
@Sarlay try to add home page for french provider, it will be great, thanks
