### ISSUE TITLE
Add new source [provider]

### ISSUE THREAD

**Issue by Snoopski21** [LagradOst/CloudStream-3#350]
Please add wiflix.tel
Many servers in website like evoload,ddstream,uqload,netu......

**Comment by LagradOst** [comment]
cant even reach the site, no

**Comment by Snoopski21** [comment]
How can't you reach the site?

**Comment by LagradOst** [comment]
it loaded now, but site is really bad and I cant even watch anything

**Comment by Snoopski21** [comment]
Ok thank you,i will look for another site

**Comment by LagradOst** [comment]
> Ok thank you,i will look for another site

no that is not needed
