### ISSUE TITLE
App clone released on play store

### ISSUE THREAD

**Issue by NextDev65** [LagradOst/CloudStream-3#358]
https://play.google.com/store/apps/details?id=com.lagradost.cloudstream3

Do not accept updates pushed by play store or play store variants for this app. If auto update is enabled, you may need to disable it.
On Aurora Store (a play store variant), you can long press the app from under updates and add to App blacklist so prevent receiving updates for that app

**Comment by LagradOst** [comment]
this is a clone not made by me it is irrelevant

**Comment by b3pio** [comment]
I noticed this other guy posting to play store and putting ads in it...Just sad to be honest.... smh
