### ISSUE TITLE
Link not found

### ISSUE THREAD

**Issue by Snoopski21** [LagradOst/CloudStream-3#359]
For example hawkeye serie on vidembed shows link not found
![Screenshot_2021-12-22-17-50-03-299_com lagradost cloudstream3](https://user-images.githubusercontent.com/96396022/147127498-83a0801f-3cf9-43bd-9c2b-035e72fe227b.jpg)

**Comment by cutterchop** [comment]
use another source

**Comment by Snoopski21** [comment]
> 

Tnks

**Comment by LagradOst** [comment]
Should be fixed in pre
