### ISSUE TITLE
Anime Opening provider

### ISSUE THREAD

**Issue by Yashmak620** [LagradOst/CloudStream-3#364]
Add https://themes.moe/ this provider has all anime opening

**Comment by LagradOst** [comment]
Why do you want a provider with only openings / endings????

**Comment by Yashmak620** [comment]
Because there isn't any app where you can get that and i think there is lots of anime opening fan so please reconsider

**Comment by LagradOst** [comment]
Sorry but that is not the purpose of this app. Fork is your best alternative.
