### ISSUE TITLE
[BUG] Next episode and watch history issues

### ISSUE THREAD

**Issue by stojkovskistefan** [LagradOst/CloudStream-3#366]
While watching I have experienced two bugs.

- When finishing with an episode, the next episode feature currently does not work and you have to go back to the main tv-show screen to play the next episode.The occuring error is "Source error ERROR_CODE_IO_UNSPECIFIED (2000) Source error"

![Screenshot_20211224-100823](https://user-images.githubusercontent.com/22908297/147338811-13fdf526-3e5f-424a-affb-4635f2dc5bcd.png)

- When you finish watching an episode, the history of alrrady watched episodes counter goes to the next epidode. Example: I finish watching epidode 4, and when I go to the screen showing all episodes, the blue line(already watched epidodes) under each episode's picture is also shown on episode 5, which I didn't watch at the time

![Screenshot_20211224-101252](https://user-images.githubusercontent.com/22908297/147338746-ae8e182a-8057-45bc-86f9-327f4c4d457a.png)

**Comment by LagradOst** [comment]
Is this in pre or main

**Comment by LagradOst** [comment]
I am unable to repliate any of these issues

**Comment by stojkovskistefan** [comment]
Version: 2.4.5
Tv-show: Rick&Morty
Provider:  Sfix

**Comment by LagradOst** [comment]
> Version: 2.4.5 Tv-show: Regular Show Provider: Sfix

Unable to replicate

**Comment by stojkovskistefan** [comment]
I uninstalled the app, and the issues with the same case scenario are gone. I couldn't replicate the issue again. I consider the issue closed.
