### ISSUE TITLE
Subtitles bug

### ISSUE THREAD

**Issue by cutterchop** [LagradOst/CloudStream-3#376]
I tested all movie sources, it appears to happen only in dopebox and sflix because they are the only ones (I think) that provide subtitles settings anyways, so what is happening is  when you press on source it shows that the subtitles settings is on 'no subtitles' and it also won't let you remove subtitles, I sometimes watch movies without subtitles on etc so this happened

https://user-images.githubusercontent.com/31880937/147501604-1921760f-53c1-4b0a-8217-3799c3cc9eee.mp4

**Comment by yephny** [comment]
Yeah, " no subtitles" still shows subtitles in Dopebox. They aren't embedded subs either.

**Comment by optzeci** [comment]
For me it's the other way around. Since a few days ago I have no subtitles in Sflix, even if English subtitles are activated.

**Comment by LagradOst** [comment]
fixed in pre
