### ISSUE TITLE
Season sorting error

### ISSUE THREAD

**Issue by jeybsss** [LagradOst/CloudStream-3#38]
Season sorting is a big mess, like season 1 is on the last and other seasons are on the beginning, it's hard to find what season you are going to watch

**Comment by LagradOst** [comment]
Send ss, if you are talking about search then there is nothing I can do

**Comment by jeybsss** [comment]
![Screenshot_2021-08-29-19-03-26-39](https://user-images.githubusercontent.com/88224473/131248169-7ae06229-fd41-4581-838f-fffe18e232f2.png)

**Comment by LagradOst** [comment]
willfix

**Comment by LagradOst** [comment]
try the pre-release

**Comment by ArjixWasTaken** [comment]
Can't replicate in the latest stable/beta versions.
