### ISSUE TITLE
App data

### ISSUE THREAD

**Issue by Buddie911** [LagradOst/CloudStream-3#387]
Hi, why does the app consume too much data after the latest update? The app data is too big even when you've barely used the app.

**Comment by LagradOst** [comment]
The cache size is 500mb on the videoplayer, is that the issue?

**Comment by Buddie911** [comment]
Maybe, so how do i reduce that or something?

**Comment by LagradOst** [comment]
not possible atm

**Comment by Buddie911** [comment]
Okay great
