### ISSUE TITLE
Found an app on playstore similar to this

### ISSUE THREAD

**Issue by saurabhinabys** [LagradOst/CloudStream-3#388]
I just want to make sure if the app named 'Movies Time - Tv shows and movies' on play store is your app, and if you're the dev of that app? Or if someone else is using your app to their benifit!!

**Comment by JasonSmith20** [comment]
It is not the devs app somebody basically just stole it without even changing much at all

**Comment by saurabhinabys** [comment]
They even have the apk name exactly same, so shouldn't dev do something about it?

**Comment by LagradOst** [comment]
The app on the playstore is not uploaded by me, and I changed to licence to GPLv3 to prevent this happening in the future. There is nothing I can really do about it

**Comment by saurabhinabys** [comment]
I dont know much, but reporting the app on play store, will it help in any way at all?

**Comment by LagradOst** [comment]
Yes do report it and leave a review linking to the github
