### ISSUE TITLE
Add Undubbed/Original media on Pelisplus (spanish) provider

### ISSUE THREAD

**Issue by JesusCabant** [LagradOst/CloudStream-3#389]
Nowadays a lot of new TV shows and movies are not dubbed, on the app only it's possible to access to dubbed ones. Can you please add support to servers with original audio with subtitles (undubbed)? Pelisplus site has them, it's better for avoiding unsync subtitles issues. Thanks

**Comment by LagradOst** [comment]
url?

**Comment by JesusCabant** [comment]
pelisplus.icu
