### ISSUE TITLE
Some movies on  trailer.to need subscription

### ISSUE THREAD

**Issue by jeybsss** [LagradOst/CloudStream-3#39]
Movies like star wars need subscription to watch, otherwise it will only show the 8 second clip saying you need to subscribe
![Screenshot_2021-08-29-19-32-45-15](https://user-images.githubusercontent.com/88224473/131248963-67597950-c7a3-40e2-87a7-20343d520ae8.png)

**Comment by LagradOst** [comment]
Use VPN, nothing I can do

**Comment by xxxcrow** [comment]
@LagradOst maybe some built-in proxies to somehow bypass the request of the video, and then continue watching without proxy?
