### ISSUE TITLE
Trailers.to

### ISSUE THREAD

**Issue by Gottarocket** [LagradOst/CloudStream-3#391]
Trailers.to episodes doesnt play and when browser icon is clicked it takes to moviedb website instead of trailers.to website .
Test on It's Always Sunny in Philadelphia S5

**Comment by LagradOst** [comment]
Works for me, and taking you to tmdb site is the intended behavior.

**Comment by Gottarocket** [comment]
If you check sfixto it takes to sflix website instead of moviedb

**Comment by LagradOst** [comment]
trailers works diffrently

**Comment by Gottarocket** [comment]
On my end it shows https://0bin.net/paste/46aLxItc#-xDV+xYqmicCQmk+UfclDAokNsUPKIpXmu2lX/sgcx3
