### ISSUE TITLE
[Feature request] Clear cached data

### ISSUE THREAD

**Issue by 1onLSD** [LagradOst/CloudStream-3#395]
Hello, I was using this app for some time now and I noticed something, when you watch an episode/movie online it keep cached data of that in the app directory and that is understandable som you won't wait a long time when you re-enter that same episode again but the problem is there's no choice of deleting this cached data, anyway I tried to watch a movie today and when I checked the app settings I noticed it's 500mb more and I couldn't clear it by tapping "clear cache"  you can only clear it by tapping "clear storage" by then I'll lose my saved shows, fortunately I have root access on my phone and I found the cached data and I cleared it it was in data/data/com.lagrad..../files/media  and I got rid of 500mb of cache.
Anyway I am writing this so I can ask if you could add a button that automatically deletes this by clicking it. Thanks for this amazing app.

**Comment by LagradOst** [comment]
This is fixed in the player brach, will get merged soon
