### ISSUE TITLE
android tv

### ISSUE THREAD

**Issue by techno-arch** [LagradOst/CloudStream-3#4]
add android tv dpad support for the video player and make cloudstream show up on the home screen without the need for forwarder

**Comment by LagradOst** [comment]
When I have very much time on my hands yes

**Comment by JimZiii** [comment]
Any news on the android tv version?
Haven't found anything worth using since the death of the old app.

**Comment by LagradOst** [comment]
Do you feel like the current prerelease version of cs3 works on AndroidTV (does navigation work)

**Comment by Pentaphon** [comment]
> Do you feel like the current prerelease version of cs3 works on AndroidTV (does navigation work)

Tried the latest one and no, it does not work well. You can move from settings to downloads and all that but you can't really select any videos or episodes of shows. Only 33% of the UI works with a remote, I'd say. Somebody with an Android TV needs to just go through the whole app and make sure everything can be accessed with an Android TV remote control.

**Comment by LagradOst** [comment]
:pain: it works perfectly for me on an emulator

**Comment by techno-arch** [comment]
i got a shield so i can check later
