### ISSUE TITLE
No Link Found

### ISSUE THREAD

**Issue by Akshay-1024** [LagradOst/CloudStream-3#404]
Hi guys i was watching food wars anime from the gogoanime server but from the past 2 days when ever i open the anime and play any episode it is showing no link found in the app , but when i open the web version (the globe icon) from the app its playing the episode in the website.

I would prefer it to run in the app video player rather than the web one. Please once take a look

**Comment by ITADORI-15** [comment]
Gogoanime encrypted its URLs so tats the reason these kind of problems r occurring

**Comment by LagradOst** [comment]
fixed in pre
