### ISSUE TITLE
A Strange movie image and message 

### ISSUE THREAD

**Issue by Samy20023** [LagradOst/CloudStream-3#41]
There is a problem in new version and new beta  that there are a couple of movie's image don't show and says that a VPN might be needed for this provider to work correctly. Please fix this problem and check the app once again if there any problems. 

I will send you the problem's image:

1-   ![20210830_021334.jpg](https://user-images.githubusercontent.com/88319767/131270173-3e8994fa-f3df-4800-8b58-e9e7f9b87c33.jpg)

2-   ![20210830_021202.jpg](https://user-images.githubusercontent.com/88319767/131270183-7fd7901d-edcd-4c54-8ad7-ae68285253c6.jpg)

**Comment by LagradOst** [comment]
Provider error.
