### ISSUE TITLE
Issues with subtitles on downloaded content.

### ISSUE THREAD

**Issue by SlamZDank** [LagradOst/CloudStream-3#418]
Theres an issue where subtitles don't show on downloaded videos:
![Screenshot_20220110-011424_CloudStream Beta](https://user-images.githubusercontent.com/83764499/148706944-e875cfdd-b2eb-4855-9162-038f7af2bd87.png)
![Screenshot_20220110-011450_CloudStream Beta](https://user-images.githubusercontent.com/83764499/148706952-f1fa5b52-709a-4b77-92eb-2addc3bda999.png)
and there is also another issue with loading subtitles locally on a downloaded video causing the player to quit and return "No links found" toast
![Screenshot_20220110-011220_CloudStream Beta](https://user-images.githubusercontent.com/83764499/148707005-a85eca4f-829e-4234-b002-316ed0445922.png)
Using latest pre 2.4.8 on samsung A32 android 11.

**Comment by LagradOst** [comment]
subtitles not displaying is a known issue with exoplayer,

subtitles locally on a downloaded video causing the player to quit and return "No links found" toast. storage permission error I guess

**Comment by SlamZDank** [comment]
apparently renaming a local subtitle and moving it in the downloaded cloudstream videos directory and then using it on cloudstream got it to work.
![Screenshot_20220110-232142_CloudStream Beta](https://user-images.githubusercontent.com/83764499/148848358-c59296e5-5eee-4c6c-82aa-74dbc33a6244.png)

**Comment by SlamZDank** [comment]
everything is fixed in the latest pre. thx for fixing this!
