### ISSUE TITLE
A SHORT SYNOPSIS FOR EVERY TV EPISODE ON A SPECIFIC SERIES (Request or Idea)

### ISSUE THREAD

**Issue by Biggy-biggy** [LagradOst/CloudStream-3#422]
Hello good day sir, Can I request this feature sir by chance 
It would be a great feature Idea.. so that some viewers will know what will happen and know what is the events happening in the specific episode of a tv series

**Comment by Biggy-biggy** [comment]
> Hello good day sir, Can I request this feature sir by chance It would be a great feature Idea.. so that some viewers will know what will happen and know what is the events happening in the specific episode of a tv series

**Comment by LagradOst** [comment]
Already exist if provider has it
