### ISSUE TITLE
Should I download pre release build everytime u release?

### ISSUE THREAD

**Issue by ITADORI-15** [LagradOst/CloudStream-3#425]

**Comment by Kaluku10** [comment]
Yes it good coz it fixes some problems..in the app

**Comment by LagradOst** [comment]
Pre-release updates with every commit and that can be a lot. Most stuff are small fixes or changes so it is only really needed to update when you feel like it. that being said, you should update before you make an issue to make sure it is not already fixed.

**Comment by ITADORI-15** [comment]
Thanks for confirming @LagradOst
