### ISSUE TITLE
Name of the movie in copy link 

### ISSUE THREAD

**Issue by inventor7** [LagradOst/CloudStream-3#430]
Can you add the name of the movie in the copied link 
It's always "index "  

Like this one : 

https://b-g-eu-6.betterstream.co:2222/v2-hls-playback/1b3f97fcaadcf6334251e8e0f061ad06a8197a75ec726aaf3c9860669af9002d415952141cf22921d68d5ab81249f22d4f87558175627a5a62729f16c2045c545a468816b0521cc3a19e1b6b5fcef6a5df64cb762f876bd5d4ff5ffa9b1b94bfecef6dc529da72d3a88b29f7014340657102463f80a3d3fb3c2882d43a45deac4a64853a35a25cda1d218fd583de1338cdeefb3ea1e25e58f526c2bf19b219fb3801fb405a94ca273a900e1bbbbd63dd/360/index.m3u8

There's index at the last of the sentence "index.m3u8"
Can u change it to "name_of_the_mocie.m3u8" 
Everytime i copied the link and thhhn'xxxxxx

**Comment by LagradOst** [comment]
what no?

**Comment by inventor7** [comment]
I told you this bcuz whn i open the movie in mx player i need to type name of the movie manually and search it search online mx player 
So if u do tht we don't need to type evrytime the name of the movie

**Comment by LagradOst** [comment]
you do know that you cant simply rename a link and it will work? a link is a location on a file system and changing it will make it stop working

**Comment by inventor7** [comment]
Oh i didn't know tht i'm sorry for this
