### ISSUE TITLE
[BUG] Streamed cache is stored in app data

### ISSUE THREAD

**Issue by CypherpunkSamurai** [LagradOst/CloudStream-3#431]
So I noticed my system storage running out and turns out that the app is storing streamed data. Please fix it by using Android video cache or some other video player library. Or just manually clean leftovers.

![Screenshot_2022-01-12-02-51-42](https://user-images.githubusercontent.com/66906402/149023985-72c5d3b6-35f3-4ebe-b4ea-be86e024d154.png)

**Comment by LagradOst** [comment]
fixed in pre
