### ISSUE TITLE
[FEATURE] Manually select stream quality before playing

### ISSUE THREAD

**Issue by CypherpunkSamurai** [LagradOst/CloudStream-3#432]
Please add option to check which stream quality to play when long clicked on episodes.

**Comment by LagradOst** [comment]
why

**Comment by CypherpunkSamurai** [comment]
> why

Because sometimes we need to watch some episodes in HD while some filler episodes are ok on 360

**Comment by LagradOst** [comment]
that is why you use the souce button in player
