### ISSUE TITLE
Source selection from player

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#433]
Add source selection in player instead of selecting from every source

Example- trailer to, dopebox, sflix makes these source to select from player

And make only one catalogue for one movie or TV show

![IMG_20220112_130905.jpg](https://user-images.githubusercontent.com/87866912/149084281-68f32c1e-3e80-4c3e-9be0-b5a39716e28b.jpg)

This is what i'm saying

**Comment by LagradOst** [comment]
This is not cs2, cant do
