### ISSUE TITLE
Streaming 1080p instead of  preferred480p : Way off from preffered quality for last 2-3 beta releases 

### ISSUE THREAD

**Issue by imDusht** [LagradOst/CloudStream-3#435]
I have set preffered quality 480p and when it wasn't available it plays 360p by default, but for last few updates even if it's set to 480p it streams 1080p (it takes time to load from start and uses a lot data) and after initial loading when source button is accessible i changes it to 480 or 360 whichever available, please fix this a little annoying bug.

**Comment by LagradOst** [comment]
Should be fixed in latest pre
