### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by ITADORI-15** [LagradOst/CloudStream-3#436]
What happens when I give a benene to a dev
![Screenshot_20220112-194306_CloudStream.jpg](https://user-images.githubusercontent.com/83289685/149156503-bc0a1d64-975a-42c9-b483-1c50189e5eda.jpg)

**Comment by LagradOst** [comment]
I eat 🍌

**Comment by justfoolingaround** [comment]
And I steal <img src="https://cdn.discordapp.com/emojis/925072155144753253.png?size=16">.
