### ISSUE TITLE
Requests, adding MAL and anilist sync, AND more sources for old school cartoons

### ISSUE THREAD

**Issue by JimZiii** [LagradOst/CloudStream-3#437]
In shiro we had the ability to log into anlilist and MAL to sync our progress which isn't possible right now.

And on cartoons I wish you had sources for more old school cartoons like Old Donald duck Old Tom and Jerry, old old loony toons and cartoons like that

**Comment by oOflyeyesOo** [comment]
Could do a rewrite to use MAL to display the anime, then it searches the sites, like other apps to keep it simplified and quick.

**Comment by lasersPew** [comment]
You could copy tachiyomiorg/tachiyomi or jmir1/aniyomi Aniyomi's code and some edits since it has the same language(Kotlin) and has the same functionality most(if not all) users want.
