### ISSUE TITLE
Play local files

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#443]
Is there. Any way to play local files in cloudstream

**Comment by LagradOst** [comment]
Yes, in latest beta you can open any video file with cloudstream if you open it via a file manager.

**Comment by Light7654** [comment]
I think my phone doesn't allow


>https://user-images.githubusercontent.com/87866912/149347216-1c2f5f63-96a5-4abe-b924-2ee9921d384b.mp4

Phone- oppo A5s 2020
