### ISSUE TITLE
Trailer.to always sucks

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#444]
https://user-images.githubusercontent.com/87866912/149348051-8c77a312-1894-48ba-a299-b3d91aadaa2b.mp4

It have been loading for 1 min and then get an error

![Screenshot_2022-01-13-19-56-56-28.jpg](https://user-images.githubusercontent.com/87866912/149348378-4b214ad0-63a3-4e64-8464-5eec23bd3cfe.jpg)

**Comment by LagradOst** [comment]
Nothing we can do.

**Comment by Kaluku10** [comment]
Use another site not amust trailers.to
