### ISSUE TITLE
Egybest provider 

### ISSUE THREAD

**Issue by inventor7** [LagradOst/CloudStream-3#447]
Fast + unbuilt Arabic subtitles
Url : 

https://gose.egybest.xyz/explore/?q=%D8%A3%D8%AD%D9%85%D8%AF%20%D8%B7%D8%A7%D9%87%D8%B1%20%D8%A3%D8%AD%D9%85%D8%AF%20%D8%B7%D8%A7%D9%87%D8%B1

**Comment by cutterchop** [comment]
Hello, recently one of the developers decided to work on an Arabic site but we are searching for the best also the link for that site would be : egy.best
We found better sites then it and searching for more

**Comment by cutterchop** [comment]
> Fast + unbuilt Arabic subtitles Url :
> 
> https://gose.egybest.xyz/explore/?q=%D8%A3%D8%AD%D9%85%D8%AF%20%D8%B7%D8%A7%D9%87%D8%B1%20%D8%A3%D8%AD%D9%85%D8%AF%20%D8%B7%D8%A7%D9%87%D8%B1

New site has been added (akwam) check it out in latest beta release
