### ISSUE TITLE
Can't "use system brightness"

### ISSUE THREAD

**Issue by yephny** [LagradOst/CloudStream-3#452]
I liked using the system brightness for Cloudstream but that option seems to be removed from settings.

v.2.5.8.

**Comment by LagradOst** [comment]
Yes, I removed black overlay

**Comment by yephny** [comment]
Any reason why? Anything above this brightness feels too bright to me.

![bright](https://a.pomf.cat/ucectr.png)

**Comment by LagradOst** [comment]
bloat
