### ISSUE TITLE
BIG UPDATE OF 2022

### ISSUE THREAD

**Issue by Kaluku10** [LagradOst/CloudStream-3#453]
What can we expect on the biggest updates of 2022????here some of features if u may add..
1.able to download full season of a series at oncce...
2.Add new sites.
Whats can we expect from you the new features 2022???

**Comment by LagradOst** [comment]
*spoilers*

**Comment by Kaluku10** [comment]
What are spoilers

**Comment by cutterchop** [comment]
Bro I didn't reach that chapter yet please don't spoil
