### ISSUE TITLE
Subtitle outline color not displaying correctly

### ISSUE THREAD

**Issue by SpoopyTim** [LagradOst/CloudStream-3#454]
When selecting darker colors for the subtitle outline used in the player, it only darkens towards the middle left and lightens everywhere else. This makes it impossible to get a black outline and also inadvertently offsets all other colors from their actual color according to the pallete. This is also the case for preset colors.

**Should be black**
![IMG_20220114_225928.jpg](https://user-images.githubusercontent.com/38570914/149596448-4e60de91-e0fb-47bd-9a79-5230851a7d65.jpg)

**Should be dark red**
![IMG_20220114_230428.jpg](https://user-images.githubusercontent.com/38570914/149596382-c319b6d6-de05-43f9-8a69-60f1071c4734.jpg)

**As close to black as possible**
![IMG_20220114_230628.jpg](https://user-images.githubusercontent.com/38570914/149596533-f8295b5b-39da-4cf2-b125-9804e1cee0a9.jpg)

**Comment by LagradOst** [comment]
![Screenshot_20220115_002423_com.lagradost.cloudstream3.debug.jpg](https://user-images.githubusercontent.com/11805592/149597758-e8c914fc-127f-4c90-af0c-a3d529ca7553.jpg)

this is deafult settings

**Comment by LagradOst** [comment]
The problem is not with the app but an app you are using on your phone to make all apps dark mode.
