### ISSUE TITLE
Fix slow loading with video player

### ISSUE THREAD

**Issue by xaviQ7** [LagradOst/CloudStream-3#455]
Developer of cloudstream I would really appreciate it if you could fix slow loading when you watch a movie I don't often see skip loading when I watch a movie I would really like it your app is really nice and I would really use it more if it weren't for slow loading when I watch a movie.i hope you can get fast loading when you watch a movie.

**Comment by LagradOst** [comment]
switch provider, I dont host the videos so there is nothing I can do

**Comment by xaviQ7** [comment]
So you can't fix how long it takes to watch the movie

**Comment by LagradOst** [comment]
no
