### ISSUE TITLE
Discover content by genre

### ISSUE THREAD

**Issue by ImranMZ** [LagradOst/CloudStream-3#459]
![Screenshot_2022-01-13-18-55-50-835_com tdo showbox](https://user-images.githubusercontent.com/93569556/149634989-02eca813-d1a2-4746-b648-016387a95c8c.jpg

Could you please add discovery option like this so we can find movies/series by selecting specific genre
Is it possible ?

**Comment by LagradOst** [comment]
No, it is not possible

**Comment by ImranMZ** [comment]
> No, it is not possible

Okay
