### ISSUE TITLE
Non-free dependencies

### ISSUE THREAD

**Issue by Donkey-Doug** [LagradOst/CloudStream-3#46]
According to my fdroid app, this app has non-free dependencies. What are these dependencies and why are they needed?

**Comment by LagradOst** [comment]
I dont know what it is going on about, all my dependencies exist on github:
https://github.com/Karn/khttp-android
https://github.com/jhy/jsoup
https://github.com/FasterXML/jackson-core
https://github.com/bumptech/glide
https://github.com/google/ExoPlayer
https://github.com/jaredrummler/ColorPicker
https://github.com/brionmario/rhino-library-android
https://github.com/TorrentStream/TorrentStreamServer-Android

**Comment by Blatzar** [comment]
Probably the chromecast dependency

**Comment by LagradOst** [comment]
🤔 well, I am not removing any part of the app because some app store dont like chromecast

**Comment by LPW00** [comment]
> https://github.com/TorrentStream/TorrentStreamServer-Android

I'm sorry, but what's that for? Cloudstream doesn't use torrents, right?

**Comment by LagradOst** [comment]
> 
> 
> > https://github.com/TorrentStream/TorrentStreamServer-Android
> 
> I'm sorry, but what's that for? Cloudstream doesn't use torrents, right?

Yes and no, one hidden provider for cs3 is a torrent. It does not work and https://github.com/TorrentStream/TorrentStreamServer-Android is super slow
