### ISSUE TITLE
max quality 720p

### ISSUE THREAD

**Issue by sajobaba** [LagradOst/CloudStream-3#461]
from january 13th i have a problem of having only 720p quality even if i use preferred 1080p,when i go to site it does have 1080p,anime have 1080p,but series and movies does not,please fix it.

**Comment by Buddie911** [comment]
Same here, 1080p links seem to have disappeared

**Comment by SlamZDank** [comment]
maybe this is why.
![Screenshot_20220116-181926_Bromite](https://user-images.githubusercontent.com/83764499/149670622-81a72664-0554-485a-979b-9c008ada2584.png)
