### ISSUE TITLE
[No Links] issue with certain sites

### ISSUE THREAD

**Issue by ghfsa** [LagradOst/CloudStream-3#462]
Since a couple of days, cannot play anything from _Sflix_ & _Dopebox_. It shows 'No Links'.

I can play by going onto the sites though. _Upcloud_ is their main server? I can play from that & other servers they provide. 

Anyone having same issues?

**Comment by karasuno05** [comment]
Yes I'm having the same with those sites

**Comment by xololunatic** [comment]
I am having this issue also on cloud stream. Its working on my browser becoz of the upcloud server but not in cloud stream. Only working with vpn
