### ISSUE TITLE
TV navigation problem

### ISSUE THREAD

**Issue by knightmob** [LagradOst/CloudStream-3#463]
Hi hello there fellow user of cs3 and it's really a great app, there's just one problem, in app settings the sub section color customization, I can't navigate in that section so I can't change the background sub color pls fix it

TV layout
:TLC 
:Beyond TV 2
:Android 9

**Comment by LagradOst** [comment]
Check prerelease it should have been fixed

**Comment by LagradOst** [comment]
Not an issue with cs3 but the lib cs3 uses
