### ISSUE TITLE
Not able to play Dropbox and sflix without vpn

### ISSUE THREAD

**Issue by ishimagi** [LagradOst/CloudStream-3#464]
Not able to play Dropbox and sflix without vpn 
Vpn has many ads and the modded vpn is not fast enough
Can u do something about it

**Comment by Jhawahar** [comment]
Yes guys.. kindly fix this issue..
Kindly note that we tried using cloudflare or google dns or adgaurd , even though it doesn't work, 
It works only while using vpn but it keeps loading while using vpn , vpn is not speed enough

**Comment by LagradOst** [comment]
Cant be fixed your isp is blocking it or smth
