### ISSUE TITLE
Player not responding

### ISSUE THREAD

**Issue by dhishkyaon** [LagradOst/CloudStream-3#467]
Player is not responding for me in the right side area of the forward seek button.

I changed some settings like double tap to seek in enabled and swipe to seek is disabled if thats related to the issue. I am using latest version 2.5.8 on Pixel 4a (Android 12)

White coloured area is not responding  - 

![Picsart_22-01-16_21-56-10-486.png](https://user-images.githubusercontent.com/88529066/149668614-99593c0c-cf0f-48f7-a92a-8f1c5d14cb30.png)

**Comment by LagradOst** [comment]
Fixed it, it was due to navigationBarHeight being counted twice

**Comment by dhishkyaon** [comment]
issue still exists.

**Comment by dhishkyaon** [comment]
@LagradOst ^
