### ISSUE TITLE
Custom subtitles Not loading

### ISSUE THREAD

**Issue by Yashmak620** [LagradOst/CloudStream-3#474]

**Comment by LagradOst** [comment]
More info needed

**Comment by Yashmak620** [comment]
I tried to load srt subtitles from device but after that video is in buffering mode

**Comment by LagradOst** [comment]
Yes, the video has to reload in order to get the new subtitles

**Comment by Yashmak620** [comment]
How long

**Comment by Yashmak620** [comment]
I don't think you're not  getting i am saying that after loading subtitles it's does come out from buffering mode
