### ISSUE TITLE
Dopebox Sflix No 1080p Sources

### ISSUE THREAD

**Issue by Debjoymon** [LagradOst/CloudStream-3#475]
Previously there are 1080p links for most movies and series but not 720p links only there.Website still has 1080p links.

**Comment by LagradOst** [comment]
fixed in pre

**Comment by Debjoymon** [comment]
> fixed in pre

Sorry still not fixed in pre release.

**Comment by LagradOst** [comment]
Isp issue, it is clearly working for me![Screenshot_20220117_140033_com.lagradost.cloudstream3.prerelease.jpg](https://user-images.githubusercontent.com/11805592/149773752-250c5436-8abc-4d37-9aed-89c19924087c.jpg)

**Comment by Debjoymon** [comment]
> Isp issue, it is clearly working for me![Screenshot_20220117_140033_com.lagradost.cloudstream3.prerelease.jpg](https://user-images.githubusercontent.com/11805592/149773752-250c5436-8abc-4d37-9aed-89c19924087c.jpg)

Can you check series please?
