### ISSUE TITLE
Sflix and dopebox Series not working

### ISSUE THREAD

**Issue by Thorodinson1** [LagradOst/CloudStream-3#476]
Sflix and dopebox Series not working but movies section is working in series it is showing no links found.

https://user-images.githubusercontent.com/95184073/149782587-793980ad-a83f-437c-9508-73b825973d4d.mp4

https://user-images.githubusercontent.com/95184073/149783174-a00011e4-c978-473b-8a41-497c326cda7f.mp4

**Comment by Thorodinson1** [comment]
@

> Sflix and dopebox Series not working but movies section is working in series it is showing no links found.
> 
>  Screenrecorder-2022-01-17-19-29-28-57.mp4

**Comment by Thorodinson1** [comment]
Series not working

Uploading Screenrecorder-2022-01-17-19-36-23-764.mp4…

**Comment by Debjoymon** [comment]
Same

**Comment by LagradOst** [comment]
Check latest pre

**Comment by Thorodinson1** [comment]
> Check latest pre

Iam using latest pre
