### ISSUE TITLE
After I Add Subtitles To Video It's Doesn't Play Normal or doesn't Come of buffering mode

### ISSUE THREAD

**Issue by Yashmak620** [LagradOst/CloudStream-3#484]
Look Here i Add the subtitles to video
![Screenshot_2022-01-19-08-40-37-34_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/90566456/150057225-366e7bca-b0b7-43d0-88eb-dd7cc164dd8d.jpg)
Now After That It will Remain like this
![Screenshot_2022-01-19-08-40-46-15_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/90566456/150057573-58bcdb0c-929c-4b1b-a1b7-56076752f54d.jpg)

**Comment by LagradOst** [comment]
ass format not supported iirc

**Comment by Yashmak620** [comment]
I also tried srt

**Comment by Yashmak620** [comment]
![Screenshot_2022-01-19-12-04-27-32_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/90566456/150077175-0f0d9cf6-8d50-41bd-b255-f1917f96e6a1.jpg)
![Screenshot_2022-01-19-12-04-31-48_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/90566456/150077259-69bd2bef-f9b4-414e-bec6-0ad048e005f0.jpg)

**Comment by cutterchop** [comment]
use a other source ( for better quality )

**Comment by Yashmak620** [comment]
Video Is playing Normal but after i add subtitles it doesn't Come out of buffering mode

**Comment by LagradOst** [comment]
Android ver, app ver, subtitle file and any popups that show some sort of error message?

**Comment by Yashmak620** [comment]
Android Version 9,App version 2.5.8, Subtitles file srt and it doesn't shows any pop up any message.

**Comment by LagradOst** [comment]
Fixed in 038800d93a8076638f58122a98d985263065f3ca the problem was a zero width space character
