### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by gaylexiv** [LagradOst/CloudStream-3#485]
Subtitles keep missing when I move on to the next episode. It only shows when i apply auto select language but it doesn't always work.

**Comment by LagradOst** [comment]
So it wont show subs even if they exist? What provider? Do they show when selected, you need to give more info.

**Comment by gaylexiv** [comment]
![Screenshot_2022-01-19-17-21-31-000_com lagradost cloudstream3](https://user-images.githubusercontent.com/98002558/150101321-58eb2598-6409-411e-8734-de6be8f5d7f9.jpg)
It's like this. Most of the provider. I uninstalled it but it still not fixed.

**Comment by LagradOst** [comment]
it means that no subtitles are found or that they are loading the the background
