### ISSUE TITLE
Loading speed

### ISSUE THREAD

**Issue by xaviQ7** [LagradOst/CloudStream-3#486]
Dev, is it possible if you make the loading speed quicker when you watch something.If you could that would be great.

**Comment by LagradOst** [comment]
no, not possible

**Comment by LagradOst** [comment]
switch provider

**Comment by ITADORI-15** [comment]
Bro if u shud increase ur wifi speed for tat

**Comment by ITADORI-15** [comment]
Ig*

**Comment by xaviQ7** [comment]
Dev, I am not talking about when you watch a video and it is loading I'm talking about the part when it eventually says skip loading

**Comment by xaviQ7** [comment]
Btw I'm getting a new wi-fi system

**Comment by LagradOst** [comment]
> Dev, I am not talking about when you watch a video and it is loading I'm talking about the part when it eventually says skip loading

All loading in app is as fast as it can be rn

**Comment by xaviQ7** [comment]
Ok thnx
