### ISSUE TITLE
Feature Request-> Can you make a diffrent repo for only Exo player with all fertures and UI ?

### ISSUE THREAD

**Issue by AndroMaterial** [LagradOst/CloudStream-3#492]
I really love this player want to use this one but the codebase is huge I have tried multiple times but was unable to separate both Exo player and Ui.

**Comment by LagradOst** [comment]
All the exoplayer logic is located in https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt with NO ui bindings

https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/player/AbstractPlayerFragment.kt implements the android boilerplate and some basic UI all players should have such as pause. It has some empty methods that must be overridden from a higher level.

https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/player/FullScreenPlayer.kt implements all UI logic for the player that is not related to how the player gets its links, this is where the UX can be changed, for example if you want to make swipe do smth differently.

https://github.com/LagradOst/CloudStream-3/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt is where CS3 Link loading magic interacts with the player and also updates some relevant UI

**Comment by LagradOst** [comment]
So if you want to implement the CS3 Player in your own app, then I suggest you use FullScreenPlayer and change stuff, atm I feel like moving it to a different repo seams a bit overkill
