### ISSUE TITLE
No episodes found on frenchstream source

### ISSUE THREAD

**Issue by GogerN01** [LagradOst/CloudStream-3#493]
No episodes found on frenchstream source but on the website, episodes are available and working.

![Screenshot_20220120-152624](https://user-images.githubusercontent.com/72227362/150357909-867cb136-1f31-45df-abbb-9241e1b0316c.jpg)
![Screenshot_20220120-152653](https://user-images.githubusercontent.com/72227362/150357917-3a7e9d8a-a09a-493c-86a8-61ab2b1bbd44.jpg)

**Comment by LagradOst** [comment]
@Sarlay

**Comment by Sarlay** [comment]
Yeah I know about the issue, it's because no trailer url is provided on the website and it points to a null element

**Comment by LagradOst** [comment]
@Sarlay Then check out ?. for all those elements
