### ISSUE TITLE
Add Subtitles

### ISSUE THREAD

**Issue by pixelroll** [LagradOst/CloudStream-3#5]
Good evening,

first of all, thank you for your work :)
Secondly, would it be possible to put back the subtitles?
With opensubtitles for example.
Or to add the possibility to open on another player.

If not, there are plenty of sites of the same kind that often have the same sources with a lot of subtitles:

yesflix .is
flixtor .ws
123moviestv .me
fmoviesc .org
fmovies .app

(in short, fmovies clones)

Thank you.

**Comment by LagradOst** [comment]
You can open in an external player (Only VLC supported atm) by long holding an episode and pressing "Play in External App".

Yes, more providers with subtitle support and opensubtitles is planned

**Comment by pixelroll** [comment]
I am only offered the app reader or the browser.

**Comment by amorabda** [comment]
> You can open in an external player (Only VLC supported atm) by long holding an episode and pressing "Play in External App".
> 
> Yes, more providers with subtitle support and opensubtitles is planned

Great, i think it is very important feature

**Comment by joybavisi** [comment]
I cannot see subtitles here
![Screenshot_20210902_130442](https://user-images.githubusercontent.com/36401796/131808100-a592b46d-531c-430d-9cc7-a3da9a9dba69.jpg)

**Comment by LagradOst** [comment]
@joybavisi That is because that provider does not have subtitles, I will add opensubtitles support later.

**Comment by cutterchop** [comment]
> Good evening,
> 
> first of all, thank you for your work :) Secondly, would it be possible to put back the subtitles? With opensubtitles for example. Or to add the possibility to open on another player.
> 
> If not, there are plenty of sites of the same kind that often have the same sources with a lot of subtitles:
> 
> yesflix .is flixtor .ws 123moviestv .me fmoviesc .org fmovies .app
> 
> (in short, fmovies clones)
> 
> Thank you.

Hi
Update - 2022

Every site with subtitles will most likely display in app with the ability to change its font size etc, except if it's hard-coded in it

Also now there is a feature added by lag where u can load external subs, also able to play a video on a external player like vlc

Are you still using the app :-)?
