### ISSUE TITLE
Tried opening demon slayer from zoro server and this happens

### ISSUE THREAD

**Issue by ITADORI-15** [LagradOst/CloudStream-3#505]
![Screenshot_20220123-221044_CloudStream.jpg](https://user-images.githubusercontent.com/83289685/150688594-78b850fb-7605-4df0-88d8-c3448f368c46.jpg)

**Comment by LagradOst** [comment]
Cloudflare

**Comment by ITADORI-15** [comment]
How do I resolve it plz help

**Comment by LagradOst** [comment]
You wait
