### ISSUE TITLE
Episodes not perfectly arranged

### ISSUE THREAD

**Issue by joybavisi** [LagradOst/CloudStream-3#51]
I have started using the Cloudstream app since 2 days. I have came across the problem that the episodes in some tv shows are not arranged as per the seasons they belong to. They are not organized season-wise. This makes it hard to fimd the episode which we have left to watch. Please resolve this issue in the next update.

**Comment by ArjixWasTaken** [comment]
This alone means shit (nothing).
Be more specific.

What provider are you using?
Link to tv show that has no season ordering?

**Comment by joybavisi** [comment]
I downloaded older version of Cloudstream, so there was this issue. But I have now upgraded to the latest version, which gives no such issues. Thanks anyway.

**Comment by joybavisi** [comment]
I downloaded older version of Cloudstream, so there was this issue. But I have now upgraded to the latest version, which gives no such issues. Thanks anyway.
