### ISSUE TITLE
Site Suggestion

### ISSUE THREAD

**Issue by karasuno05** [LagradOst/CloudStream-3#521]
There's this site for watching and downloading anime - animepahe.com its really good and fast but it only provide sub anime but its really good it will be great if you add it.

**Comment by LagradOst** [comment]
Ot is already in cs3, but was removed @ArjixWasTaken

**Comment by ArjixWasTaken** [comment]
Uhh, I wrote like 40 lines of text, and I decided that was not a good move on my part

So in summary: no, it won't be added back unless there is a volunteer to maintain the code for it.

**Comment by karasuno05** [comment]
Ok . I know there is a lot of work and i appreciate your efforts for creating and maintaining this beautiful app but i have a request to make 
Add other site for movies and tv shows cause the site already in the app have issue sometimes like no 1080p link found or like video is not played.
For movies and series i have suggest hdtoday.tv great website

**Comment by LagradOst** [comment]
animepahe.com was added in latest pre
