### ISSUE TITLE
Sflix loading time and resume link loading

### ISSUE THREAD

**Issue by Thorodinson1** [LagradOst/CloudStream-3#532]
While playing movies in latest beta of cloud stream it is taking more time than earlier beta bulids. In Beta update before January 18 it is fine and there is no problem in Stable update, Both them have fast loading.
I installed and checked both now  this issue is only in beta update. 
And also when pressing back button in top left corner and then playing movie again in older beta update and in Stable update it resumes quickly, but in latest beta update it load movie very slowly.

1st older beta

https://user-images.githubusercontent.com/95184073/151663415-f80adfb4-0028-4748-a48c-ee3007709a23.mp4

2nd latest beta

https://user-images.githubusercontent.com/95184073/151663457-f9efafed-d8b1-4d6e-8238-e61bbc22b63e.mp4

Please check these issues and thank you again for this wonderful app 😊❤️😊❤️

**Comment by LagradOst** [comment]
The main reason why sflix is now slower is because it loads more links

![Screenshot_20220129_180837_com.lagradost.cloudstream3.jpg](https://user-images.githubusercontent.com/11805592/151670284-076bfd32-b488-4b53-a039-0a5fd5d75441.jpg)![Screenshot_20220129_180757_com.lagradost.cloudstream3.prerelease.jpg](https://user-images.githubusercontent.com/11805592/151670289-8e492aa2-b649-4320-89ca-f8174224d8fc.jpg)

The other issue is more due to link cache.

**Comment by LagradOst** [comment]
It loads more links because I got 100000 issues about 1080p missing, and the cache is because I changed the underlying link loading system

**Comment by ghfsa** [comment]
> It loads more links because I got 100000 issues about 1080p missing, and the cache is because I changed the underlying link loading system

Can the load time be decreased for those of us who only want 720p? For those of us who have set 720p in the _app settings_ be given the previous iteration of loading? Or can the app start the video once the selected resolution is found while loading the rest in background?

Cause the loading time has _increased significantly_. Whereas previously the links would load in maybe 30 seconds, now it may take upto 3 minutes! Thats _600%_ jump.

**Comment by imxcr** [comment]
> While playing movies in latest beta of cloud stream it is taking more time than earlier beta bulids. In Beta update before January 18 it is fine and there is no problem in Stable update, Both them have fast loading.
> I installed and checked both now  this issue is only in beta update. 
> And also when pressing back button in top left corner and then playing movie again in older beta update and in Stable update it resumes quickly, but in latest beta update it load movie very slowly.
> 
> 1st older beta
> 
> https://user-images.githubusercontent.com/95184073/151663415-f80adfb4-0028-4748-a48c-ee3007709a23.mp4
> 
> 
> 
> 2nd latest beta
> 
> https://user-images.githubusercontent.com/95184073/151663457-f9efafed-d8b1-4d6e-8238-e61bbc22b63e.mp4
> 
> 
> Please check these issues and thank you again for this wonderful app 😊❤️😊❤️
> 
> 
> 

hey, can i have the old beta link? bc I can't find it : / ty!

**Comment by LagradOst** [comment]
should be fixed
