### ISSUE TITLE
Recommendations/similar like Netflix. Search/Browse by Genre

### ISSUE THREAD

**Issue by Bungeexgum** [LagradOst/CloudStream-3#548]
This app is 1years or more now. But still no improvement, it's like a site that only gives movie/tvshow nothing else. You won't know who are the cast. The same to anime there's no recommendations and similar below like Netflix or any other app/site. You don't know if that anime has season 2 Or Ova. Please add this very useful features. Enough adding more source zoro.to and gogo is enough. The same for movie enough adding.

**Comment by LagradOst** [comment]
not possible
