### ISSUE TITLE
Hindi https://ww6.9movierulz.bar/

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/CloudStream-3#549]
Dear Dev.. Thank you very much for this amazing application. May I request you to kindly check the possibility of adding Hindi audio wherever it's available please?

**Comment by LagradOst** [comment]
url to a hindi site?

**Comment by Pranithjainbp84** [comment]
@LagradOst https://ww6.9movierulz.bar/

_Sent from my AC2001 using [FastHub-RE](https://github.com/LightDestory/FastHub-RE/)_

**Comment by imurreflection** [comment]
Dear Dev, may I please know when can we expect this addition. Many thanks for your great work. Regards

**Comment by LagradOst** [comment]
no eta on anything

**Comment by imurreflection** [comment]
No worries my friend..have a nice day

**Comment by imurreflection** [comment]
Kindly consider https://hindmovie.org/ 
For Hindi source as the previous site domains are frequently changed like it has now changed to https://9movierulz.art/
