### ISSUE TITLE
why this permission REQUEST_INSTALL_PACKAGES is there 

### ISSUE THREAD

**Issue by AndroMaterial** [LagradOst/CloudStream-3#551]
no offense to the dev. but why this REQUEST_INSTALL_PACKAGES  permision is there.

**Comment by LagradOst** [comment]
You need that permission to update the app on api > 25 from inside the app. Regular apps does not need it because you instead use some sort of play store/Fdroid, but cs3 only officially exist here on github and I dont want users to download off a site for every update.
