### ISSUE TITLE
Resume series - Netflix UI button

### ISSUE THREAD

**Issue by imxcr** [LagradOst/CloudStream-3#564]
idk how to explain but yeah my req if it's possible tho : )

![Untitled244_20220204202039.png](https://user-images.githubusercontent.com/98096677/152528157-9fb53eee-028d-4b9c-8df0-532376fd6c82.png)

**Comment by LagradOst** [comment]
Very possible to joink that from netflix

**Comment by imxcr** [comment]
this is the movie one if u guys would like to add : D
and tysm devs that was v fast! have a good night < 3

![Untitled245_20220205000536.png](https://user-images.githubusercontent.com/98096677/152562321-44008dde-8684-4130-bc3a-7ac97ab9aaf7.png)

**Comment by imxcr** [comment]
LOL im jus spying on free Netflix subs and tryna look to their some features then suggest it in here o_O
