### ISSUE TITLE
Sflix and Dopebox not working.

### ISSUE THREAD

**Issue by noah010** [LagradOst/CloudStream-3#566]
The site works fine but it says "no link found" in the app.

**Comment by Buddie911** [comment]
The sites dont work either... i just tried them

**Comment by Rinhak** [comment]
It's not working.... Showing source error 2004

**Comment by noah010** [comment]
> The sites dont work either... i just tried them

It's working. I already tried it before posting an issue.

**Comment by Buddie911** [comment]
Well its not for me, their two first severs are definitely not working

**Comment by Rinhak** [comment]
Not working-

![Screenshot_20220204-234244_CloudStream](https://user-images.githubusercontent.com/99042103/152581508-ab298242-7d07-4d9b-b167-c3045d3b17e0.jpg)

**Comment by Rinhak** [comment]
In the updated version it's showing "No links found".

**Comment by 9MoIssam9** [comment]
In the original version sflix is not working but in the beta version it works perfectly.
