### ISSUE TITLE
Sflix is not working

### ISSUE THREAD

**Issue by Rinhak** [LagradOst/CloudStream-3#569]
Just wanted to inform that sflix is not working all of a sudden. Also in the updated version, it's showing "no link found". Kindly look into it if possible. Thank you for this app.
![Screenshot_20220204-234244_CloudStream](https://user-images.githubusercontent.com/99042103/152628810-0a83faa9-9c9d-4744-9f11-cc9965b23268.jpg)

**Comment by noah010** [comment]
> Just wanted to inform that sflix is not working all of a sudden. Also in the updated version, it's showing "no link found". Kindly look into it if possible. Thank you for this app. ![Screenshot_20220204-234244_CloudStream](https://user-images.githubusercontent.com/99042103/152628810-0a83faa9-9c9d-4744-9f11-cc9965b23268.jpg)

It is working in my phone. But not in my TV. Are they blocking a brand or IP? No problem at all in my phone. Just my TV.

**Comment by Rinhak** [comment]
> > Just wanted to inform that sflix is not working all of a sudden. Also in the updated version, it's showing "no link found". Kindly look into it if possible. Thank you for this app. ![Screenshot_20220204-234244_CloudStream](https://user-images.githubusercontent.com/99042103/152628810-0a83faa9-9c9d-4744-9f11-cc9965b23268.jpg)
> 
> It is working in my phone. But not in my TV. Are they blocking a brand or IP? No problem at all in my phone. Just my TV.

Nope... Still not working. Both in old and current versions.

**Comment by Rinhak** [comment]
> > Just wanted to inform that sflix is not working all of a sudden. Also in the updated version, it's showing "no link found". Kindly look into it if possible. Thank you for this app. ![Screenshot_20220204-234244_CloudStream](https://user-images.githubusercontent.com/99042103/152628810-0a83faa9-9c9d-4744-9f11-cc9965b23268.jpg)
> 
> It is working in my phone. But not in my TV. Are they blocking a brand or IP? No problem at all in my phone. Just my TV.

Nope. Still not working, both in the current and updated version.

**Comment by xololunatic** [comment]
Same problem and same error in both sflix and dopebox

**Comment by Zeroo097** [comment]
Same here sflix VidEmbed and dopebox are not working

**Comment by 32423d** [comment]
I got this error for a few days ago but now all sflix.to content is working with cloudstream and I no longer get this error.

**Comment by Zeroo097** [comment]
Update:All The Sites are working fine with a DNS Changer

**Comment by Buddie911** [comment]
Same i used DNS too

**Comment by noah010** [comment]
> Update:All The Sites are working fine with a DNS Changer
What DNS did you use?

**Comment by Zeroo097** [comment]
I Use 1.1.1.1

**Comment by Zeroo097** [comment]
> > Update:All The Sites are working fine with a DNS Changer
> What DNS did you use?
> 

I Use 1.1.1.1
