### ISSUE TITLE
An option to change language

### ISSUE THREAD

**Issue by tonya1545b** [LagradOst/CloudStream-3#57]
it will be nice to have a option to change the language.

**Comment by ArjixWasTaken** [comment]
What language tho?
The UI language?

**Comment by LagradOst** [comment]
@ArjixWasTaken rn no option to change the app language from settings is present, so you have to go into system settings to change lang.

**Comment by joybavisi** [comment]
Plz give an option to change language of a movie or tv show (dubbed) because many shows are not in english language

**Comment by LagradOst** [comment]
@joybavisi completely different issue and no.

**Comment by ArjixWasTaken** [comment]
> Plz give an option to change language of a movie or tv show (dubbed) because many shows are not in english language

How would that even be possible?
Would we translate the movie real time and use TTS for the audio?

**Comment by joybavisi** [comment]
> > Plz give an option to change language of a movie or tv show (dubbed) because many shows are not in english language
> 
> How would that even be possible?
> Would we translate the movie real time and use TTS for the audio?

Some movies and tv shows are also released as dubbed movies and tv shows. Provide links for that.
