### ISSUE TITLE
Disable debugging

### ISSUE THREAD

**Issue by dhishkyaon** [LagradOst/CloudStream-3#572]
The Izzy-on-Droid repo is marking an anti-feature of compiled from debbuging for this app.

can you explain whats that and how does it affects app security.

**Comment by LagradOst** [comment]
I can fix in next release. It simply means that you can attach a debugger as I forgot to add debug = false

Ye it is good for some banking app to have this, but it is not really important for cs3.

**Comment by LagradOst** [comment]
fixed
