### ISSUE TITLE
Sflix 

### ISSUE THREAD

**Issue by ITADORI-15** [LagradOst/CloudStream-3#573]
![Screenshot_20220205-181636_CloudStream Beta.jpg](https://user-images.githubusercontent.com/83289685/152642727-54c3d628-b6e5-4040-9772-804bb57fe079.jpg)
Not working

**Comment by Zeroo097** [comment]
You'll need a vpn because the site may be blocked in your region

**Comment by Buddie911** [comment]
It hasnt worked for a while though

**Comment by Light7654** [comment]
after vpn its working but link doest found
