### ISSUE TITLE
Add ability to delete downloaded episode/series

### ISSUE THREAD

**Issue by xaviQ7** [LagradOst/CloudStream-3#575]

**Comment by ITADORI-15** [comment]
Bro head to the downloads section 
From the downloaded episodes u can c a dustbin kind of a icon at the right end okay....click on that and ur wish will be fullfilled![20220205_235045.jpg](https://user-images.githubusercontent.com/83289685/152653995-ef02688c-f905-4003-aef6-9be8f3d255d9.jpg)

**Comment by xaviQ7** [comment]
Oh I didn't see that thnx

**Comment by xaviQ7** [comment]
Q

**Comment by ITADORI-15** [comment]
Guess ur new 2 this app...your welcome😁

**Comment by xaviQ7** [comment]
I'm not

**Comment by xaviQ7** [comment]
I've been using this app for 2 mnths it's bcus I never download stuff

**Comment by ITADORI-15** [comment]
Ohh whatever 😃Enjoy🙂

**Comment by xaviQ7** [comment]
Lol

**Comment by xaviQ7** [comment]
Give me good shows to watch
