### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Adhi2314** [LagradOst/CloudStream-3#58]
![Screenshot_20210902-100148](https://user-images.githubusercontent.com/87760343/131782279-fa8327f1-96fe-4296-b7e8-b71cb7efb925.png)
I can't open any movies in trailor.to 🤷🏻‍♂️

**Comment by ArjixWasTaken** [comment]
Not a fricking bug man, it's not available on the site, that's all.
![image](https://user-images.githubusercontent.com/53124886/131805543-7e17904e-6ea7-4e3f-bec5-ae5d85007df2.png)

And also trailers.to is not the most stable site.
