### ISSUE TITLE
Option to NOT download subtitles when downloading a video

### ISSUE THREAD

**Issue by steamedham544** [LagradOst/CloudStream-3#581]

**Comment by LagradOst** [comment]
Already exist in subtitle settings

**Comment by steamedham544** [comment]
It doesn't exist. There is no "none" option under "downloaded" languages.

**Comment by LagradOst** [comment]
![Screenshot_20220206_123738_com.lagradost.cloudstream3.debug.jpg](https://user-images.githubusercontent.com/11805592/152679048-5f56ba4a-f8bf-4e47-ac32-85292253ff5d.jpg)![Screenshot_20220206_123740_com.lagradost.cloudstream3.debug.jpg](https://user-images.githubusercontent.com/11805592/152679050-ab0d2703-04d9-40b0-beeb-5d672861f496.jpg)

yes, just deselect

**Comment by steamedham544** [comment]
Got it. Cheers.
