### ISSUE TITLE
Change the search 

### ISSUE THREAD

**Issue by xaviQ7** [LagradOst/CloudStream-3#584]
Basically I would like the search thing back to how it was because I can't click on anything it won't do anything.I like it when it says the website name and there are movies under it.Now it shows movies no website name

**Comment by Light7654** [comment]
But it still shows website name

May be you turned of advance search option

**Comment by xaviQ7** [comment]
Thnx bro your a lifesaver

**Comment by xaviQ7** [comment]
Thnx

**Comment by Light7654** [comment]
Your welcome
