### ISSUE TITLE
Resume movies- Netflix UI button

### ISSUE THREAD

**Issue by Thorodinson1** [LagradOst/CloudStream-3#585]
this is the movie one if u guys would like to add : D
and tysm devs that was v fast! have a good night < 3

![Untitled245_20220205000536.png](https://user-images.githubusercontent.com/98096677/152562321-44008dde-8684-4130-bc3a-7ac97ab9aaf7.png)

_Originally posted by @imxcr in https://github.com/LagradOst/CloudStream-3/issues/564#issuecomment-1030128605_

Can you add this resume ui to cloud stream 
Thank you  
😊

**Comment by LagradOst** [comment]
done
