### ISSUE TITLE
Sflix is not working

### ISSUE THREAD

**Issue by Rinhak** [LagradOst/CloudStream-3#594]
Sflix is one of the best site for watching movies and shows. It has not been working properly for a long time. I request the dev to please look into it. It's been showing "no links found" continuously. Please 🙏🏻

**Comment by noah010** [comment]
> Sflix is one of the best site for watching movies and shows. It has not been working properly for a long time. I request the dev to please look into it. It's been showing "no links found" continuously. Please 🙏🏻

I thought it was just me. Please fix it.

**Comment by noah010** [comment]
> Sflix is one of the best site for watching movies and shows. It has not been working properly for a long time. I request the dev to please look into it. It's been showing "no links found" continuously. Please 🙏🏻

Actually, it works perfectly in my phone. It's showing "no links found" in my tablet. I triend to use von and dns changer but nothing change. Is there a setting need to be turned on for it to work?

**Comment by Buddie911** [comment]
Doesn't work on my tablet too, it was working yesterday

**Comment by noah010** [comment]
> Doesn't work on my tablet too, it was working yesterday

Are they blocking it? I mean a specific brand or IP or anything. Sflix and Dopebox doesn't work. When I try to play movie on the website, it's working. On the other hand, Zoro is working good as fuck.

**Comment by Buddie911** [comment]
Trailers to works on mine, idk if they are but im gonna try the DNS thing again

**Comment by Rinhak** [comment]
> Trailers to works on mine, idk if they are but im gonna try the DNS thing again

Can you tell me how to make it work?

**Comment by Buddie911** [comment]
Sflix just doesn't work for me even its newest clone but trailers to does even without DNS

**Comment by Rinhak** [comment]
In the latest version, it's showing "no links found". If you use the older version, they'll play it for 2 minutes and then it'll crash showing "source error http 2004". It was working fine last week.

**Comment by Buddie911** [comment]
I give up lmao

**Comment by noah010** [comment]
> In the latest version, it's showing "no links found". If you use the older version, they'll play it for 2 minutes and then it'll crash showing "source error http 2004". It was working fine last week.

For real.

**Comment by Maddyhf** [comment]
Sflix is working now

**Comment by Buddie911** [comment]
> Sflix is working now

Well its certainly not for me

**Comment by ITADORI-15** [comment]
Guys y dont u use sflix.pro website itself......it doesnt hve ads also......if still u want app for movies ig showbox is good enough

**Comment by Buddie911** [comment]
> Guys y dont u use sflix.pro website itself......it doesnt hve ads also......if still u want app for movies ig showbox is good enough

Oh i use those, and i use vumoo.to, yes ads but they update fast especially the shows
