### ISSUE TITLE
Can you put vidcloud,hydrex etc as they have huge repo of content?

### ISSUE THREAD

**Issue by pranimation** [LagradOst/CloudStream-3#597]
First of all this app is good but it lacks of movies specially non famous one. If some Dev can work on Vidcloud,hydrex etc or use bee tv sources it will be outstanding. If you don't agree you can close this issue though this app has good collection of famous movies and i like it.

**Comment by LagradOst** [comment]
url?

**Comment by pranimation** [comment]
i can give you source url since i saw those as iframe i don't know exact url.
https://c1ne.co/ (fast streaming)
https://fsapi.xyz/ (has all url i told before)
Update: I can't stream via trailers.to it shows waiting dialog on player screen.

**Comment by LagradOst** [comment]
#24
