### ISSUE TITLE
Please make Sflix and Dopebox work 🙏🏻

### ISSUE THREAD

**Issue by Rinhak** [LagradOst/CloudStream-3#602]
Request to the dev. Please make Sflix and Dopebox work. It has not been working properly both in the old and old version. Kindly look into it please.
![Screenshot_20220204-234244_CloudStream](https://user-images.githubusercontent.com/99042103/153063320-f361a252-d95b-4904-a62d-ed4e892fb429.jpg)

**Comment by Gthbacc** [comment]
Same problem here. +1

**Comment by Buddie911** [comment]
Same here, for almost two days now

**Comment by LagradOst** [comment]
We have looked into it many times, and tldr the site is fucked

**Comment by cutterchop** [comment]
Everyone that has this problem make sure you are on the beta release

https://github.com/LagradOst/CloudStream-3/releases/download/pre-release/app-prerelease.apk

**Comment by stojkovskistefan** [comment]
> > Everyone that has this problem make sure you are on the beta release it most probably will work
> > https://github.com/LagradOst/CloudStream-3/releases/download/pre-release/app-prerelease.apk
> 
> Im on the new pre release and it still says no links found or i get an error message after an ep plays for like 2 minutes

Same here.

**Comment by Maddyhf** [comment]
Sometimes Sflix works, sometimes it doesn't. just try opening and closing the app and clicking the link and it would work.

**Comment by Maddyhf** [comment]
https://user-images.githubusercontent.com/87609775/153258661-476b4884-ad37-45a7-a2fd-71c068339285.mp4

**Comment by Buddie911** [comment]
Lucky you, every time i try its just no links

**Comment by noah010** [comment]
> Lucky you, every time i try its just no links

Yeah same.
