### ISSUE TITLE
Cloudstream logo on home page

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#610]
U can Add Cloudstream logo on the top of the home page to promote your app

I have two design u can use it if u like these

![Cloudstream home page-01.png](https://user-images.githubusercontent.com/87866912/153247722-465a59ff-0bfd-4305-8133-3412ed14fac6.png)

![Cloudstream home page-03.png](https://user-images.githubusercontent.com/87866912/153247792-b923abdb-9aa5-4f1e-ab69-65538572ac51.png)

For Stable Release

![Cloudstream home page-02.png](https://user-images.githubusercontent.com/87866912/153247956-7e0f0035-a110-428a-b849-a28a3552d15a.png)

![Cloudstream home page-04.png](https://user-images.githubusercontent.com/87866912/153248007-eabb1d2c-8ddb-45f6-91c8-7977c1f5b550.png)

**Comment by LagradOst** [comment]
No, that feel kinda egocentric. (I was planning on having the mal/anilist account image there anyways)

**Comment by Light7654** [comment]
Ohh that's also cool
