### ISSUE TITLE
Logo Update

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#613]
I Really Like this app and wanna contribute a little so I made a logo designs for this app

Dev if you like these logo concepts then u can update

![Cloudstream-3-01.png](https://user-images.githubusercontent.com/87866912/153260333-4b9603c1-351d-40bc-b86f-1c8ae9a15f6a.png)

![Cloudstream-3-05.png](https://user-images.githubusercontent.com/87866912/153260403-944b3344-6df6-4e1a-9067-59f8a735edd1.png)

![Cloudstream-3-06.png](https://user-images.githubusercontent.com/87866912/153260451-1be009e5-f5a0-422e-8f7c-c9297f632a3e.png)

For Pre-release

![Cloudstream-3-04.png](https://user-images.githubusercontent.com/87866912/153260517-32c9e632-fc89-4f0d-aaa1-71e2ba175223.png)

![Cloudstream-3-02.png](https://user-images.githubusercontent.com/87866912/153261179-fff38b5a-6741-40f3-a498-455559ac2b23.png)

![Cloudstream-3-03.png](https://user-images.githubusercontent.com/87866912/153260586-3fcb0f62-35cb-453a-98c5-842e173d015f.png)

**Comment by LagradOst** [comment]
Downvoted 10-0, sorry but ppl dont like this design compared to the current.
