### ISSUE TITLE
WiWi Cinema 

### ISSUE THREAD

**Issue by karasuno05** [LagradOst/CloudStream-3#616]
Can you try to make servers like WiWi cinema app that doesn't have any server issue or anything but it's UI is pretty bad. Where as CloudStream have a better UI and if the this apps get serve like WiWi Cinema the app will be the best in category. So plz check this out. Thanks.

**Comment by LagradOst** [comment]
We dont host any of the content on this app. Do you know what it does to load links? Does it host the content or scrape from some website?

**Comment by Buddie911** [comment]
> We dont host any of the content on this app. Do you know what it does to load links? Does it host the content or scrape from some website?

It scrapes from lookmovie.io
