### ISSUE TITLE
I can't stream

### ISSUE THREAD

**Issue by Zeroo097** [LagradOst/CloudStream-3#624]
So I was streaming euphoria on Dopebox and had some network issues so I switched to 360p and after playing the episode like for 50 seconds it showed no links found then i used sflix for the same episode again in 360 and again after streaming the episode for 2 minutes it showed some http 404 connection error or something and no links were found in solarmovie

**Comment by Buddie911** [comment]
> So I was streaming euphoria on Dopebox and had some network issues so I switched to 360p and after playing the episode like for 50 seconds it showed no links found then i used sflix for the same episode again in 360 and again after streaming the episode for 2 minutes it showed some http 404 connection error or something and no links were found in solarmovie

Ongoing problem with sflix dude

**Comment by Buddie911** [comment]
> > Ongoing problem with sflix dude
> 
> What about dopebox and solarmovie

They're clones of sflix aka same servers so same problems

**Comment by cutterchop** [comment]
> > So I was streaming euphoria on Dopebox and had some network issues so I switched to 360p and after playing the episode like for 50 seconds it showed no links found then i used sflix for the same episode again in 360 and again after streaming the episode for 2 minutes it showed some http 404 connection error or something and no links were found in solarmovie
> 
> Ongoing problem with sflix dude


https://user-images.githubusercontent.com/31880937/153474261-0fe85208-f556-465e-aedb-06c024861dc8.mp4

**Comment by Buddie911** [comment]
Well its not working for me still....

**Comment by steamedham544** [comment]
Same here. Around 2 minutes in and it cycles through the sources till it says no links found. 

![Screenshot_20220210-222842_CloudStream Beta](https://user-images.githubusercontent.com/99104240/153507484-88560351-1f85-49c0-a16c-84c5ba3c3b97.png)
