### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#628]
Subtitles are not working in pre-release

https://user-images.githubusercontent.com/87866912/153571932-cce050dc-73eb-4995-9788-f3bd5bb80c9b.mp4

**Comment by KasukeLp23** [comment]
I have the same problem

**Comment by LagradOst** [comment]
STOP ASKING, it is currently being reworked

**Comment by LagradOst** [comment]
seek will fix it
