### ISSUE TITLE
Subtitle not showing / not downloading

### ISSUE THREAD

**Issue by yashash99** [LagradOst/CloudStream-3#641]
Subtitle not showing / not downloading not sure which.

Subtitle sources are showing in sources screens and I have selected English, but subtitle is not showing while playing.

**Comment by yashash99** [comment]
![Screenshot_20220212-195835_CloudStream Beta.jpg](https://user-images.githubusercontent.com/29854066/153715423-e78e521a-f9ee-46bd-a9ce-c45df1b0f5a1.jpg)

![Screenshot_20220212-195845_CloudStream Beta.jpg](https://user-images.githubusercontent.com/29854066/153715428-1d02733a-7cfc-44e5-b6c4-953883686648.jpg)

**Comment by LagradOst** [comment]
known issue in pre, seek once and it will show

**Comment by yashash99** [comment]
Hey. I have tried that. It didn't work me.
