### ISSUE TITLE
zoro external subtitle

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#643]
there is external subtitle in zoro site

![Screenshot (500)](https://user-images.githubusercontent.com/87866912/153716663-49a3ca1c-8ada-4d42-87a4-173ec249c26c.png)
e

but in app there is no external subtitle

![55aea90a-c6a5-44e5-9a59-d2d7b6cbc23c](https://user-images.githubusercontent.com/87866912/153717306-fb6a0a47-60ed-4a0b-82ac-a8bf961c8592.jpg)

**Comment by LagradOst** [comment]
fixed
