### ISSUE TITLE
smooth and fast transition in cs3 WHEN o_O

### ISSUE THREAD

**Issue by whillw** [LagradOst/CloudStream-3#654]

**Comment by LagradOst** [comment]
what?

**Comment by whillw** [comment]
> what?

I mean the transitions in cs3 isnt that up to you guys or...?

**Comment by whillw** [comment]
> what exactly do you mean with transitions? 

yh the apps transitions when u go like home to settings it moves smooth or fast like that

**Comment by LagradOst** [comment]
send example video

**Comment by Light7654** [comment]
Maybe he wanna say that the app is not smooth enough

**Comment by brahmkshatriya** [comment]
I think they mean animations when switching tabs
