### ISSUE TITLE
Different Subtitles Format

### ISSUE THREAD

**Issue by Yashmak620** [LagradOst/CloudStream-3#656]
Please allow app to accept ass,sup and other subtitles format because it is much more difficult to find srt file.Although Thanks so much for app

**Comment by LagradOst** [comment]
current supported formats are `MimeTypes.TEXT_VTT,
            MimeTypes.TEXT_SSA,
            MimeTypes.APPLICATION_TTML,
            MimeTypes.APPLICATION_MP4VTT,
            MimeTypes.APPLICATION_SUBRIP,` TEXT_SSA is .ass files so latest pre should support them, if not reopen and send an example .ass file
