### ISSUE TITLE
I think ass format does not support

### ISSUE THREAD

**Issue by Yashmak620** [LagradOst/CloudStream-3#657]
![Screenshot_2022-02-14-00-53-16-59](https://user-images.githubusercontent.com/90566456/153771257-e834bae0-93a1-48d5-91a8-d63418625a08.jpg)

**Comment by Yashmak620** [comment]
If you're going to add ass please, please also add sup format.

**Comment by Light7654** [comment]
No it supports, look

![Screenshot_2022-02-14-00-58-27-29.jpg](https://user-images.githubusercontent.com/87866912/153771527-2baf3629-88e4-44f9-a611-82abbef97b97.jpg)

**Comment by Yashmak620** [comment]
I think maybe because of your android version

**Comment by Yashmak620** [comment]
![Screenshot_2022-02-14-01-14-48-67](https://user-images.githubusercontent.com/90566456/153771981-2f2b1040-1746-454b-af76-11215796bac1.jpg)
