### ISSUE TITLE
Error 2004

### ISSUE THREAD

**Issue by Buddie911** [LagradOst/CloudStream-3#658]
The error problem is back again, even in the latest pre. It was working fine but now....

**Comment by Buddie911** [comment]
> The error problem is back again, even in the latest pre. It was working fine but now....

Never mind it works for me again

**Comment by xaviQ7** [comment]
How what did you do

**Comment by Buddie911** [comment]
Well i was watching this show first and that didn't work but i tried this other one and it worked for me. Trailers.to is the one not working for me now. I get error on that in nearly everything. But sflix, does.
