### ISSUE TITLE
No Links Found

### ISSUE THREAD

**Issue by Zeroo097** [LagradOst/CloudStream-3#659]
I Was streaming Euphoria Latest episode which came out yesterday and 3 Minutes into the episode sflix suddenly showed no links found and closed the player.Same problem with dopebox and Solarmovie as these have same server kinda thing I hope you fix this soon.

**Comment by LagradOst** [comment]
and you have checked the latest prerelease?

**Comment by Zeroo097** [comment]
> and you have checked the latest prerelease?

Yeah am using the latest pre-release

**Comment by Zeroo097** [comment]
Okay i tried in the lastest pre-release and It showed some http 404 bad connection error thing and then it moved to another sflix server and then another and in the last it showed no links found and closed.

**Comment by imxcr** [comment]
same problem, i'm watching the latest episode of euphoria and it just says error & no links found.
