### ISSUE TITLE
Few queries

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#664]
Is it possible to have gogoanime sub and dub animes at one catalogue

Also

When anilist/mal will integrate then will there be every movie catalogue for every site or only one catalogue for one movie

For example
![Screenshot_2022-02-15-23-01-20-73.jpg](https://user-images.githubusercontent.com/87866912/154116774-7342770a-0851-45a0-bd96-64ebde29ca25.jpg)

![Screenshot_2022-02-15-23-02-33-67.jpg](https://user-images.githubusercontent.com/87866912/154116984-d9212f3d-77ec-429b-82a2-6b17d547e064.jpg)

**Comment by LagradOst** [comment]
Idk, we will see what happends
