### ISSUE TITLE
source

### ISSUE THREAD

**Issue by laufeyss** [LagradOst/CloudStream-3#666]
is it okay if You guys Just take this off? It wasn't necessary Or... is it?

![Untitled272_20220216131900](https://user-images.githubusercontent.com/99605276/154201158-72781090-e684-456a-865e-838a18a93fb9.png)

**Comment by ITADORI-15** [comment]
And also can u place the lock option in the top right corner

**Comment by imxcr** [comment]
> And also can u place the lock option in the top right corner

no. i think it's better with that default one

**Comment by ITADORI-15** [comment]
Yeah maybe until it's in one corner

**Comment by LagradOst** [comment]
no 😔
