### ISSUE TITLE
window subtitles

### ISSUE THREAD

**Issue by whillw** [LagradOst/CloudStream-3#667]
aren't the subtitles with window supposed to look like this?

![Screenshot_2022-02-16-16-09-18-14_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/97724042/154222939-90839629-8e90-4f6a-a7ab-fe01c6e0fe67.jpg)

cs3
![IMG_20220216_210733](https://user-images.githubusercontent.com/97724042/154271057-5de126a6-56cb-4552-852c-c2942b4c5621.jpg)

**Comment by Light7654** [comment]
That First one is not subtitles window it's called subtitle background colour

**Comment by whillw** [comment]
> That First one is not subtitles window it's called subtitle background

It is window

this the background one, completely different

![Uploading Screenshot_2022-02-16-18-10-13-16_7a4090f09f6554852d748ee9fd6f40d3.jpg…]()

**Comment by whillw** [comment]
> That First one is not subtitles window it's called subtitle background

It is window

this the background one, completely different

![Screenshot_2022-02-16-18-10-13-16_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/97724042/154243390-2e36cd55-c389-4706-b5ca-9d3dc4f39106.jpg)

**Comment by Light7654** [comment]
> > That First one is not subtitles window it's called subtitle background
> 
> It is window
> 
> this the background one, completely different
> 
> ![Screenshot_2022-02-16-18-10-13-16_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/97724042/154243390-2e36cd55-c389-4706-b5ca-9d3dc4f39106.jpg)
> 

Ohh I just checked in app

My bad

**Comment by LagradOst** [comment]
i can probs fix

**Comment by whillw** [comment]
> i can probs fix

Tysm! waiting for it ^^

**Comment by whillw** [comment]
+ a lil request, is it ok if u guys make the subs corners look like this:
![IMG_20220216_232141](https://user-images.githubusercontent.com/97724042/154296584-c9971bf2-8920-4f32-8070-e255908995c6.jpg)


instead of this one
![IMG_20220216_232153](https://user-images.githubusercontent.com/97724042/154296634-e66c9523-35a1-49f8-8e5d-8cd365fb60a6.jpg)

**Comment by LagradOst** [comment]
> + a lil request, is it ok if u guys make the subs corners look like this:
> ![IMG_20220216_232141](https://user-images.githubusercontent.com/97724042/154296584-c9971bf2-8920-4f32-8070-e255908995c6.jpg)
> 
> 
> instead of this one
> ![IMG_20220216_232153](https://user-images.githubusercontent.com/97724042/154296634-e66c9523-35a1-49f8-8e5d-8cd365fb60a6.jpg)
> 
> Thank u sm ❤️

not possible

**Comment by LagradOst** [comment]
nope, exoplayer windowcolor is match parent in width. I cannot change it to wrap content

**Comment by LagradOst** [comment]
100dp vs wrap content. as you can see I can set it to a constant but not matching the subtitles
