### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by laufeyss** [LagradOst/CloudStream-3#669]
Custom font for Subtitles

**Comment by cutterchop** [comment]
> Custom font for Subtitles

Hmm while this isn't custom fonts it's a bit variety maybe u don't know of its located in
Settings > subtitles > fonts

![Screenshot_20220217-073658](https://user-images.githubusercontent.com/31880937/154419486-cce01b65-bffe-4b5b-af6b-4d7e590fce36.jpg)
