### ISSUE TITLE
For the subs

### ISSUE THREAD

**Issue by laufeyss** [LagradOst/CloudStream-3#673]
Ayo Guys is it possible or ok to make the subtitles shadows look like this? it's Just so Clean and fine Ty!
![Picsart_22-02-18_01-34-16-745](https://user-images.githubusercontent.com/99605276/154539357-165c76cd-a990-4285-9ce0-7ed9c49bf877.jpg)

cs3's
![IMG_20220218_014016](https://user-images.githubusercontent.com/99605276/154539412-80d2cfdd-5407-4064-a278-493e35c12afa.jpg)

**Comment by LagradOst** [comment]
The current settings is all that exoplayer provide

**Comment by laufeyss** [comment]
> The current settings is all that exoplayer provide

Wait what is exoplayer exactly? do U guys don't own yalls player or smth

**Comment by LagradOst** [comment]
https://github.com/google/ExoPlayer
this is what the player exposes for us to modify https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/CaptionStyleCompat.html

**Comment by laufeyss** [comment]
> https://github.com/google/ExoPlayer this is what the player exposes for us to modify https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/CaptionStyleCompat.html

Own player when 😔

**Comment by LagradOst** [comment]
@laufeyss not happening, exoplayer has 12 393 commits while cs3 has 800
