### ISSUE TITLE
Continue Watching Issue

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/CloudStream-3#674]
Hi, when you expand the list "Continue Watching' and you see the Thumbnails of all movies/TV Shows, unfortunately, nothing happens when you click on any thumbnail and we need to manually search that content. Ideally speaking, it should play the content from the same source where it had left. Can you please fix this.

**Comment by LagradOst** [comment]
Send video

**Comment by imurreflection** [comment]
Please see the video. Nothing happens when you click on any of the poster

https://user-images.githubusercontent.com/30263396/154612099-0ced659e-9b33-416a-844b-1c9b74f97f8f.mp4
