### ISSUE TITLE
Here's my suggestion

### ISSUE THREAD

**Issue by Bungeexgum** [LagradOst/CloudStream-3#680]
![IMG_20220219_163534](https://user-images.githubusercontent.com/88455631/154793657-d306ec04-3e50-446b-a24b-9f2f620a50f3.jpg)

![IMG_20220219_163559](https://user-images.githubusercontent.com/88455631/154793666-ac63d5ce-3e44-4a3e-b46f-54039b527655.jpg)

**Comment by LagradOst** [comment]
No, I switched to the current due to UI and UX, I wont change it to smth worse. If you really want it then fork the project
