### ISSUE TITLE
Pause/resume button

### ISSUE THREAD

**Issue by whillw** [LagradOst/CloudStream-3#682]
Is it okay or possible I say to take this shadow thing off when tapping on the pause or resume button on player? thanks 🤙
![Picsart_22-02-19_21-44-52-250](https://user-images.githubusercontent.com/97724042/154803453-ec7f7508-21e6-4336-aabe-675d509ba21a.jpg)

**Comment by whillw** [comment]
> Is it okay or possible I say to take this shadow thing off when tapping it on the pause or resume button on player? thanks 🤙 ![Picsart_22-02-19_21-44-52-250](https://user-images.githubusercontent.com/97724042/154803453-ec7f7508-21e6-4336-aabe-675d509ba21a.jpg)

**Comment by LagradOst** [comment]
What, why, no?

**Comment by whillw** [comment]
> What, why, no?

No? why, what

**Comment by LagradOst** [comment]
that is how the app shows that smth is highlighted

**Comment by whillw** [comment]
> that is how the app shows that smth is highlighted

Yes okay! so.. you say yes or no?

**Comment by LagradOst** [comment]
big no
