### ISSUE TITLE
Pause/Play button replaced with a circular progress bar when casting

### ISSUE THREAD

**Issue by steamedham544** [LagradOst/CloudStream-3#683]
Happens when opening the player while casting then going back. Closing the app fixes it. 

![Screenshot_20220220-003711_CloudStream Beta](https://user-images.githubusercontent.com/99104240/154823984-76bd5af7-417b-4107-9fbd-5fa2dd5e554c.png)

**Comment by LagradOst** [comment]
chromecast issue, cant fix
