### ISSUE TITLE
notch issue

### ISSUE THREAD

**Issue by shawalvai** [LagradOst/CloudStream-3#69]
in player Fullscreen mode,,player doesn't fill the notch...it looks annoying... please consider to fix this

**Comment by LagradOst** [comment]
Send image

**Comment by shawalvai** [comment]
![Screenshot_20210905-193821126](https://user-images.githubusercontent.com/87768126/132128931-eb411f37-989d-4584-a0da-c66393a15bb3.jpg)
#
@LagradOst
