### ISSUE TITLE
Some content are not playable

### ISSUE THREAD

**Issue by gadz91** [LagradOst/CloudStream-3#70]
Some movie/series content are not playable in the app but on the site it's available to play and watch.
I think the issue is the synchonizing of the source.
Many of the content are searchable but not playable.
Please fix these issue.
Thanks for this awesome app! ❤❤❤

**Comment by ArjixWasTaken** [comment]
If you want to get help then you need to give more details when asking for it.
What provider did you use and it could not play the episodes?
Link to an example episode that failed to play?
On what android version are you?

**Comment by gadz91** [comment]
Sorry, I'm wrong.
