### ISSUE TITLE
This one

### ISSUE THREAD

**Issue by laufeyss** [LagradOst/CloudStream-3#701]
When tapping an episode

![Picsart_22-02-22_22-54-53-025](https://user-images.githubusercontent.com/99605276/155158398-af08f9f6-c53d-464b-a38d-d0eb00d6866f.jpg)

**Comment by LagradOst** [comment]
what??

**Comment by glorymaster** [comment]
> When tapping an episode
> 
> ![Picsart_22-02-22_22-54-53-025](https://user-images.githubusercontent.com/99605276/155158398-af08f9f6-c53d-464b-a38d-d0eb00d6866f.jpg)

![Screenshot_20220224-003653](https://user-images.githubusercontent.com/71760685/155364359-047f45f4-808d-417b-9b54-dbe4a9fed347.jpg)
you're not satisfied with this yet?
