### ISSUE TITLE
zoro.to ignoring some results

### ISSUE THREAD

**Issue by ahnaf0014** [LagradOst/CloudStream-3#703]
Can't find  (not showing) a anime series from zoro.to CS source but I can find that show directly searching into the site through web browser. The anime is Monster (2004)

**Comment by LagradOst** [comment]
![Screenshot_20220223_121120_com.lagradost.cloudstream3.prerelease.jpg](https://user-images.githubusercontent.com/11805592/155308404-9260c21d-4e42-4d60-806b-562cc24d6a0f.jpg)

**Comment by LagradOst** [comment]
https://zoro.to/search?keyword=monster+2004

it uses the site for search

**Comment by ahnaf0014** [comment]
ok including year with title fixed my problem but in main site search this anime still appears by including only the title. try it I'm not wrong.It is a very small bug though.You can label this issue as low priority if you want.

**Comment by LagradOst** [comment]
This is a problem with the site, not the app. The app mirrors the site results

**Comment by LagradOst** [comment]
I legit cant fix it, ask the zoro devs instead
