### ISSUE TITLE
Some Content showing VPN required

### ISSUE THREAD

**Issue by mohdbilalquadri** [LagradOst/CloudStream-3#71]
When playing some of the content it shows that this source may require VPN to play correctly while the other content plays fine. The content that is showing this issue was playing fine before the latest update. I was trying to rewatch one of the episode and movie when i faced this issue. The source is same for all the movies and shows trailers.to still some play fine and some not
![Screenshot_20210905-134454_CloudStream](https://user-images.githubusercontent.com/59991516/132120305-d834d433-508e-44a7-9cc6-359762b16362.jpg)

**Comment by LagradOst** [comment]
Usa a vpn, I did not change the source between the updates
