### ISSUE TITLE
just my suggestion

### ISSUE THREAD

**Issue by imxcr** [LagradOst/CloudStream-3#713]
if u guys into it ^^
![Untitled284_20220225134357.png](https://user-images.githubusercontent.com/98096677/155660954-412aaeb4-4655-4777-9a32-f4ec6e8d2a94.png)

**Comment by glorymaster** [comment]
I think its hard to implement this, since the content of this app is provided by the sites not by cloudstream itself..

**Comment by imxcr** [comment]
> I think its hard to implement this in all available videos, since the content of this app is provided by the sites not by cloudstream itself.. please be contented on what is and what is. 

AGAIN, just my suggestion lol not complaining on anything at all 💀 and idk if it's possible or not. i'm sorry.

**Comment by LagradOst** [comment]
Somewhat related to https://github.com/LagradOst/CloudStream-3/issues/709 so I am closing this rn as I added episode title. The only problem with your suggestion is that I dont want to hide information about the video quality and mirror name.

**Comment by laufeyss** [comment]
> Somewhat related to #709 so I am closing this rn as I added episode title. The only problem with your suggestion is that I dont want to hide information about the video quality and mirror name.

But why? it looks good tho
