### ISSUE TITLE
Change lagbros cheese icon to this very good monke mmm

### ISSUE THREAD

**Issue by cutterchop** [LagradOst/CloudStream-3#716]
![IMG_20220226_112341](https://user-images.githubusercontent.com/31880937/155844801-2100f895-6af2-45be-b7b0-e36d94e52165.jpg)
![IMG_20220226_112324](https://user-images.githubusercontent.com/31880937/155844805-ab5e0eb4-3766-46a5-8ede-57f98311e52b.jpg)
Very important

**Comment by dm699** [comment]
What?
