### ISSUE TITLE
subs

### ISSUE THREAD

**Issue by imxcr** [LagradOst/CloudStream-3#717]
why are the subtitles window like this?
![Screenshot_2022-02-27-00-02-29-72_cfa2fd239c8cded9285432912d0e0818.jpg](https://user-images.githubusercontent.com/98096677/155850102-7fd57a52-8c00-4c86-a2a7-98137acff453.jpg)

in settings:
![IMG_20220227_000306.jpg](https://user-images.githubusercontent.com/98096677/155850112-c2212c66-b254-4222-9711-83464b393ce7.jpg)

**Comment by PAULeD16** [comment]
You can change that in options, subtitles, background color, set transparency to 100% any color. It will go away after.

**Comment by imxcr** [comment]
> You can change that in options, subtitles, background color, set transparency to 100% any color. It will go away after.

didn't work

**Comment by LagradOst** [comment]
exoplayer itself was wack
