### ISSUE TITLE
[Bug] No link founds in DopeBox/SFlix in latest beta

### ISSUE THREAD

**Issue by steamedham544** [LagradOst/CloudStream-3#720]
I'm using the latest beta and when trying to watch something on DopeBox, it says "no links found" after like 5 seconds. Working fine in the latest stable release

**Comment by LagradOst** [comment]
Known issue, they updated anti bot

**Comment by PAULeD16** [comment]
I tried next morning. It's working for me now (sflix)

**Comment by houdini101** [comment]
the anti-bot is still active. it will let you play for about 1-2 mins then it will disconnect (error 2004 will apear repeatedly then no links found.)

**Comment by mamanglodet** [comment]
Same here, it also happens on stable release. No link founds in DopeBox/Sflix

**Comment by PAULeD16** [comment]
I'm not getting any links on solarmovie, sflix, or dopebox. It was okay yesterday.

**Comment by imxcr** [comment]
> I'm not getting any links on solarmovie, sflix, or dopebox. It was okay yesterday. 

same

**Comment by imxcr** [comment]
same, until now
