### ISSUE TITLE
Adjust the Subtitle Elevation in Chromecast

### ISSUE THREAD

**Issue by noah010** [LagradOst/CloudStream-3#723]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- New feature

**Describe your request here** *(fill this up)*
- [x] It lets you adjust the subtitle elevation of the media when casting to tv with Chromecast.
- [x] The subtitle is too low.
- [x] So I can be happy^^

**Other related info**

**Comment by LagradOst** [comment]
Not possible, chromecast does not expose any option for changing elevation
