### ISSUE TITLE
Sever change 

### ISSUE THREAD

**Issue by Thorodinson1** [LagradOst/CloudStream-3#727]
In latest beta update there is new provider called bflix 
In that provider currently my cloud and streamtape is added .
But there is a server called vidstream it is fastest server. If it possible change to vidstream instead of streamtape.
Thank you 💗😊😊😊

**Comment by Buddie911** [comment]
They're using mycloud, it works just fine tho

**Comment by Thorodinson1** [comment]
Vidstream is faster compared to my cloud or up cloud

**Comment by Buddie911** [comment]
Well apparently it doesn't work on the up, one of the contributors said so

**Comment by Stormunblessed** [comment]
It's already added, try latest beta
#728
