### ISSUE TITLE
Provider language section On search bar

### ISSUE THREAD

**Issue by whillw** [LagradOst/CloudStream-3#729]
When selected other provider/s language than English, Is it okay to add its own section on search bar?

![Screenshot_2022-02-28-20-47-44-42](https://user-images.githubusercontent.com/97724042/155987629-ad501bb9-7a38-431a-960e-5fe6b10984eb.jpg)

![Picsart_22-02-28_20-55-46-824](https://user-images.githubusercontent.com/97724042/155987652-7d856c5f-68c8-48ce-8922-659395f2b293.jpg)

**Comment by LagradOst** [comment]
no, that would be bloat impo
