### ISSUE TITLE
Source error Response code : 500

### ISSUE THREAD

**Issue by devanshtyagi150** [LagradOst/CloudStream-3#73]
Every video I try to watch shows the same error. I even tried using a VPN, but it's not working :( 

![Screenshot_2021-09-05-20-22-36-103_com lagradost cloudstream3](https://user-images.githubusercontent.com/69811597/132131352-6575dec6-55a4-4313-9969-26dc66662bef.jpg)

**Comment by LagradOst** [comment]
Trailers.to is currently not working and is removed in pre-release

**Comment by devanshtyagi150** [comment]
i knew that site was too good :(, thanks anyways

**Comment by another-sapiens** [comment]
Hmm, the site is actually working for me

**Comment by another-sapiens** [comment]
@devanshtyagi150 Ah, just tried again, it seems to be a hit or miss depending on the movie itself. But most links I've tried seem to be working
