### ISSUE TITLE
Not able select Old provider in home screen of cloud stream 

### ISSUE THREAD

**Issue by Thorodinson1** [LagradOst/CloudStream-3#737]
The old provider [sflix.to] and dopebox is not available now after latest update. There is no option for selecting those providers please make any one of them back available. I installed old bulid before 4days (pre release) and both [sflix.to] and Dope box is playing fine. I have bookmarked some shows of [sflix.to] and it is also playing fine in latest update but no option to search through those providers.
Now in app there is [sflix.pro] thanks for that. But please make [sflix.to] available just as earlier times.

And thanks you for all developers of this app❤️❤️❤️

**Comment by imxcr** [comment]
sflix is shit tbh, it just says no links found and then it randomly gets fixed. and dw it's just temporary, they'll bring sflix & its clones back.
