### ISSUE TITLE
Solarmovies.to

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/CloudStream-3#738]
Hi, it appears that in beta releases, solarmovies.to is not there any more but it is available in stable release. Can you please include it in beta releases also unless you want to remove it.

**Comment by Thorodinson1** [comment]
Yes and also dopebox too

**Comment by tebuuu** [comment]
they removed it. the website is fucked as what i know.

**Comment by imurreflection** [comment]
The website is working just fine and in our addon also..I just checked it

**Comment by LagradOst** [comment]
It is temporarily restricted due to only working like 50% of the time. This means that you can still open it if you had smth bookmarked but you cant search for anything on it.

**Comment by imurreflection** [comment]
Hi Dev, there are no issues with Solarmovies..i just searched 'Matrix' on stable release 2.7.14 and it generated accurate results. Please see the screen below

**Comment by imurreflection** [comment]
![Screenshot_2022-03-03-10-23-52-67_a153ad7195ab131f51b38ebe0eab4033](https://user-images.githubusercontent.com/30263396/156499084-f37bee71-1ef7-4eeb-a220-9cc33292db59.jpg)

**Comment by LagradOst** [comment]
The problem is not search, but loading the links

**Comment by imurreflection** [comment]
Hi Dev, I am slightly confused as you earlier mentioned that there is an issue with the search. I checked again with other search and the links are loading fine. All we need is just one link to work and there is no issue with it. If there is any other reason or you wish to remove it entirely then I have nothing to say.
