### ISSUE TITLE
Bflix not working

### ISSUE THREAD

**Issue by Zeroo097** [LagradOst/CloudStream-3#743]
Bflix is not showing any results

**Screenshots or video**
![Screenshot_20220304-160012.jpg](https://user-images.githubusercontent.com/91909890/156746938-e2b192e9-a733-4c88-8de8-2f7551e541d4.jpg)![Screenshot_20220304-160006.jpg](https://user-images.githubusercontent.com/91909890/156746949-8d92870d-ff8e-472b-a139-70a26f717f15.jpg)

**Device (please complete the following information):**
 - Android Version: Android 11
 - App Version: v2.7.15
 - Provider: Bflix

**Additional context**
It shows cloudfare must have updated something like that.

**Comment by Stormunblessed** [comment]
You probably need a vpn
![Screenshot_20220304-054320_CloudStream_Beta.png](https://user-images.githubusercontent.com/86633626/156757631-993929f0-317a-4ebd-88a7-c19646106347.png)

![Screenshot_20220304-054331_CloudStream_Beta.png](https://user-images.githubusercontent.com/86633626/156757653-a2e1a10d-cd22-4d1b-bf46-fd97c1e0c56f.png)

**Comment by Zeroo097** [comment]
> You probably need a vpn
Yeah it's working with a VPN but idk yesterday it was working without VPN

**Comment by Zeroo097** [comment]
> You probably need a vpn
> !
Yeah it's working with a VPN but idk yesterday it was working without a VPN

**Comment by Zeroo097** [comment]
Yes it's working with a VPN but idk yesterday it was working without a VPN
