### ISSUE TITLE
subtitles shadow/window corners

### ISSUE THREAD

**Issue by sh1mv** [LagradOst/CloudStream-3#744]
are u guys able to edit subtitles? bc if yes i would like to ask if y'all can edit them corners

from this:
![IMG_20220304_190825](https://user-images.githubusercontent.com/100834418/156752892-88bd6ef0-5291-4640-8718-b9f93b2f44f4.jpg)

to this one:
![Screenshot_2022-03-04-18-18-17-90](https://user-images.githubusercontent.com/100834418/156752965-7363ce4e-77df-4c80-8323-1b3b75c024dd.jpg)

**Comment by LagradOst** [comment]
Exoplayer does not have that by default, create an issue https://github.com/google/ExoPlayer/issues instead
