### ISSUE TITLE
bflix

### ISSUE THREAD

**Issue by imxcr** [LagradOst/CloudStream-3#745]
how can i select full hd on cs3? it only shows minutes of episode (deleted scene) and there's no option on sources, i've tried all the servers on source list.

![Screenshot_2022-03-05-11-26-44-86.jpg](https://user-images.githubusercontent.com/98096677/156866078-e34e8ce1-e075-41ca-9867-067f05256322.jpg)

cs3
![Screenshot_2022-03-05-11-27-05-35_cfa2fd239c8cded9285432912d0e0818.jpg](https://user-images.githubusercontent.com/98096677/156866039-d42ce6a2-7503-4e14-9060-aa91aa929d97.jpg)

bflix's default
![Screenshot_2022-03-05-11-29-59-21.jpg](https://user-images.githubusercontent.com/98096677/156866057-209382e2-1804-4333-ad63-5ce01b96c922.jpg)

**Comment by Stormunblessed** [comment]
I'll fix this, didn't know that feature on bflix
