### ISSUE TITLE
App crashing in Firestick

### ISSUE THREAD

**Issue by akash-258** [LagradOst/CloudStream-3#747]
**To Reproduce**
Usually crashes when next episode automatically loads, sometimes happens when pausing and resuming videos, a lot less times it crashes when video is playing.
The crashes dont happen all time but happens during each session where i watch 2-3 episodes. The crashes were also present in last 2-3 pre releases as well. Dont know before that as I recently started using the app.

**Device :**

-    Android Version: dont know
-    Device Type: Fire TV Stick (2nd Gen)
-    Software Version: Fire OS 5.2.8.4 (672831820) latest till 5/3/22
-    Fire TV Home Version: 6350077.1
-    App Version: 2.7.16(beta)
-    Provider: All

**Comment by LagradOst** [comment]
Like the entire app crash or does it just quit the player?

**Comment by akash-258** [comment]
> Like the entire app crash or does it just quit the player? 

Yes the entire app crashes and sends me to firestick homescreen.

**Comment by LagradOst** [comment]
Ok, I think it is an out of memory error, can you check if you get it if you set video cache to None

**Comment by akash-258** [comment]
> Ok, I think it is an out of memory error, can you check if you get it if you set video cache to None

I think this might be the case, firestick already has very less free memory, and the app never crashes in the beginning. Will test tomorrow and update.

**Comment by ghfsa** [comment]
Same hardware.
I only watch one episode or movie, but 95% of the time it does crash after about 30mins or so duration. Also, after app crash, video resuming doesn't happen at the crashed time but somewhere much before. This has happened since long. Always thought it was the site issue.

I use the app still because that is some minor inconvenience for the overall seamlessness of the app. 

One more thing. I can't see 'Subtitle Offset' setting in the player. Can you @akash-258 ?

**Comment by akash-258** [comment]
> One more thing. I can't see 'Subtitle Offset' setting in the player. Can you @akash-258 ?

I agree the "sync subs" option is gone completely in TV layout, and is present if switched to Mobile layout. And tested this with multiple servers.

**Comment by akash-258** [comment]
> Ok, I think it is an out of memory error, can you check if you get it if you set video cache to None

I did set the video cache to 100 and then to none, but the app is still crashing.
Also noticed as mentioned by @ghfsa that it happens either after around 20-30 mins or if you try to play many episodes for 2-3 minutes duration.

**Comment by ghfsa** [comment]
Update of my experience after watching newer site SFlix pro for two days, single episode each time. Isn't exact but trying to show a probable pattern...

The "Toast Message" (2nd screenshot) may appear multiple times ( at the end of white line)

![img 1 5m  (2)](https://user-images.githubusercontent.com/83634560/157647964-3f11eee6-48e2-4603-9758-57a950dedd34.jpg)
![img 2 35m  (3)](https://user-images.githubusercontent.com/83634560/157647974-cbf4bbc3-b805-4442-8f96-ce04b1f19782.jpg)
![img 3 45m  (5)](https://user-images.githubusercontent.com/83634560/157647981-d4cc7358-2750-4a59-9385-000d078b51e3.jpg)

**Comment by LagradOst** [comment]
try latest pre

**Comment by akash-258** [comment]
> try latest pre

Tried the pre-release, the app seems stable now, was able to easily watch 5-8 episodes in a row (before it was 1-2) after which app started to lag, like UI became slow to respond, loading circle animation started stuttering then it crashed.

Will do more testing and update. Still, thanks for this update, I can really watch some episodes in tv now.

**Comment by ghfsa** [comment]
Thanks dev for the video fix as well as player button.
Even I want to know about **cache**. Does the _'auto'_ setting cache the video on FirestickGen2? 
Cause while watching online on sites, it seems to cache some parts ahead. For effeciency, should we keep some amount of _cache_ or is _auto_ just as efficient?

**Comment by LagradOst** [comment]
On any tv device I should keep it on auto. Auto just means that it will buffer 50s and not store anything on disk.
