### ISSUE TITLE
Infinate pages homepage

### ISSUE THREAD

**Issue by Gujjugaming2k** [LagradOst/CloudStream-3#760]
Please add Pagination features also
like page 1, page 2

**Comment by LagradOst** [comment]
wdym

**Comment by Gujjugaming2k** [comment]
See we can see only homepage data right?
example : Homepage site - https://gogoanime.film/
We need below contain also 
Next Page/Pagination - https://gogoanime.film/?page=2
Next Page/Pagination -https://gogoanime.film/?page=3

we can add some button function like next page
