### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by laufeyss** [LagradOst/CloudStream-3#762]
Hello! can U guys add an option to change subtitles edge type color?

![Screenshot_2022-03-07-19-46-17-90](https://user-images.githubusercontent.com/99605276/157028634-aea9546a-0920-4061-b5d2-a235c0c1afe4.jpg)

**Comment by LagradOst** [comment]
it is called outline color...

**Comment by laufeyss** [comment]
> it is called outline color...

But it's still white
![Screenshot_2022-03-16-20-46-43-60_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/99605276/158593243-6ae11d74-3075-4069-b07b-e3eada191ea0.jpg)
That edge type is depressed same as the raised one

**Comment by laufeyss** [comment]
Even i set it on outline color black

**Comment by LagradOst** [comment]
can be a problem if you are using an app to change apps to darkmode

**Comment by laufeyss** [comment]
> can be a problem if you are using an app to change apps to darkmode

I don't
