### ISSUE TITLE
Data Restore

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#764]
Cloudstream doesn't support Json file for restore data

![Screenshot_2022-03-08-19-05-53-75.jpg](https://user-images.githubusercontent.com/87866912/157249216-dec627f0-4613-4067-8f96-d9da396c494b.jpg)

**Comment by LagradOst** [comment]
wtf, it should

**Comment by Light7654** [comment]
Yeah but it doesn't
Please fix
