### ISSUE TITLE
Subtitle sync

### ISSUE THREAD

**Issue by karasuno05** [LagradOst/CloudStream-3#765]
The subtitles are not properly sync it mess up half way to the episode
Please fix this 
Other than great app appreciate your hard work dev

**Comment by LagradOst** [comment]
1. We dont host any subtitles
2. We dont host any videos
3. There exists an subtitle sync button to sync subtitles, you have to change the delay manually

**Comment by karasuno05** [comment]
I know but when i play it on website it works fine
