### ISSUE TITLE
Show not playing 

### ISSUE THREAD

**Issue by MidlajYH** [LagradOst/CloudStream-3#77]
![Screenshot_2021-09-06-14-06-01-392_com.lagradost.cloudstream3.jpg](https://user-images.githubusercontent.com/85442225/132186752-de0c6d5c-c580-4c11-945d-750d7b182874.jpg)

It says renderer error decoder failed: c2.android.aac.decoder

![Screenshot_2021-09-06-14-05-30-520_com.lagradost.cloudstream3.jpg](https://user-images.githubusercontent.com/85442225/132187056-ef2e6b1e-c395-4e9c-87cb-11d7efe36eed.jpg)

Device: Poco X3 Pro
Android Version: 11

It happened when I played 1st episode, I tried VPN too.

**Comment by ArjixWasTaken** [comment]
As the error suggests, it fails to decode the audio stream.
So uhh, this is either an error by exoplayer, or your device is missing some codecs.
