### ISSUE TITLE
MyAnimeList tracking for anime

### ISSUE THREAD

**Issue by SaqinNoor** [LagradOst/CloudStream-3#770]
- New feature

Add MyAnimeList tracking so that you can have real-time tracking. It will update the episode count if you finish an episode, and finish the whole series if you watch all episodes. CloudStream will check the date of the day you finished the series, and will add it as the finish date in MyAnimelist. Same can also be applied to the start date. It removes the burden of having to go to myanimelist.net and change the episode count or mark it as finished. You can take the implementation and idea from a similar app to cloudstream named Aniyomi which also has MyAnimeList tracking support. Aniyomi is also open source so you can see the code as to how the tracking works.

**Comment by LagradOst** [comment]
duplicate feature request, that has been requested 1000x before
