### ISSUE TITLE
100% Custom subtitle font

### ISSUE THREAD

**Issue by sh1mv** [LagradOst/CloudStream-3#771]
the ability to add/remove custom subtitle fonts. at the moment, there is only a select few you can choose from and it would be cooler to add any font we desire. thank you for the hardwork!

**Comment by Fireboy6** [comment]
> the ability to add/remove custom subtitle fonts. at the moment, there is only a select few you can choose from and it would be cooler to add any font we desire. thank you for the hardwork!

There's Netflix subtitle font isn't that enough?

**Comment by whillw** [comment]
> > the ability to add/remove custom subtitle fonts. at the moment, there is only a select few you can choose from and it would be cooler to add any font we desire. thank you for the hardwork!
> 
> There's Netflix subtitle font isn't that enough?

Read his/her request again

**Comment by laufeyss** [comment]
> > the ability to add/remove custom subtitle fonts. at the moment, there is only a select few you can choose from and it would be cooler to add any font we desire. thank you for the hardwork!
> 
> There's Netflix subtitle font isn't that enough?

Bro... Why would they request that if those few Fonts are enough? common sense 💀

**Comment by Blatzar** [comment]
Closing as this was added some time ago :+1:
