### ISSUE TITLE
Auto quality

### ISSUE THREAD

**Issue by tebuuu** [LagradOst/CloudStream-3#775]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- New feature

**Describe your request here** *(fill this up)*
- [x] So can u add auto quality in preferred video quality? It would be very useful to me

**Other related info**

**Comment by LagradOst** [comment]
You dont know how cs3 works do you?

**Comment by tebuuu** [comment]
> You dont know how cs3 works do you?

Lmao im just asking. Why mad
