### ISSUE TITLE
browse/search by category

### ISSUE THREAD

**Issue by imxcr** [LagradOst/CloudStream-3#785]
ㅤ

**Comment by whillw** [comment]
Or like the saikou
![Screenshot_2022-03-13-16-56-56-86_f4add486f0ca06883ca4fa789e77e31e](https://user-images.githubusercontent.com/97724042/158052411-7ca83323-bae3-4754-98d4-9ab9554823d8.jpg)
![Screenshot_2022-03-13-16-57-02-81](https://user-images.githubusercontent.com/97724042/158052417-64185b51-3a04-4e28-b00c-ffde56a3bcba.jpg)

**Comment by whillw** [comment]
Or like the saikou
![Screenshot_2022-03-13-16-57-02-81](https://user-images.githubusercontent.com/97724042/158052474-90b23eed-e36c-427c-87f3-af6e1b9ccfd6.jpg)
