### ISSUE TITLE
Improve vmovee.watch

### ISSUE THREAD

**Issue by krrishkap** [LagradOst/CloudStream-3#792]
Hey can you please make vmovee.watch fetch for series amd tv shows too it works for movies but it doesnt fetch tv shows also this site supports 720p and 1080p quality but in the app it just fetches the 480p source

**Comment by krrishkap** [comment]
> I tried to, but dood extractor doesn't work and they scrape from 2embed, so I didn't continue

I tried searching up a series "rocket boys" with 2embed in the app but it didn't work tho it works on vmovee.watch so are you sure they scrape from 2embed?

**Comment by Stormunblessed** [comment]
> > I tried to, but dood extractor doesn't work and they scrape from 2embed, so I didn't continue
> 
> I tried searching up a series "rocket boys" with 2embed in the app but it didn't work tho it works on vmovee.watch so are you sure they scrape from 2embed?

That's because 2embed uses tmdb api to search, and yes they scrape from 2embed
![notitle](https://user-images.githubusercontent.com/86633626/158674454-55a56b52-1290-4fad-8d13-5ed26990fc2b.png)

**Comment by krrishkap** [comment]
> > > I tried to, but dood extractor doesn't work and they scrape from 2embed, so I didn't continue
> > 
> > 
> > I tried searching up a series "rocket boys" with 2embed in the app but it didn't work tho it works on vmovee.watch so are you sure they scrape from 2embed?
> 
> That's because 2embed uses tmdb api to search, and yes they scrape from 2embed ![notitle](https://user-images.githubusercontent.com/86633626/158674454-55a56b52-1290-4fad-8d13-5ed26990fc2b.png)

Ohk so can you make dood extractor work or it wont work?

**Comment by krrishkap** [comment]
@Stormunblessed any updates on this?

**Comment by Stormunblessed** [comment]
> @Stormunblessed any updates on this?

I won't continue trying, dood server there needs captcha

**Comment by krrishkap** [comment]
> > @Stormunblessed any updates on this?
> 
> I won't continue trying, dood server there needs captcha

Ohhk no problem
