### ISSUE TITLE
Crash after loading subtitles

### ISSUE THREAD

**Issue by hogus7** [LagradOst/CloudStream-3#795]
Whenever I load subtitles from file, the app starts to work slow and after syncing the subtitles few times it crashes. I'm on android 11 if it helps.

**Comment by LagradOst** [comment]
On latest prerelease and video cache set to None?

**Comment by hogus7** [comment]
On the last few versions of prerelase and i have video cache set to 400MB

**Comment by LagradOst** [comment]
try to set it to None and see if it still crashes

**Comment by hogus7** [comment]
Okay, after the change it seems to be working smooth. So I think that was caused because of the video cache. Thanks.
