### ISSUE TITLE
[providers] Some sites

### ISSUE THREAD

**Issue by OshekharO** [LagradOst/CloudStream-3#796]
Here are some sites i managed to find. Feel free to cross off sites that are not feasible to implement.

### Animes:

- [ ] https://anime-world.in
- [ ] https://lmanime.com
- [ ] https://animexin.xyz
- [ ] https://123animes.ru
- [ ] https://animenana.com
- [ ] https://animefox.sbs
- [ ] https://animeonsen.xyz
- [ ] https://11anime.fr
- [ ] https://www2.kickassanime.ro
- [ ] https://kimcartoon.li
- [ ] https://animeflick.net
- [ ] https://www.animeworld.tv

### Movies & Series:

- [ ] https://ecinema.ml
- [ ] https://moviesee.live
- [ ] https://turkish123.com
- [ ] https://www.privatehd.xyz
- [ ] https://shoow.in
- [ ] https://movie.squeezebox.dev
- [ ] https://cmovies.online
- [ ] https://prettyflix.gq
- [ ] http://www.streamlord.com
- [ ] https://theflix.to

**Comment by Thorodinson1** [comment]
https://theflix.to It think it is possible to implement because it has video player as in chrome browser.

![Screenshot_2022-03-16-08-04-24-324_com brave browser](https://user-images.githubusercontent.com/95184073/158505342-494ce44f-e590-4269-ace3-9f774ba3cad6.png)

**Comment by OshekharO** [comment]
@Thorodinson1 almost all the sites I have suggested have webplayer.

**Comment by LagradOst** [comment]
#24

**Comment by OshekharO** [comment]
> #24

Sir it's not duplicate all the website which i have mentioned are different.

**Comment by LagradOst** [comment]
I just dont want ppl bloating issues with providers, post it in issue 24
