### ISSUE TITLE
Themes & ASIAN MOVIES/SERIES

### ISSUE THREAD

**Issue by gadz91** [LagradOst/CloudStream-3#8]
Congrats to this kind of app!

Hope to have light/dark themes.

I wan't also to request to have asian movies/series like korean, chinese, filipino, thai, taiwan, indian, etc..

Sites like dramacool & 2213films.

**Comment by LagradOst** [comment]
No non-english based sources is planned atm. Themes are something that is planned tho

**Comment by Jacekun** [comment]
dramacool looks alot like watchasian. Anyways, dramacool seems to have more server so I'd probably add it at a later date.
