### ISSUE TITLE
Subtitles size

### ISSUE THREAD

**Issue by laufeyss** [LagradOst/CloudStream-3#805]
Possible to make subtitles font size count to 1-2-3? bc when i set it to 19 it's too small and when i set to 21 it's too big : / pls fix thank U
![Screenshot_2022-03-17-16-30-25-90](https://user-images.githubusercontent.com/99605276/158769004-cdace737-d8f6-4b41-9de7-43448005975f.jpg)

**Comment by LagradOst** [comment]
bruh

**Comment by laufeyss** [comment]
Nun changed 😔

**Comment by laufeyss** [comment]
> bruh

Nun changed 😔

**Comment by laufeyss** [comment]
It is now. Tysm!!
