### ISSUE TITLE
[Feature Request] Add a "Show More" button for some anime websites. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [LagradOst/CloudStream-3#806]
**Guidelines:**
- [ ] This is Not a duplicate Issue
- [x] This is not a request to add a website.

**Choose one of the following:**
- [x] New feature

**Adding "Show More" Button when scrolling through anime** 
- [x] When Clicking the "Show More" you get more anime from the site you like to stream the anime on. 
- [x] It Solves it from stopping at the end of the list so that you can keep scrolling for a good anime. 
- [x] So that the user does not have to switch sites all the time and can explore new anime that they could be interested to. 

**Other related info**
I honestly love this app and it was way better then AnimeGlare or ect. Having a "Show More" button would be really great instead of seeing the end of the list so that the list can go on. 

![image](https://user-images.githubusercontent.com/62456796/158900734-80f628d5-41fc-4937-b1b3-13c7285bef0b.png)

**Comment by Goldenfreddy0703** [comment]
Wait where is the duplicate, i was trying to find similar post for it lol 😂

**Comment by LagradOst** [comment]
Ye, kinda hard to know w 130 issues, https://github.com/LagradOst/CloudStream-3/issues/760

**Comment by Goldenfreddy0703** [comment]
Oh ok great, thanks for letting me know. 
Would you like me to close this issue sense it's a duplicate?

**Comment by Goldenfreddy0703** [comment]
Hey sorry for bothering but I just noticed this was close today. Were you guys able to add more pages or a "show more" button?

**Comment by LagradOst** [comment]
@Goldenfreddy0703 check the prerelease

**Comment by LagradOst** [comment]
some providers have it, but not all support it

**Comment by Goldenfreddy0703** [comment]
Ahhh that might explain it. Ok I'm on the beta or prerelease and I thought it was not added. Thank you
