### ISSUE TITLE
[bug] Zoro

### ISSUE THREAD

**Issue by whillw** [LagradOst/CloudStream-3#809]
Zoro always giving errors like this and still loads but after a minutes it gives errors again
![IMG_20220318_231607](https://user-images.githubusercontent.com/97724042/159030525-b84a6eda-6f6d-4e5e-9b58-3c572de67b55.jpg)

**Comment by AbeieDhPensi** [comment]
Same as me.

**Comment by Nebula6531** [comment]
Known issue Zoro has new anti scraping so I would recommend using other sources for now since the devs are busy
