### ISSUE TITLE
<Bug><Zoro>

### ISSUE THREAD

**Issue by 9MoIssam9** [LagradOst/CloudStream-3#810]
-Device: Samsung M51
 - App Version: v2.7.14
 - Provider: zoro.to
 -Android: 11

Zoro on the pervious stable version[2.7.14] is better for example there isn't that Remote error and subtitles can be downloaded but  none of this is working on the new stable version[2.8.15] and prerelease 

Remote Error
![Screenshot_20220318-194249_CloudStream Beta.png](https://user-images.githubusercontent.com/98220178/159045879-d14dbca6-1db4-44e2-b53d-634ea1be02f1.png)

**Comment by Nebula6531** [comment]
Known issue Zoro has new anti scraping so I would recommend using other sources for now since the devs are busy
