### ISSUE TITLE
[Bug] Subtitles aren't loaded automatically

### ISSUE THREAD

**Issue by z0xrv** [LagradOst/CloudStream-3#811]
**Guidelines:**
- [x] It **is not** a duplicate issue.

**To Reproduce**
1. Go to any movie or series(i tried with fmovies.to)
2. Download the episode
3. Try watch it after it's downloaded
4. Click on sources you'll realize the subs arent loaded but they're downloaded with the video

**Expected behavior**
The downloaded subs should automatically appear on sources with out the need to load the file manually

**Device (please complete the following information):**
 - Android Version: Android 7.0
 - App Version: v2.8.16 beta

**Comment by LagradOst** [comment]
Does it have many subtitles to choose from or just 1?

**Comment by LagradOst** [comment]
It works for me

**Comment by z0xrv** [comment]
> It works for me, unable to replicate with 1 or more download langues.

Appearantly itcs working with the version 2.8.14
