### ISSUE TITLE
SW Decoder for video playback 

### ISSUE THREAD

**Issue by hasseltuff** [LagradOst/CloudStream-3#813]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*
- [x] How it works.
- [x] Issues it solves.
- [x] Why it is needed.

**Other related info**

**Comment by LagradOst** [comment]
wdym

**Comment by hasseltuff** [comment]
When playing a video on any video in player like MX Player,the video is
usually encoded with Hardware Decoder(HW)but in MX Player,you can switch to
Software Decoder (SW) which uses cpu instead of gpu and improves the video
quality.

The reason I requested this is that I have a redmi note 10s ,but there's an
issue with the display. The phone automatically overshapens videos and they
look oversaturated and almost impossible to watch. But whenever I switch to
SW Decoder on MX Player,it solves the problem totally. The video looks way
better! So can u plz add it plz?

**Comment by LagradOst** [comment]
exoplayer does not provide that option afaik

**Comment by hasseltuff** [comment]
*edited message from 11:10 PM:*

When playing a video on any video  player like MX Player,the video is
usually encoded with Hardware Decoder by default(HW)but in MX Player,you
can switch to Software Decoder (SW) which uses cpu instead of gpu and
improves the video quality.

The reason I requested this is that I have a redmi note 10s ,but there's an
issue with the display. The phone automatically overshapens videos and they
look oversaturated and almost impossible to watch. But whenever I switch to
SW Decoder on MX Player,it solves the problem totally. The video looks way
better! So it would be much appreciated if you could add that feature

**Comment by hasseltuff** [comment]
Is that your in built player?

**Comment by hasseltuff** [comment]
*edited message from 11:30 PM:*

Is that your in-built player?

**Comment by LagradOst** [comment]
yes, cs3 uses exoplayer

**Comment by hasseltuff** [comment]
So there's no way you can add a feature like that?

**Comment by LagradOst** [comment]
no, afaik
