### ISSUE TITLE
Some 1080 links don't really show 1080 video 

### ISSUE THREAD

**Issue by hasseltuff** [LagradOst/CloudStream-3#814]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*
- [x] How it works.
- [x] Issues it solves.
- [x] Why it is needed.

**Other related info**

**Comment by hasseltuff** [comment]
Plz provide better sites

**Comment by hasseltuff** [comment]
Plz provide better streaming links

**Comment by LagradOst** [comment]
That is a fault in the hosting sites, not cs3

**Comment by hasseltuff** [comment]
Tnx
