### ISSUE TITLE
Dub non-English TV shows 

### ISSUE THREAD

**Issue by hasseltuff** [LagradOst/CloudStream-3#815]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*
- [x] How it works.
- [x] Issues it solves.
- [x] Why it is needed.

**Other related info**

**Comment by hasseltuff** [comment]
Plz Dub non-English TV shows like Control Z

**Comment by LagradOst** [comment]
check out #24
