### ISSUE TITLE
I hope I can close cc subtitles manually.

### ISSUE THREAD

**Issue by shanyan-wcx** [LagradOst/CloudStream-3#816]
**Choose one of the following:**
UX enhancement

**Describe your request here** *(fill this up)*
I found that the subtitles in Animation videos from websites such as 9anime are CC subtitles, but they can't be closed in cloudstream. When I try to use other subtitles, these embedded subtitles are uncomfortable. I hope they can be turned off manually and let me see a clean animation video without subtitles in other languages.

**Other related info**

**Comment by Stormunblessed** [comment]
9anime has subtitles hardcoded, they can't turn them off, only provider that has subtitles that can be turned off is Zoro, but it's currently broken, If you encounter another anime site that has soft subs, you can request it to be added

**Comment by LagradOst** [comment]
All subtiltles that are not burned into the video can be disabled or replaced with your own. If they are burned, then there is nothing you or I can do about it, switch souce.

**Comment by LagradOst** [comment]
fyi it looks like 9anime burns it subs

**Comment by shanyan-wcx** [comment]
> fyi it looks like 9anime burns it subs

I checked it again, in https://9anime.vc , the subtitles were not burned. And in https://9anime.st , the subtitles were burned. The two websites look almost the same. I don't know what their relationship is.

**Comment by Stormunblessed** [comment]
Check 9anime.me for offical 9anime domains, 9anime.vc is a Zoro.to clone, 9anime.st is a gogoscraper and scrapes other sites too

**Comment by LagradOst** [comment]
> > fyi it looks like 9anime burns it subs
> 
> I checked it again, in https://9anime.vc , the subtitles were not burned. And in https://9anime.st , the subtitles were burned. The two websites look almost the same. I don't know what their relationship is.

we use 9anime.center
