### ISSUE TITLE
Soft embeded subtitles 

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#817]
In 9 anime website it has soft embeded subtitles.

![Screenshot_2022-03-19-16-07-26-74.jpg](https://user-images.githubusercontent.com/87866912/159117786-b05be9e7-b7ad-4a34-9267-b804e6eb54cc.jpg)

But in the app it has hardcode embedded subtitles.why is that

![Screenshot_2022-03-19-16-08-30-25.jpg](https://user-images.githubusercontent.com/87866912/159117793-dd362978-0030-4c12-829b-6c6314f8eaf3.jpg)

![Screenshot_2022-03-19-16-08-36-94.jpg](https://user-images.githubusercontent.com/87866912/159117802-67696999-fb16-40c2-9ba0-8130f9d713e3.jpg)

**Comment by LagradOst** [comment]
nope, cs3 uses 9anime.center https://9anime.center/watch/attack-on-titan.kww/ep-1

**Comment by Stormunblessed** [comment]
Check 9anime.me for official sites of 9anime, .vc is a Zoro.to clone

**Comment by Light7654** [comment]
> nope, cs3 uses 9anime.center https://9anime.center/watch/attack-on-titan.kww/ep-1

Ohhh
