### ISSUE TITLE
Faster download,choosing server

### ISSUE THREAD

**Issue by Dman-1000** [LagradOst/CloudStream-3#820]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
 -New feature
- Other

**Describe your request here** *(fill this up)*
- [x] Needs to download faster. Downloads are slow. Also needs a server select option and resolution option.
- [x] needs an option to select from which server the anime has to download especially in case like 9anime and at which resolution.
- [x] makes downloading something a better experience compared to other apps available like 1dm or idm.

**Other related info**

**Comment by Dman-1000** [comment]
Fix the download speed so it goes faster than 256 kbps whereas i can download 10 files with more than 1mbps

**Comment by dangB99** [comment]
I second this. You cant even select resolution,seriously 400mb for a 24min episode! No way in hell.
For now i'll stick with chia-anime.cc, atleast till i get somewhat good at android dev to fork en mod it.

**Comment by odnar-dev** [comment]
Tap and hold on the episode or movies you want to download and a bunch of options will appear just tap on download mirror and choose your preferred download quality

**Comment by LagradOst** [comment]
Hold to select mirror 😐
