### ISSUE TITLE
Downloads keep repeating 

### ISSUE THREAD

**Issue by hasseltuff** [LagradOst/CloudStream-3#821]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**

**Expected behavior**

**Screenshots or video**

**Device (please complete the following information):**
 - Android Version: [e.g. Android 11 API 30, Android TV] 
 - App Version: [e.g. v2.7.14]
 - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]

**Additional context**

**Comment by hasseltuff** [comment]
My downloads just keep repeating and don't end up getting downloaded completed

**Comment by LagradOst** [comment]
Fill out the form.
