### ISSUE TITLE
Homescreen should be like this 

### ISSUE THREAD

**Issue by Yeaboi567** [LagradOst/CloudStream-3#83]
![Screenshot_20210906-191637](https://user-images.githubusercontent.com/86415683/132225296-d4739cd7-2395-41b3-a680-fe87d4e0a9a2.png)
There needs to be 
Anime         Movies         TV shows

**Comment by ArjixWasTaken** [comment]
@LagradOst maybe make the random option to take different HomePageList's from different providers and put them in the same page?

**Comment by joybavisi** [comment]
> ![Screenshot_20210906-191637](https://user-images.githubusercontent.com/86415683/132225296-d4739cd7-2395-41b3-a680-fe87d4e0a9a2.png)
> There needs to be
> Anime Movies TV shows

Which app?
