### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by whillw** [LagradOst/CloudStream-3#830]
Please bring this option back if possible bc i installed cs3 on my other phone and I can't control the brightness thank youu

![Screenshot_2022-03-20-22-24-53-34](https://user-images.githubusercontent.com/97724042/159167259-fa1b289b-3e63-404f-ab2a-0731d7831ece.jpg)

**Comment by whillw** [comment]
That's old version btw ^^

**Comment by LagradOst** [comment]
Allow cs3 to change system settings that might fix it. I have no plans atm to bring that feature back.

**Comment by whillw** [comment]
> Allow cs3 to change system settings that might fix it. I have no plans atm to bring that feature back.

Wait where or how? in settings

**Comment by LagradOst** [comment]
In your phone settings, goto cs3 and allow it to change system settings.
