### ISSUE TITLE
Bookmark issue

### ISSUE THREAD

**Issue by tallo3646** [LagradOst/CloudStream-3#831]
I can't view all the shows in my bookmark on android TV .. you have to keep scrolling right. 

Please fix it.

**Comment by LagradOst** [comment]
wdym

**Comment by tallo3646** [comment]
Like when you click on the watching list you have, you can scroll down for a couple of shows, but then it stops you can't scroll down anymore.

I hope this is clear

**Comment by LagradOst** [comment]
ohhhh

**Comment by tallo3646** [comment]
So how can this be fixed?

**Comment by LagradOst** [comment]
it should be fixed in latest pre if I understood it correctly
