### ISSUE TITLE
HD, CAM, or TS indicator

### ISSUE THREAD

**Issue by houdini101** [LagradOst/CloudStream-3#835]
- [x] It **is not** a duplicate issue.
- UI/UX enhancement

Some sites, like sflix.pro, has an indicator if the movie is in HD copy or CAM or TS copy. It would be great to know if a movie is in HD copy or not before playing it.

**Comment by Fireboy6** [comment]
> * [x]  It **is not** a duplicate issue.
> * UI/UX enhancement
> 
> Some sites, like sflix.pro, has an indicator if the movie is in HD copy or CAM or TS copy. It would be great to know if a movie is in HD copy or not before playing it.

I hope it will not add
