### ISSUE TITLE
Disable/Remove/Off Subtitles

### ISSUE THREAD

**Issue by Gujjugaming2k** [LagradOst/CloudStream-3#839]
Add option like Disable/Remove/Off Subtitles under player or under setting tab

**Comment by Fireboy6** [comment]
> Add option like Disable/Remove/Off Subtitles under player or under setting tab

There's already an option for that

**Comment by Gujjugaming2k** [comment]
PLEASE LET ME KNOW WHERE I CAN FIND THIS ?

**Comment by LagradOst** [comment]
The source button in videoplayer

**Comment by LagradOst** [comment]
Of you want to show subtitles, then check out subtitle settings
