### ISSUE TITLE
Plz replace delete icon on downloaded videos with something more attractive. 

### ISSUE THREAD

**Issue by hasseltuff** [LagradOst/CloudStream-3#843]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*
- [ ] How it works.
- [ ] Issues it solves.
- [ ] Why it is needed.

**Other related info**

**Comment by LagradOst** [comment]
provide an image or svg
