### ISSUE TITLE
No links found 

### ISSUE THREAD

**Issue by Buddie911** [LagradOst/CloudStream-3#849]
Whenever i play something on theflix to, and i load subtitles, it plays for a few seconds then says no links found

**Comment by LagradOst** [comment]
Unable to replicate. Is it the subtitles that are causing the problem or the video?

**Comment by LagradOst** [comment]
If you can play fine without the subtitles, then send the subtitle file so I can inspect it

**Comment by Buddie911** [comment]
> If you can play fine without the subtitles, then send the subtitle file so I can inspect it

Actually now it just says no links found. It just doesn't play anything on that provider

**Comment by Buddie911** [comment]
Hmm yeah, one minute it works and then its no links found
