### ISSUE TITLE
Subtitles edge type

### ISSUE THREAD

**Issue by whillw** [LagradOst/CloudStream-3#856]
Depressed edge type is color white even it's set on black outline color
![Screenshot_2022-03-23-14-52-27-33](https://user-images.githubusercontent.com/97724042/159641376-7544f762-1f4f-44ea-8bec-1b3682c4f6c9.jpg)
![Screenshot_2022-03-23-14-55-18-37](https://user-images.githubusercontent.com/97724042/159641395-15a65d13-5b1e-46a0-826b-2b71c87875e4.jpg)
![Screenshot_2022-03-23-14-54-58-69_f1e7df207bc5904dcb73811d44b775db](https://user-images.githubusercontent.com/97724042/159641418-16e68b54-4ccc-4bb8-b72e-1ccbd25c07c1.jpg)

**Comment by whillw** [comment]
And the raised one

**Comment by LagradOst** [comment]
Exo is wack.

**Comment by whillw** [comment]
> Exo is wack.

Is there any way to fix?? please fix : //
