### ISSUE TITLE
load font from external folder

### ISSUE THREAD

**Issue by shtvh** [LagradOst/CloudStream-3#864]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*
- [x] How it works.
- [x] Issues it solves.
- [x] Why it is needed.

**Other related info**

**Comment by shtvh** [comment]
IDK if duplicate or nah

**Comment by imxcr** [comment]
> IDK if duplicate or nah

it is duplicate

**Comment by shtvh** [comment]
thank you

**Comment by shtvh** [comment]
> > IDK if duplicate or nah
> 
> it is duplicate

thank you.
