### ISSUE TITLE
10 sec-forward area

### ISSUE THREAD

**Issue by Light7654** [LagradOst/CloudStream-3#865]
Can u do make it like this

![Photo.jpg](https://user-images.githubusercontent.com/87866912/160246479-466b6a9b-77df-4d45-86d4-1fa52b5e5122.jpg)

Instead of this

![photo 2.jpg](https://user-images.githubusercontent.com/87866912/160246489-4328bf55-290e-4ced-a365-7f451494ea2c.jpg)

**Comment by LagradOst** [comment]
no
