### ISSUE TITLE
Update url

### ISSUE THREAD

**Issue by melbasuonyy** [LagradOst/CloudStream-3#873]
Hello

I just want you to change egy.best url as its not working in most countries 
From: egy.best
To : https://egybest.org/

From: mycima.tv 
To : https://mycima.bid:2096/ 

This will be grateful and amazing if you could it works in all countries and i have tried with VPN built in but not working 

Thanks

**Comment by cutterchop** [comment]
> Hello
> 
> I just want you to change egy.best url as its not working in most countries From: egy.best To : https://egybest.org/
> 
> From: mycima.tv To : https://mycima.bid:2096/
> 
> This will be grateful and amazing if you could it works in all countries and i have tried with VPN built in but not working
> 
> Thanks

The my Cima link you sent has a cloud flare

The egybest link you sent prob isn't the main website, every egybest film tells you to go to egy.best
![IMG_20220330_183549](https://user-images.githubusercontent.com/31880937/160896817-e5005934-39ec-4f14-a656-529dbab45ef0.jpg)
