### ISSUE TITLE
[TV] Restore Data From Backup, no filepicker

### ISSUE THREAD

**Issue by Goldenfreddy0703** [LagradOst/CloudStream-3#893]
**Guidelines:**
- [x] It **is not** a duplicate issue.

**To Reproduce**
1. Find a google tv capable device like google chromecast.
2. Download multiple file explorers such as: FX, File Manager, X-plore, ect
3. Download the CloudStream-3 apk and open it.
4. Go to settings and click "Restore data from backup"
5. See error message "you don't have an app that can do this"

**Expected behavior**
To ask you which file explorer you would like to use. 

**Screenshots or video**
Cannot not produce sense its on my tv. 

**Device (please complete the following information):**
 - Android Version: Android TV OS Version 10
 - App Version: 2.8.16
 - Provider: No Provider

**Additional context**
- I'm not sure if this happens on other tv's but sense Google TV's doesn't have a file explorer build in, you would have to download one off the store but cloudstream does not work with them for some odd reason.

**Comment by LagradOst** [comment]
I use ActivityResultContracts.OpenDocument https://github.com/LagradOst/CloudStream-3/blob/092fad148bec455dc84347fd1c54cc28d344438c/app/src/main/java/com/lagradost/cloudstream3/utils/BackupUtils.kt#L146

And even if a file explorer exist on your device that does not mean that the file explorer supports this action. This is ***not*** a bug with cs3. This is the intended way of doing it on android, however I might have to do smth like this https://stackoverflow.com/questions/49697630/open-file-choose-in-android-app-using-kotlin for devices that does not have storage support out of the box

**Comment by Goldenfreddy0703** [comment]
Hey thank you so much for responding and i understand. If we could have a filepicker soon, that would be great and im happy to hear that. 

Again, Thank you very much.

**Comment by Goldenfreddy0703** [comment]
Hey there, Sorry for bothering you but i know this a low priority issue but would there be anyway i can just copy the contents of the cs3 file that a backed up and paste it in a box in the cloudstream app or like a way to open the data and paste to contents in it like how you have the "Show Logcat 🐈" button.

**Comment by Goldenfreddy0703** [comment]
Hey @LagradOst , i made this example for you of what i mean to help understand more. 
![cs3 view example button](https://user-images.githubusercontent.com/62456796/163044276-4582e645-aae8-435b-b662-2c809d473613.png)

**Comment by Goldenfreddy0703** [comment]
Hey so nevermind about this issue, it turns out that you have to find certain file explorers and i finally found one that works with my tv and that works with this app. This was all thanks to the AnExplorer for Android TV. 

Thank you very much for helping me out and sorry if i caused any trouble.
