### ISSUE TITLE
Notch issue in full screen mode

### ISSUE THREAD

**Issue by Starlord619** [LagradOst/CloudStream-3#90]
While playing videos in full screen mode the video doesnt cover the total screen. There is still a black area seen near the notch which is distracting
![IMG_20210910_090010](https://user-images.githubusercontent.com/90435378/132796464-8450db37-1a2f-4b13-b230-3f9779f1f0ce.jpg)
![IMG_20210910_090039](https://user-images.githubusercontent.com/90435378/132796469-d8af4f49-9d10-4be5-b7df-c856a00cff47.jpg)
![Screenshot_2021-09-10-08-41-49-363_com lagradost cloudstream3](https://user-images.githubusercontent.com/90435378/132796473-67539692-0d12-4fdc-a43d-fb4ce0b0462a.jpg)

**Comment by LagradOst** [comment]
Should be fixed.
