### ISSUE TITLE
Invideo subtitle on/off

### ISSUE THREAD

**Issue by tywentghxst** [LagradOst/CloudStream-3#907]
Can you please add a button to turn off and on subtitles on the video player instead of only being able to turn it off from the settings, my wife loves subtitles and I hate them😂😭, and it'd be so much nicer for us to just turn it off and on in the video player like alot of other apps do instead of having to find it in the settings everytime we go to watch something, thank you for your hard work!

**Comment by MrConqueror** [comment]
> Can you please add a button to turn off and on subtitles on the video player instead of only being able to turn it off from the settings, my wife loves subtitles and I hate them😂😭, and it'd be so much nicer for us to just turn it off and on in the video player like alot of other apps do instead of having to find it in the settings everytime we go to watch something, thank you for your hard work!
Click Source

**Comment by MrConqueror** [comment]
> Can you please add a button to turn off and on subtitles on the video player instead of only being able to turn it off from the settings, my wife loves subtitles and I hate them😂😭, and it'd be so much nicer for us to just turn it off and on in the video player like alot of other apps do instead of having to find it in the settings everytime we go to watch something, thank you for your hard work!

Click Source

**Comment by LagradOst** [comment]
Click the source button in videoplayer

**Comment by tywentghxst** [comment]
Thank you!!!
