### ISSUE TITLE
Chromecast support.
The chromecast feature isn't working. I've tried casting from multiple sources and it doesn't work. 

### ISSUE THREAD

**Issue by transferableethos** [LagradOst/CloudStream-3#908]
**Guidelines:**
- [ ] It **is not** a duplicate issue.
- [ ] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**

**Expected behavior**

**Screenshots or video**

**Device (please complete the following information):**
 - Android Version: [e.g. Android 11 API 30, Android TV] 
 - App Version: [e.g. v2.7.14]
 - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]

**Additional context**

**Comment by LagradOst** [comment]
Already exist
