### ISSUE TITLE
Just a minor changes 

### ISSUE THREAD

**Issue by MrConqueror** [LagradOst/CloudStream-3#916]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
![IMG_20220404_084107](https://user-images.githubusercontent.com/102837820/162097106-da995103-1ae8-431b-b3cc-034e58b23661.jpg)
Instead source icon over the homepage
- New feature
- Other

**Describe your request here** *(fill this up)*
- [ ] How it works.
- [ ] Issues it solves.
- [ ] Why it is needed.

**Other related info**

**Comment by LagradOst** [comment]
no
