### ISSUE TITLE
Trailers.to removed?

### ISSUE THREAD

**Issue by dennis90a** [LagradOst/CloudStream-3#92]
Hello LagradOst, thanks for the really nice app!

I noticed in the 1.7.6 update, support for trailers.to has been removed? It has also been removed from the readme. Can I know why this was done? Also, please re-add support for it.

Thanks

**Comment by LagradOst** [comment]
No. Trailers.to was removed due to them making it login only. it only works for like 10% of users 50% of the time. IF you REALLY want to use it, donate 40 benenes and restart

**Comment by dennis90a** [comment]
I donated 43 benenes using the button at the bottom and then restarted, however I don't see trailers.to when I search for a movie

**Comment by dennis90a** [comment]
Maybe you should add it to the README
