### ISSUE TITLE
Add option to toggle HD marker

### ISSUE THREAD

**Issue by musty2840** [LagradOst/CloudStream-3#924]
for some people like me find it unnecessary, so it'll be good option if you can add toggle to show and not show it for people that like and didn't like this feature.

**Comment by MrConqueror** [comment]
> for some people like me find it unnecessary, so it'll be good option if you can add toggle to show and not show it for people that like and didn't like this feature.

Yeah i found it unecessary too, because you can always change the quality of the movie in Source in the player. I hope there's an option to turn them off or remove it permanently. Title Text is already blocking the Title in the poster plus this HD text thing.
