### ISSUE TITLE
Only a few movies/series work on Trailers.to

### ISSUE THREAD

**Issue by JimZiii** [LagradOst/CloudStream-3#929]
![151702811-efeeb374-f547-454a-a384-1ffe8af8b02c](https://user-images.githubusercontent.com/7854537/162524847-ff56de55-6ca1-4c09-b854-6de8f519a8b1.jpg)
The majority of series and movies on Trailers.to don't work, i just get a quick flash of the above image. If i download i get a short clip with that image. This goes for new and old series. Even if i pick Trailers.to as source on the homepage, the vast majority of content on the homepage doesn't work.  
Seems either I'm doing something wrong or it's pretty useless to have it as a source if 80% of the search matches and homepage content doesn't work.
Edit: seems like there might be few more movies working than series but i'm not sure

**Comment by Stormunblessed** [comment]
![Screenshot_20220408-150233_CloudStream_Beta_1.png](https://user-images.githubusercontent.com/86633626/162529993-15cb6adc-6f7b-4e12-9ab1-d2abca2b56b7.png)

Read this text please

**Comment by JimZiii** [comment]
> ![Screenshot_20220408-150233_CloudStream_Beta_1.png](https://user-images.githubusercontent.com/86633626/162529993-15cb6adc-6f7b-4e12-9ab1-d2abca2b56b7.png)
> 
> Read this text please

First of all, that's wrong because on trailers.to pretty much everything says that and the rare movies/series that actually work also say that.

Im just saying, why have the site as a source when 80%, or maybe even more, of its content on both search results and when selected on the homepage doesn't work at all.
Unless there's a way to get these videos to work, it's a complete waste of space
