### ISSUE TITLE
Mx player

### ISSUE THREAD

**Issue by Yashmak620** [LagradOst/CloudStream-3#93]
Can you please add the option to play on external app like mx player because vlc player doesn't support all videos. Please 🥺

**Comment by bienconsuelo21** [comment]
> Can you please add the option to play on external app like mx player because vlc player doesn't support all videos. Please 🥺

The the working on it

**Comment by ArjixWasTaken** [comment]
> > Can you please add the option to play on external app like mx player because vlc player doesn't support all videos. Please 🥺
> 
> The team working on it

LMAO, are you ignoring the "wontfix" label?

**Comment by toukaku0** [comment]
'Copy link' works.
Choose 'copy link' and paste it in 'network stream' then add .mp4 or .mkv at the end.
