### ISSUE TITLE
Null object reference

### ISSUE THREAD

**Issue by nicknitewolf** [LagradOst/CloudStream-3#930]
**Guidelines:**
- [ ] It **is not** a duplicate issue.
- [ ] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**
1. Open any media description page
2. Black screen with error shown
3. Attempt to invoke interface method
'android.media.session.ISessionController
android.media.session.ISession.getController()'on a null object reference

**Expected behavior**

**Screenshots or video**

**Device (please complete the following information):**
 - Android Version: [e.g. Android 11 API 30, Android TV] 
 - App Version: v2.8.16
 - Provider: SolarMovie

**Additional context**

**Comment by nicknitewolf** [comment]
Low key not sure how to debug this since I dont really want to enable adb on this tv LOL

**Comment by LagradOst** [comment]
Have you checked prerelease?

**Comment by nicknitewolf** [comment]
> Have you checked prerelease?

Its working fine in pre release. Did you change anything in between?

**Comment by LagradOst** [comment]
I have no idea, a lot of stuff change between pre and stable. I assume it is fixed because it is pre
