### ISSUE TITLE
black background in player

### ISSUE THREAD

**Issue by ourslfs** [LagradOst/CloudStream-3#933]
*Guidelines:*
- It is not a duplicate issue.
- It is not a request to add a website.

*UI/UX enhancement:*

*As of now, when you play some movies that has different display aspect compared to your device you have grey background, it would be nice to have an option to make it completely black * 

*![Screenshot_20220409-184617.jpg](https://user-images.githubusercontent.com/78319733/162581510-a6a6d8ea-4754-4ce4-8609-bfc280ddaf7e.jpg)*

**Comment by LagradOst** [comment]
It is black, are you able to replicate with another video?

**Comment by ourslfs** [comment]
tried another movie, the first screenshot is built-in player, another one is mpv ![Screenshot_20220409-201829.jpg](https://user-images.githubusercontent.com/78319733/162584691-0d54d8df-f472-48d0-8bc7-0386da7ff973.jpg)
![Screenshot_20220409-202014.jpg](https://user-images.githubusercontent.com/78319733/162584699-8d60c600-7d1e-4b6f-a4a0-588963135b9e.jpg)
