### ISSUE TITLE
Birghtness/Lightning + Sites 

### ISSUE THREAD

**Issue by gadz91** [LagradOst/CloudStream-3#94]
The brightness issue is not fix well.
It only darken/brigthen the app meaning the brightness setting is not synchronize.
My phone is vivo v9. 
I don't know if its only in my phone or the same issue with others.

You can also use this sites for more site(s) added.
https://3db7.xyz/stream/website

More power!

**Comment by gadz91** [comment]
https://user-images.githubusercontent.com/86019036/133017374-b2fe1050-b460-4b9b-8c1c-dc22be51c854.mp4

**Comment by gadz91** [comment]
As you can see the in the video, I was turn the brightness in to max but when I go to the brightness setting on my phone its not synchronize to the app brightness volume...
Try to do the same.

**Comment by LagradOst** [comment]
You want true brightness 😔

**Comment by gadz91** [comment]
I feel sorry for that. But this thing will be great. 
If it is impossible to fix then I/we will adjust. 👍

**Comment by LagradOst** [comment]
True brightness was added but you have to enable modify system settings for it to work
