### ISSUE TITLE
Cast to Roku, Roku TV

### ISSUE THREAD

**Issue by gladel** [LagradOst/CloudStream-3#948]
**Guidelines:**
- [ ] It **is not** a duplicate issue.
- [ ] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- New feature

**Describe your request here** *(fill this up)*
- [ ] Screencast to Roku streaming device or Roku TV
- [ ] Screencast
- [ ] To have better viewing experience

**Other related info**

**Comment by LagradOst** [comment]
https://support.roku.com/article/208754928 screen mirroring is android specific not app specific. If it is not that you are referring to send a link to it, because I cant find any resources about it.
