### ISSUE TITLE
App is crashing at the end of an episode

### ISSUE THREAD

**Issue by venkat2305** [LagradOst/CloudStream-3#949]

**Comment by LagradOst** [comment]
Not verbose, need more info

**Comment by venkat2305** [comment]
I was using the latest pre release version. I started watching anime , by the time it reached like end of the episode just 2 or 3 min before the end the app crashed to home screen. It happened again with other episodes as well

**Comment by LagradOst** [comment]
Ok, what are your cache settings?

**Comment by LagradOst** [comment]
Are you able to replicate it and how?

**Comment by venkat2305** [comment]
> Are you able to replicate it and how?

yes,  as i already told  you.
start watching an episode, as outro is yet to start , the app crashes.
i installed the stable one now.

**Comment by LagradOst** [comment]
@venkat2305 and how? Give me an example episode

**Comment by LagradOst** [comment]
Try latest pre in about 10min

**Comment by venkat2305** [comment]
yea , its fixed.
