### ISSUE TITLE
Source error: could not stream

### ISSUE THREAD

**Issue by mizzunet** [LagradOst/CloudStream-3#96]
Cannot play this movie from AllMoviesForYou source

![Screenshot_20210913-170528_Gallery](https://user-images.githubusercontent.com/10193999/133076678-9dc13ecf-b0a5-4ff7-a33c-054786a456bf.png)

While it does play from https://allmoviesforyou.co/movies/ad-astra-4/

**Comment by ArjixWasTaken** [comment]
Uhh, that server (streamhub) is not supported.
