### ISSUE TITLE
< Download Feature >

### ISSUE THREAD

**Issue by Akashi123-deep** [LagradOst/CloudStream-3#972]
I have a comment on a download that I consider to be a very important feature of an application in view of its value. I hope that it will give it some effort.  I wanted to download one of my favorite series, but I was surprised that the download was so slow that I downloaded it from Google and took a few seconds.I hope developers will improve the download feature for faster speed and better adaptation to network conditions

**Comment by LagradOst** [comment]
😐 it is not google servers
