### ISSUE TITLE
Unable to select arrows on firstick app

### ISSUE THREAD

**Issue by Masterfinri** [LagradOst/CloudStream-3#981]
Cannot click on arrows to see more popular movies escetra  on firestick
![156929103-e0402be1-7a20-4118-a4b6-ddf294f4da83](https://user-images.githubusercontent.com/104240676/164865668-85984666-5472-4a7e-a738-b9fb5ac189a4.jpg)

**Comment by LagradOst** [comment]
Those arrows should not exist, are you running pre or stable

**Comment by Masterfinri** [comment]
Stable I'm pretty sure

**Comment by LagradOst** [comment]
It is fixed on pre-release by removing the arrows
