### ISSUE TITLE
Subtitle download with the movie/episode

### ISSUE THREAD

**Issue by Korontos123** [LagradOst/CloudStream-3#982]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature X
- Other

**Describe your request here** *(fill this up)*
- [x] How it works.
- [ ] Issues it solves.
- [ ] Why it is needed.

hello , so  i've been using the app for +1 week and its working perfectly , but i'd like to suggest a feature to add and its selecting the sub file to download with the movie/epiosde , i know that it automatically download the english sub file but it doesn't give you the option to select another sub file to download , thanks

**Other related info**

**Comment by LagradOst** [comment]
Yes, check settings. Also if you hold you can download the subtitle file you want
