### ISSUE TITLE
Egybest API 500 Internal Server Error

### ISSUE THREAD

**Issue by xVoldx** [LagradOst/CloudStream-3#987]
![image](https://user-images.githubusercontent.com/62064902/164914841-0de67229-5ad9-4ad6-a5fc-86fca152c752.png)

the [api ](https://zawmedia-api.herokuapp.com)used to scrap egybest direct link is dead

![image](https://user-images.githubusercontent.com/62064902/164914866-69ba929d-9a92-4823-8bc8-99f729f6c3bc.png)

**Comment by LagradOst** [comment]
@ImZaw iirc

**Comment by LagradOst** [comment]
fixed
