### ISSUE TITLE
Custom Font for App

### ISSUE THREAD

**Issue by Nebula6531** [LagradOst/CloudStream-3#988]
**Choose one of the following:**
- UI/UX enhancement

**Describe your request here** *(fill this up)*
Could you add a setting to set and import custom fonts for the apps UI and navigation. I know it is implemented for subs but having it customisable for the rest of the app would be a nice touch 

**Other related info**

**Comment by LagradOst** [comment]
No, because no

**Comment by Nebula6531** [comment]
:(

**Comment by LagradOst** [comment]
Ye it is very complicated to set the font of one item via code and (practicly) impossible to do that to entire app
