### ISSUE TITLE
import arabic sub file problem

### ISSUE THREAD

**Issue by Korontos123** [LagradOst/CloudStream-3#992]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [ ] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**

hello , so there is a problem , when i am playing a movie or an episode then import an arabic sub file most of the time the sub just show me " ???????? " or some weird symbols ,
![Screenshot_20220424-210352_CloudStream Beta](https://user-images.githubusercontent.com/104093479/165066222-3decc6b5-a558-4e5c-af6a-d79481319409.jpg)
 i hope you fix it . thank you

**Expected behavior**

**Screenshots or video**

**Device (please complete the following information):**
 - Android Version: [e.g. Android 11 API 30, Android TV] 
 - App Version: [e.g. v2.7.14]
 - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]

**Additional context**
![Uploading Screenshot_20220424-210352_CloudStream Beta.jpg…]()

**Comment by LagradOst** [comment]
No screenshot?

**Comment by LagradOst** [comment]
Also does the subtitle file work in other players like vlc? Sometimes the encoding on subtitle files are wrong

**Comment by Korontos123** [comment]
> No screenshot?

i uploaded a one

**Comment by Korontos123** [comment]
> Can you change your font? I think your current does not support arabic. Try to import a font you know supports arabic text.

nothing changed :(
![Screenshot_20220425-153115_CloudStream Beta](https://user-images.githubusercontent.com/104093479/165110699-8a689b8d-6199-4373-983c-045406ca9d21.jpg)

**Comment by LagradOst** [comment]
And you are 100% sure that the font you are using supports arabic?

**Comment by LagradOst** [comment]
Send subtitle file

**Comment by Korontos123** [comment]
> Send subtitle file

https://www.mediafire.com/file/9khfr2p0szkjye8/Deadpool.2016.720p.BluRay.x264-SPARKS.srt/file

**Comment by Korontos123** [comment]
> And you are 100% sure that the font you are using supports arabic?

i am using a font that i downloaded specially for arabic subtitles so yeah im 100% sure

**Comment by LagradOst** [comment]
I looked at the subtitle file, and it looks like that file is badly encoded. Does this happend to all subtitles or just this file?

**Comment by Korontos123** [comment]
> I looked at the subtitle file, and it looks like that file is badly encoded. Does this happend to all subtitles or just this file?

not all but about 90% of them

**Comment by Korontos123** [comment]
another one not working : https://www.mediafire.com/file/hr27mj4lbk3yto5/Se7en.1995.720p.OAR.BluRay.DTS.x264-DON.srt/file

**Comment by omar-2001-w** [comment]
![Screenshot_2022-05-30-11-50-51](https://user-images.githubusercontent.com/64628921/170956102-653eab13-3dd5-4b54-a4c1-26b06c79f6cb.png)

Please add this feature in the video player to make subtitle files work
This picture from vlc

**Comment by omar-2001-w** [comment]
Oh sorry i try same subtitle it didn't work in another player

**Comment by LagradOst** [comment]
This should be fixed in the latest commit
