### ISSUE TITLE
egybest api

### ISSUE THREAD

**Issue by Korontos123** [LagradOst/CloudStream-3#994]
**Guidelines:**
- [ X ] It **is not** a duplicate issue.
- [ X ] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**
  

Hello , so the egybest api is fixed but when i search a tv show named " الفوندو " then open the last episode it just give me this screen then go back to the episodes list , i hope you fix the api and make it more stable
![Screenshot_20220425-113835_CloudStream Beta](https://user-images.githubusercontent.com/104093479/165073377-f9f4ac0c-51bb-424b-b79c-c42300dbb18a.jpg)

**Expected behavior**

**Screenshots or video**

**Device (please complete the following information):**
 - Android Version: [e.g. Android 8 API 30, Android TV] 
 - App Version: [e.g. v2.7.14]
 - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]

**Additional context**
i checked it in my friend's phone and the same problem happen .

**Comment by ImZaw** [comment]
![Screenshot_20220425-151144_CloudStream Beta](https://user-images.githubusercontent.com/42999156/165086558-29486835-5a6e-4c01-ae52-f1f62f070590.jpg)
works fine for me

**Comment by Korontos123** [comment]
> ![Screenshot_20220425-151144_CloudStream Beta](https://user-images.githubusercontent.com/42999156/165086558-29486835-5a6e-4c01-ae52-f1f62f070590.jpg) works fine for me

the problem didn't go away until i did " clear data " to the app , the beta version is full of stability issues but i know that they will get solved in the next official update ...
