### ISSUE TITLE
Egyptian/Arabic series 

Could you add a service that streams arabic series 


### ISSUE THREAD

**Issue by sharqo** [LagradOst/CloudStream-3#995]
**Guidelines:**
- [ ] It **is not** a duplicate issue.
- [ ] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*
- [ ] How it works.
- [ ] Issues it solves.
- [ ] Why it is needed.

**Other related info**

**Comment by ImZaw** [comment]
> **Guidelines:**
> 
> * [ ]  It **is not** a duplicate issue.
> * [ ]  It **is not** a request to add a website. Write it here instead [[providers] Some sites #24](https://github.com/LagradOst/CloudStream-3/issues/24)
> 
> **Choose one of the following:**
> 
> * UI/UX enhancement
> * New feature
> * Other
> 
> **Describe your request here** _(fill this up)_
> 
> * [ ]  How it works.
> * [ ]  Issues it solves.
> * [ ]  Why it is needed.
> 
> **Other related info**

There is already 3 Arabic providers which is EgyBest, MyCima, Akwam and I think they provide "Egyptian/Arabic series"
