### ISSUE TITLE
Gogo Servers not showing up on Gogoanime

### ISSUE THREAD

**Issue by Adbc3949** [LagradOst/CloudStream-3#998]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**

**Expected behavior**

**Screenshots or video**

**Device (please complete the following information):**
 - Android Version: [e.g. Android 11 API 30, Android TV] 
 - App Version: [e.g. v2.7.14]
 - Provider: [e.g. https://trailers.to/en/movie/4391225/red-notice-2021]

**Additional context**

**Comment by Adbc3949** [comment]
Only Stream SB Servers are Showing Up and not the Gogoanime ones

**Comment by LagradOst** [comment]
gogo have probs changed their crypt key @Blatzar

**Comment by Adbc3949** [comment]
This is Fixed so I'll close the Issue
