### ISSUE TITLE
Hindi Audio

### ISSUE THREAD

**Issue by imurreflection** [LagradOst/CloudStream-3#999]
Dear Dev,
Is it possible to include different audios option like Hindi wherever available.

Note: I am not asking for any site addition. I am Just asking if it's possible to change audio. Example, Snowpiercer Series from Netflix has more than 5 audios and we can select language of our choice example Hindi.

If you search the same series in Hindi, you will find various hits but all of them have English audio but surprisingly Hindi Subtitles. 

Thank you

**Comment by LagradOst** [comment]
The sites we scrape from does not have hini audio, we dont host any content, we are not netflix. If there is a site used that has hindi audio that is already in the app then it will be implemented, but atm this goes in #24
